### ISSUE TITLE
The remote host forcibly closed an existing connection (erro 10054)（erro 10054）

### ISSUE THREAD

**Issue by lianxintao** [rustdesk/rustdesk#106] opened 2021-06-22 15:51 UTC
The connection is successful and I see the desktop, but after a while it displays "the remote host forcibly closed an existing connection (erro 10054)", and then disconnect?
How to solve this problem? (The windows firewall has been turned off)

**Comment by rustdesk** [comment] 2021-06-22 15:53
Cause. Error 10054 occurs when the connection is reset by the peer application, usually due to an incorrect firewall configuration. Find more information about this error on Microsoft Development Center. Check the following items to ensure that your system, firewall and router are configured correctly.

**Comment by rustdesk** [comment] 2021-06-22 15:56
It is hard to fix this issue from my side. Hope someone having the same issue can help you.

**Comment by lianxintao** [comment] 2021-06-24 00:57
OK，thank you

**Comment by rustdesk** [comment] 2021-09-27 07:33
Hope someone having this issue can dig in. Unfortunately, only reporter, no solver.

**Comment by rustdesk** [comment] 2021-11-17 01:44
Another from Google Play. Urgent.

**Comment by rustdesk** [comment] 2021-11-19 01:44
Looking for helper, I really can not reproduce it on my side, very very embarssing.

**Comment by rustdesk** [comment] 2021-12-22 06:06
@lianxintao can you reproduce this issue? Hope you can help test.

**Comment by Gitkingly** [comment] 2022-05-29 16:17
Looks like I have the same issue. When I connect the remote linux machine by ssh with tcp tunnel in my local windows machine, it firstly connected successfully, if I do not input anything on the ssh session within about 15 seconds, the connection will be closed with error message "Connection to localhost closed by remote host".

Even though I had set the ssh server/client keepalive interval to 60 seconds, it did not help.

Please note the remote desktop was working very well without any interrupts during the disconnections of SSH sessions.

**Comment by rustdesk** [comment] 2022-07-30 16:49
conclusion: https://github.com/rustdesk/rustdesk/issues/1113#issuecomment-1200250142

**Comment by rustdesk** [comment] 2022-07-30 16:50
close this so that we can focus on its dup #1113.

**Closed by rustdesk** 2022-07-30 16:50 UTC
Labels: bug, help wanted, good first issue
