### ISSUE TITLE
Blurry screen [nightly]

### ISSUE THREAD

**Issue by KoalaBear84** [rustdesk/rustdesk#2180] opened 2022-11-17 07:15 UTC
**Describe the bug you encountered:**

The 'remote' screen is blurry. It looks like it's depending on the odd or even height of the RustDesk window, and maybe also the width.

https://user-images.githubusercontent.com/5886900/202380107-1ac5954d-7be1-40a7-9173-e835f1e3d740.mp4

![image](https://user-images.githubusercontent.com/5886900/202380075-58c9a8dc-2885-4671-93b6-aa217a8e03e0.png)

**What did you expect to happen instead?**

Always clear screen when no scaling.

**How did you install `RustDesk`?**

**RustDesk version and environment**

Latest nightly on this repo, just run.

**Host**
Windows 10 Enterprise 22H2 (OS Build 19045.2251)
GitHub release, [latest nightly](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-pc-windows-msvc.exe) of 7 hours ago

**Client**
Windows 10 Pro 21H2 (OS Build 19044.2251)
@Kingtous nightly release, installed.

**Comment by fufesou** [comment] 2022-11-17 08:50
Thanks. @KoalaBear84  
I can't reproduce this problem. But I almost know where the problem is. I'll read the dev doc the make the picture better.

**Comment by KoalaBear84** [comment] 2022-11-17 08:52
Great. Not sure if it has anything to do with the screen sizes.

Host: 2560 x 1440
Client: 1920 x 1200

**Comment by rustdesk** [comment] 2022-11-17 09:02
If even number has better quality, we can always scale to even width/height, remaining one pixel as padding. let's test first, and also try painting argument adjustment first.

**Comment by fufesou** [comment] 2022-11-18 01:40
@KoalaBear84 Hi, would you please try to test if it is blured when you only change the height or width of the window?
The picture is kept aspect ratio. Changing height may not cause rescaling if window width is not big enough.
I just want to make sure if the problem exists without rescaling the picture.

**Comment by KoalaBear84** [comment] 2022-11-18 07:56
I hope this is the information you are looking first. At first the Rustdesk window is larger than the clients window, but it still blurs it. And also after the RustDesk window is smaller than the clients desktop, it keeps on blurring.

https://user-images.githubusercontent.com/5886900/202650257-a1f192a2-3a14-459a-8154-8ea58ac409c7.mp4

**Comment by rustdesk** [comment] 2022-11-18 08:00
bluring is expected if picture is scaled. Please compare with 1.1.9 with the same scale.

**Comment by fufesou** [comment] 2022-11-18 08:16
It seems you are testing with orignal scale. Can you help make sure the option "Scale original" or "Scale adaptive"? Which one causes blurring or both?
![image](https://user-images.githubusercontent.com/13586388/202653764-ecbec96d-79db-44b5-be50-a8bb207f0338.png)

**Comment by fufesou** [comment] 2022-11-18 08:27
Thanks. I've reproduced this problem. The picture is blured while it is not scaled.

**Comment by rustdesk** [comment] 2022-11-18 14:57
https://github.com/flutter/flutter/issues/115653

**Comment by fufesou** [comment] 2022-11-18 15:26
@KoalaBear84 Hi, would you please try if this problem is fixed on your env? 
https://github.com/fufesou/rustdesk/releases/tag/nightly
The build action is almost done.
https://github.com/fufesou/rustdesk/actions/runs/3497958692

**Comment by KoalaBear84** [comment] 2022-11-21 07:52
Just tested it again with the newest nightly of ~7 hours ago, removed the old version, installed the newest. Same issue. But now also flickering, I think that wasn't there before but might be because of switching the modes.

https://user-images.githubusercontent.com/5886900/202994438-9e8d43c5-00c4-4adf-81b5-e279d008a4d6.mp4

**Comment by rustdesk** [comment] 2022-11-21 08:16
> again

：（

**Comment by fufesou** [comment] 2022-11-21 09:02
@KoalaBear84 Hi, nightly build is not correct today. We're generating new nightly build. Please try later after the action is done.
https://github.com/rustdesk/rustdesk/actions/runs/3512742639

**Comment by KoalaBear84** [comment] 2022-11-21 09:38
Latest nightly generated version of 30 minutes ago is working as expected 👍

**Comment by severach** [comment] 2022-11-25 00:32
It's not fixed for me.

Both Linux local and Windows remote have been updated to latest nightly or git.

[x] Scale Original
[x] Good Image Quality

Fullscreen is perfect. When not not full screen as maximized or small window gives fuzzy text. Moving the mouse which moves the remote screen changes the location of the fuzziness. Adjusting the size of the window also changes the fuzziness including when the local window is larger than the remote screen.

The local local screen is 1920x1200.

This screenshot is from a Windows remote at 1600x900. I sized the local window, always larger than the remote screen, until I got the fuzz to be really bad. When I adjust the local window client area to exactly 1600x900 the quality is perfect.

![Screenshot from 2022-11-24 19-15-38](https://user-images.githubusercontent.com/7297892/203877610-33dd6911-9376-40b3-9f32-bfd1e0971e63.png)

Any local window size equal to or larger than the remote screen should have no effect on image quality. With Scale Original no window size should have any effect on image quality.

This screenshot is from a Windows remote at 1920x1200 where the local window size has been reduced to maximize poor quality and clipped text.

![Screenshot from 2022-11-24 18-39-33 Rustdesk](https://user-images.githubusercontent.com/7297892/203877773-e7b4066f-46cf-4817-a9e4-866b8236c925.png)

**Comment by fufesou** [comment] 2022-11-25 01:12
> [flutter/flutter#115653](https://github.com/flutter/flutter/issues/115653)

@severach Thank you for your detailed feedback.
Is "Scale Adaptive" work fine?
I'll test LInux --> Win, but I can't promise to fully fix this issue.

**Comment by severach** [comment] 2022-11-25 05:39
Scale Adaptive is better and is as good as can be expected with non integer scaling.

The Windows client is no better than Linux.

It's definitely Flutter. I reworked [rustdesk-git](https://aur.archlinux.org/packages/rustdesk-git) from `build.py` to produce Flutter or Sciter. I switched the local client to Linux Sciter and now the text looks good at any resize larger or smaller. The the remote server is still running Windows Flutter. You don't offer a Windows Sciter nightly. I switched my Windows client back to the Sciter built 1.1.9 and text looks good there too.

For Sciter, no more auto mouse scroll for small windows and the vertical scrollbar seems missing.

The Flutter thread mentioned that some resolutions didn't exhibit the problem. I tried all I have on this Lenovo LT2452: 800x600,1024x768,1280x720,1440x900,1280x1024,1680x1050,1600x1200,1920x1080,1920x1200. No resolution showed clear text. Some resolutions were much worse, possibly due to changing the numerics of the Flutter bug or possibly because the monitor's non integer scaling makes everything worse. Native OS windows always looked much better than the remote window.

**Comment by rustdesk** [comment] 2022-11-25 05:47
@fufesou scrollbar mode in sciter needs to be test, win32 still use it, we need to make it work.

**Comment by fufesou** [comment] 2022-11-29 13:28
@severach Hi, sciter version does not support auto mouse scroll now.
I've tested sicter version. I can see both vertical and horizental scrollbars.

https://user-images.githubusercontent.com/13586388/204540264-fff57682-c56b-451d-a0c1-9b2c8bff22b4.mp4

**Comment by fufesou** [comment] 2022-11-29 15:41
https://github.com/flutter/flutter/issues/115653#issuecomment-1330843151

**Comment by fufesou** [comment] 2022-11-30 14:59
@severach Hi, I've push the PR to fix this issue. Can you please download the nightly and test tommrow?
https://github.com/rustdesk/rustdesk/pull/2395

**Comment by severach** [comment] 2022-11-30 18:20
The patch was in time the nightly. Linux git and Windows nightly look good.

**Comment by severach** [comment] 2022-12-05 03:49
Blurry is fixed. Please close.

**Closed** 2022-12-05 03:55 UTC
Labels: bug
