### ISSUE TITLE
Incorrect Auto codec selection Android 14 phone

### ISSUE THREAD

**Issue by mikekgr** [rustdesk/rustdesk#8101] opened 2024-05-20 09:41 UTC
### Bug Description

Using the today nightly release (20-05-2024) I discover an error.
When I am trying to connect to my Android 14 phone from Windows 10, Windows 11 PC then in the Auto possition it select codec H265. Using this Auto codec I get not image. If I manually change to let's say VP9, AV1, H264 etc then I have normal image again.
Please see the Auto codec logic.

Thanks and Best 

### How to Reproduce

Just follow my steps above

### Expected Behavior

To be working fine in the Auto codec possition

### Operating system(s) on local side and remote side

Windows 10/11 => Android 14 phone

### RustDesk Version(s) on local side and remote side

nightly release 20-05-2024

### Screenshots

no

**Comment by 21pages** [comment] 2024-05-20 10:12
@mikekgr Thanks for your feedback, could you give the related log here? Here is steps:
1. Enable the `Transfer file` permission (Make it able to write external stroage) and restart android app.
2. Use auto codec to connect to your android
3. The log is in External stroage -> RustDesk -> Logs -> rs_rCurrent.log
4. You can 
 * send the log to my email: “cGFnZXMyMUAxNjMuY29tCg==” （base64), 
 * or paste the log start with:`scrap::common::hwcodec: all codec info:` and `scrap::common::hwcodec: available H265 encoders:`, and see if there are many `hwcodec::ffmpeg_ram::encode: Error encode: -1`.

**Comment by mikekgr** [comment] 2024-05-20 10:26
> @mikekgr Thanks for your feedback, could you give the related log here? Here are steps:
> 
> 1. Enable the `Transfer file` permission (Make it able to write external stroage) and restart android app.
> 2. Use auto codec to connect to your android
> 3. The log is in External stroage -> RustDesk -> Logs -> rs_rCurrent.log
> 4. You can
> 
> * remove server info and send the log file to my email: `cGFnZXMyMUAxNjMuY29tCg==` （base64),
> * or paste the log start with:`scrap::common::hwcodec: all codec info:` and `scrap::common::hwcodec: available H265 encoders:`, `scrap::common::codec: new encoder: HWRAM(HwRamEncoderConfig`,  and see if there are many `hwcodec::ffmpeg_ram::encode: Error encode: -1`, serveral failed encoding is normal.
> 
> ![file-permission](https://private-user-images.githubusercontent.com/14891774/332028597-9a0068f9-5a63-4e1d-9edf-edf542500fd6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDA3ODQsIm5iZiI6MTcxNjIwMDQ4NCwicGF0aCI6Ii8xNDg5MTc3NC8zMzIwMjg1OTctOWEwMDY4ZjktNWE2My00ZTFkLTllZGYtZWRmNTQyNTAwZmQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEwMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MDIyOTljYzBjNDJlYWFhYzBhMzU0ZDI2YzdhYjg0NDljZjBjZTMwNjk4MThmMDUyY2EzNWMwOTA3OWMxN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DQeJBpoTSW0sfF6u8X05ejJ3tpJ--Yfx0qs2iGSATao)

OK I sent you the log from my email : bWlrZWtAb3BlbmZvcmFsbC5jb20=

Tell me if you need anything more. Thanks

**Comment by 21pages** [comment] 2024-05-20 10:37
There are not many `Error encode: -1`, 
* If you control it while it's playing video, will there be hundreds of `Error encode: -1`?
* Enable quality monitor, is fps always zero?

**Comment by mikekgr** [comment] 2024-05-20 10:50
> Thanks for the log, there are not many `Error encode: -1`,
> 
> * If you control it while it's playing video, will there be hundreds of `Error encode: -1`?
> * Enable quality monitor, is fps always zero?
> 
> ![1716201568643](https://private-user-images.githubusercontent.com/14891774/332035262-9b448a8b-0e0a-48b4-a76a-4fe84da40a1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDE4ODcsIm5iZiI6MTcxNjIwMTU4NywicGF0aCI6Ii8xNDg5MTc3NC8zMzIwMzUyNjItOWI0NDhhOGItMGUwYS00OGI0LWE3NmEtNGZlODRkYTQwYTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEwMzk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MzU2ZTNkMzYyMmMzZWEyOTBkNzIyODZiYTUwOTI4ODQzMmVjMGZmYmY1MDkyNTY4ZWU5YmVhYzBiZWMxN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O9h3V-jn_L7fWfooNqG5OWcMeQAgkxatg3QhgJKTVCw)

Well, in case of manual codec selection e.g. VP9 or AV1, (not the case of log file that was the try of H265) then the fsp IS NOT zero although I did not tried to play video. If you need more testing, I will try anything you need but after 1-1,5 hours.
Send me what do you need to check and I will reply after 1-1.5 hours.

**Comment by 21pages** [comment] 2024-05-20 11:03
Take your time, there's no rush.
And use this windows client to control other devices (or even itself) through h265 to see if the windows client can display h265 images normally.

**Comment by 21pages** [comment] 2024-05-20 13:05
Thanks for your feedback, when the previous pc is available, could you provide `%appdata%/rustdesk/config/RustDesk_hwcodec.toml`? It should support H265 decode.

**Comment by mikekgr** [comment] 2024-05-20 13:13
> Thanks for your feedback, when the previous pc is available, could you provide the file `%appdata%/rustdesk/config/RustDesk_hwcodec.toml`? It should support H265 decode, and notice whether fps is zero.

Yes, tomorrow I will do it and I will report here

**Comment by 21pages** [comment] 2024-05-20 13:30
Here is some debug tips:
After connection with H265, look the latest date file in `RustDesk\log`, there should have logs start with `try create vram decoder` or `try create ram decoder`, that is the decoder used for decoding, and you can find the decoder in `%appdata%/rustdesk/config/RustDesk_hwcodec.toml`, you can remove the used one and connect again, btw, vram decoders has higher priority than ram decoders, hope you can find some clues.

**Comment by 21pages** [comment] 2024-05-21 01:33
According to https://en.wikipedia.org/wiki/Intel_Graphics_Technology#Capabilities_(GPU_video_acceleration), i7-3770 CPU (Ivy Bridge) doesn't support H265. The reason may be that the current detection mistakenly think that d3d11 h265 decode acceleration is supported.

Please provide `%appdata%/rustdesk/config/RustDesk_hwcodec.toml` and run https://github.com/21pages/test/releases/download/test/decode_check.exe to verify it. I willl do more to improve the support check.

**Comment by mikekgr** [comment] 2024-05-21 03:59
> According to https://en.wikipedia.org/wiki/Intel_Graphics_Technology#Capabilities_(GPU_video_acceleration), i7-3770 CPU (Ivy Bridge) doesn't support H265. The reason may be that the current detection mistakenly think that d3d11 h265 decode acceleration is supported.
> 
> Please provide old `%appdata%/rustdesk/config/RustDesk_hwcodec.toml` and run new https://github.com/21pages/test/releases/download/test/decode_check.exe in termial to verify it. I willl do more to improve the support check.
> 
> And try https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64-more-hwcodec-check.exe, maybe this version will make h265 normal. If not, please give `%appdata%/rustdesk/config/RustDesk_hwcodec.toml` of this version.

Well the result of running decode_check.exe is:
vram decoders:
[2024-05-21T03:45:41Z ERROR hwcodec] [FFMPEG_VRAM_DEC] unsupported data format

[ERROR], sts=MFX_ERR_UNSUPPORTED(-3), `anonymous-namespace'::VplDecoder::init, Query at D:\rustdesk\hwcodec\cpp\mfx\mfx_decode.cpp:110
[2024-05-21T03:45:41Z ERROR hwcodec] [MFXDEC] Queryfailed, sts=-3
DecodeContext { device: None, driver: FFMPEG, luid: 40330, api: API_DX11, data_format: H264 }
DecodeContext { device: None, driver: MFX, luid: 40330, api: API_DX11, data_format: H264 }
[2024-05-21T03:45:41Z ERROR hwcodec] [FFMPEG_RAM_DEC] Failed to check support hevc
[2024-05-21T03:45:41Z ERROR hwcodec] [FFMPEG_RAM_DEC] check_support failed
[2024-05-21T03:45:41Z DEBUG hwcodec::ffmpeg_ram::decode] name:hevc device:AV_HWDEVICE_TYPE_D3D11VA new failed:12.4932ms
ram decoders:
CodecInfo { name: "h264", mc_name: None, format: H264, priority: 0, hwdevice: AV_HWDEVICE_TYPE_D3D11VA }
CodecInfo { name: "h264", mc_name: None, format: H264, priority: 3, hwdevice: AV_HWDEVICE_TYPE_NONE }
CodecInfo { name: "hevc", mc_name: None, format: H265, priority: 3, hwdevice: AV_HWDEVICE_TYPE_NONE }

The test programm: rustdesk-1.2.4-x86_64-more-hwcodec-check.exe  still does not work, still get H265 in the Auto place

The content of: %appdata%/rustdesk/config/RustDesk_hwcodec.toml is: 
ram = '''
{
  "e": [],
  "d": [
    {
      "name": "h264",
      "format": "H264",
      "priority": 0,
      "hwdevice": "AV_HWDEVICE_TYPE_D3D11VA"
    },
    {
      "name": "h264",
      "format": "H264",
      "priority": 3,
      "hwdevice": "AV_HWDEVICE_TYPE_NONE"
    },
    {
      "name": "hevc",
      "format": "H265",
      "priority": 3,
      "hwdevice": "AV_HWDEVICE_TYPE_NONE"
    }
  ]
}'''
vram = '''
{
  "e": [
    {
      "driver": "FFMPEG",
      "luid": 40330,
      "api": "API_DX11",
      "data_format": "H264"
    }
  ],
  "d": [
    {
      "driver": "FFMPEG",
      "luid": 40330,
      "api": "API_DX11",
      "data_format": "H264"
    },
    {
      "driver": "MFX",
      "luid": 40330,
      "api": "API_DX11",
      "data_format": "H264"
    }
  ]
}'''

Am I forgot something useful to you, don't hesitate to ask me, thanks

**Comment by 21pages** [comment] 2024-05-21 04:03
Could you provide the content of `%appdata%/rustdesk/config/RustDesk_hwcodec.toml` after running old RustDesk.exe? 
If you connect your phone with the new RustDesk.exe with H265, the image is still not normal?

**Comment by mikekgr** [comment] 2024-05-21 04:11
> %appdata%/rustdesk/config/RustDesk_hwcodec.toml

Help me to install the nightly release, after having rustdesk-1.2.4-x86_64-more-hwcodec-check.exe installed, tring to install the nightly release does not give me the known update gui button. How to do it ?

**Comment by 21pages** [comment] 2024-05-21 04:13
Uninstall the current one, and test doesn't need installation.

nightly: https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64.exe
test: https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64-more-hwcodec-check.exe

**Comment by mikekgr** [comment] 2024-05-21 04:19
> Uninstall the current one, and installation is not needed.
> 
> nightly: https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64.exe test: https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64-more-hwcodec-check.exe

I am trying to install the nightly release (after having installed your test release) and I can't . I am pretty sure that this one Build date: 2024-05-21 02:47 is your testy release. Am I right ?
In this case how to force to install the nightly release?

**Comment by 21pages** [comment] 2024-05-21 04:20
Uninstall with windows setting, or uninstall with `rustdesk.exe --uninstall`

**Comment by mikekgr** [comment] 2024-05-21 04:27
Same, see the screenshot, now running the nightly release:

![image](https://github.com/rustdesk/rustdesk/assets/15084551/ba02af72-f0b9-41ee-afb5-5dd4e7d5b134)

**Comment by 21pages** [comment] 2024-05-21 04:29
Now the fix has not been merged to the ngihtly build, with the nightly build you have installed now, could you provide the content of `%appdata%/rustdesk/config/RustDesk_hwcodec.toml`?

**Comment by mikekgr** [comment] 2024-05-21 04:31
> %appdata%/rustdesk/config/RustDesk_hwcodec.toml

Here is:

ram = '''
{
  "e": [],
  "d": [
    {
      "name": "h264",
      "format": "H264",
      "priority": 0,
      "hwdevice": "AV_HWDEVICE_TYPE_D3D11VA"
    },
    {
      "name": "h264",
      "format": "H264",
      "priority": 3,
      "hwdevice": "AV_HWDEVICE_TYPE_NONE"
    },
    {
      "name": "hevc",
      "format": "H265",
      "priority": 3,
      "hwdevice": "AV_HWDEVICE_TYPE_NONE"
    }
  ]
}'''
vram = '''
{
  "e": [
    {
      "driver": "FFMPEG",
      "luid": 40330,
      "api": "API_DX11",
      "data_format": "H264"
    }
  ],
  "d": [
    {
      "driver": "FFMPEG",
      "luid": 40330,
      "api": "API_DX11",
      "data_format": "H264"
    },
    {
      "driver": "MFX",
      "luid": 40330,
      "api": "API_DX11",
      "data_format": "H264"
    }
  ]
}'''

**Comment by 21pages** [comment] 2024-05-21 04:33
So the contents of `RustDesk_hwcodec.toml` are the same. what if connect itself, eg: if your ID is 1234567, connect to 1234567

**Comment by mikekgr** [comment] 2024-05-21 04:35
> So the contents of `RustDesk_hwcodec.toml` are the same. what if connect itself, eg: if your ID is 1234567, connect to 1234567

I did and I got connection with screen but with chaos as the screens repeat itself

**Comment by 21pages** [comment] 2024-05-21 04:39
Sorry, I provide wrong mothod, your computer doesn't support h265 encoding, could you connect to my computer with public server? I have send my RustDesk ID to your email.

**Comment by mikekgr** [comment] 2024-05-21 04:44
> Sorry, I provide wrong method, your computer doesn't support h265 encoding, could you connect to my computer with public server? I have sent my RustDesk ID to your email.

Please sent me  your email here: bWlrZS5rcmFuaWRpc0BnbWFpbC5jb20=
because my main email account has problems receiving emails from Chinese servers, sorry

**Comment by mikekgr** [comment] 2024-05-21 04:50
in your connection I had H265 in working condition !

**Comment by 21pages** [comment] 2024-05-21 04:52
> Well after return home, I did some new tests, this time using my laptop (Dell Latitude 7280, i5-7300U CPU @ 2.60GHz) having Windows 11 pro.

Did i5-7300U and  i7-3770 CPU connect to the same phone?

**Comment by mikekgr** [comment] 2024-05-21 04:54
> > Well after return home, I did some new tests, this time using my laptop (Dell Latitude 7280, i5-7300U CPU @ 2.60GHz) having Windows 11 pro.
> 
> Did i5-7300U and i7-3770 CPU connect to the same phone?

Yes these are connecting to my personal OnePlus 9 pro Android phone

**Comment by mikekgr** [comment] 2024-05-21 04:56
> the problem should still be that the android h265 encoding failed

Yes it remained at Connected, waiting for the image...

**Comment by 21pages** [comment] 2024-05-21 04:57
i5-7300U connect to android with H265: good
 i7-3770 CPU connect to android with H265: bad
 i7-3770 CPU connect to my computer with H265: good

Seems not reasonable, is  i5-7300U connect to android with H265?

**Comment by mikekgr** [comment] 2024-05-21 05:04
> i5-7300U connect to android with H265: good i7-3770 CPU connect to android with H265: bad i7-3770 CPU connect to my computer with H265: good
> 
> Seems not reasonable, is i5-7300U connect to android with H265?
"is i5-7300U connect to android with H265?"
Sure see the screenshot


![rustdesk-02](https://github.com/rustdesk/rustdesk/assets/15084551/7f024164-86b4-4568-9a3c-85420872cfbb)

**Comment by 21pages** [comment] 2024-05-21 05:06
Connect to your phone with  i7-3770 CPU , and enable file transfer,

If you control it while it's playing video, will there be hundreds of Error encode: -1 in the android log? If there are, the reason is android encoding failed.
Enable quality monitor, is fps always zero?

**Comment by mikekgr** [comment] 2024-05-21 05:06
> i5-7300U connect to android with H265: good i7-3770 CPU connect to android with H265: bad i7-3770 CPU connect to my computer with H265: good
> 
> Seems not reasonable, did you remember i5-7300U connect to android with H265 or other codec?
> 
> Connect to your phone, and enable file transfer,
> 
> * If you control it while it's playing video, will there be hundreds of `Error encode: -1` in the android log? If there are, the reason is android encoding failed.
> * Enable quality monitor, is fps always zero?

I can do these tests after returned home (8+ hours), where the Dell laptop is. Then I will be happy to send you the information you asked.

**Comment by 21pages** [comment] 2024-05-21 05:06
Thanks, take your time.

**Comment by mikekgr** [comment] 2024-05-21 05:09
> Ok. connect to your phone with i7-3770 CPU , and enable file transfer,
> 
> If you control it while it's playing video, will there be hundreds of Error encode: -1 in the android log? If there are, the reason is android encoding failed. Enable quality monitor, is fps always zero?

I can do this test because I am in front of this pc. Just tell me, using what coder? Obviously not H265 that is not working...

**Comment by 21pages** [comment] 2024-05-21 05:10
Use H265, because H264 is working, I want to know why H265 is not working,

**Comment by mikekgr** [comment] 2024-05-21 05:13
> Use H265, because H264 is working, I want to know why H265 is not working,

To understand well, you instruct me to connect from my pc having with i7-3770 CPU to my phone using H265 correct?
The problem here is when I trying to connect using H265 (in this setup) I can't get picture at all. How to see the Video I thing I misunderstood your instructions

**Comment by 21pages** [comment] 2024-05-21 05:17
> To understand well, you instruct me to connect from my pc having with i7-3770 CPU to my phone using H265 correct?

Yes

> How to see the Video?

Playing video is the method to let andorid encode many times to see whether it can encode successfully, showing correct image on i7-3770 CPU is not required.

**Comment by mikekgr** [comment] 2024-05-21 05:25
> > To understand well, you instruct me to connect from my pc having with i7-3770 CPU to my phone using H265 correct?
> 
> Yes
> 
> > How to see the Video?
> 
> Playing video is the method to let android encode many times to see whether it can encode successfully, showing correct image on i7-3770 CPU is not required.
> 
> After connection, could you send the android log and the computer log `%appdata%/RustDesk/log/rustdesk_rCURRENT.log` to my email

email with the requested Android phone log sent

**Comment by 21pages** [comment] 2024-05-21 05:44
`[2024-05-21 07:22:14.127371 +03:00] ERROR [src\flutter.rs:432] width/height mismatch: (1080,2412) != (1080,2428)`

Found the reason, I'll try to fix it.

**Comment by mikekgr** [comment] 2024-05-21 05:46
@21pages 
thanks, glad to help you

**Comment by 21pages** [comment] 2024-05-21 05:55
I want to analyze the encoded video, when you're home, could you connect to your phone with the  i5-7300U with H265, then record the connection with rustdesk, and send the mp4 to my email?

![1716270908013](https://github.com/rustdesk/rustdesk/assets/14891774/39b9e927-c69b-479b-834b-c41460174ee5)

**Comment by mikekgr** [comment] 2024-05-21 13:28
> I want to analyze the encoded video, when you're home, could you connect to your phone with the i5-7300U with H265, then record the connection with rustdesk, and send the mp4 to my email?

There is something wrong ! See the screenshot

![rustdesk-3](https://github.com/rustdesk/rustdesk/assets/15084551/7cddede2-55d4-4cac-bd18-2bfa59f1e0a6)

**Comment by mikekgr** [comment] 2024-05-21 13:39
@21pages 
I sent the video.

**Comment by 21pages** [comment] 2024-05-21 13:42
Thanks

**Comment by mikekgr** [comment] 2024-05-22 06:52
@21pages 
Hello Sir. Did you solve the problem? Do you need any further help with debugging?

**Comment by 21pages** [comment] 2024-05-22 06:55
Thank you for your help, no further help is needed and I will let you know when the issue is resolved.

**Comment by 21pages** [comment] 2024-05-22 12:22
Try https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-aarch64-align64.apk or next nightly

The i7-3770 should be able to connect to the H265, the i5-7300U's image should not have a green bottom.

**Comment by rustdesk** [comment] 2024-05-22 12:42
Nightly build is ready now

**Comment by mikekgr** [comment] 2024-05-22 13:43
Dear @21pages  @rustdesk 
I happily confirm that the reported problem is solved using the latest (today) nightly.

Thanks for your fabulous work !

**Closed** 2024-05-22 13:47 UTC
Labels: bug
