### ISSUE TITLE
Characters displayed in Simplified Chinese are Japanese characters.

### ISSUE THREAD

**Issue by kidzgy** [rustdesk/rustdesk#7444] opened 2024-03-20 15:25 UTC
### Bug Description

Under Simplified Chinese, the interface texts are all in Japanese, not in simplified Chinese.

### How to Reproduce

Set the language to Simplified Chinese

### Expected Behavior

Displays simplified Chinese character forms from the mainland.

### Operating system(s) on local side and remote side

Windows10  Windows10 

### RustDesk Version(s) on local side and remote side

1.2.3-1

### Screenshots

![20240320231746](https://github.com/rustdesk/rustdesk/assets/6967810/01856f8a-9720-4aa2-82ea-dfff6894f712)

**Comment by 21pages** [comment] 2024-03-21 02:12
Can't reproduce on my computer

![1710987134185](https://github.com/rustdesk/rustdesk/assets/14891774/a3d64ed3-80d6-437c-8ade-924b8aea4d2b)

**Comment by 21pages** [comment] 2024-03-21 02:15
Thanks, reproduced

**Comment by kidzgy** [comment] 2024-03-21 02:50
The three characters I mentioned are the more obvious ones where you can see the differences in the glyphs, in fact the other glyphs also have differences in strokes if you look closely.

**Comment by rustdesk** [comment] 2024-03-21 02:57
@21pages report to Flutter. It seems Windows specific, no issue on Android.

**Comment by 21pages** [comment] 2024-03-21 03:13
https://github.com/flutter/flutter/issues/145512

**Comment by 21pages** [comment] 2024-03-22 00:12
Flutter won't fix it, we have set `supportedLocales` as recommended.
It's ok if the Windows display language is the same as RustDesk.

![1711066341150](https://github.com/rustdesk/rustdesk/assets/14891774/e8d9398b-181c-4e54-ace3-33889e83988e)

**Comment by kidzgy** [comment] 2024-03-22 02:11
> Flutter won't fix it, we have set `supportedLocales` as recommended. It's ok if the Windows display language is the same as RustDesk.
> 
> ![1711066341150](https://private-user-images.githubusercontent.com/14891774/315840094-e8d9398b-181c-4e54-ace3-33889e83988e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzM3MzQsIm5iZiI6MTcxMTA3MzQzNCwicGF0aCI6Ii8xNDg5MTc3NC8zMTU4NDAwOTQtZThkOTM5OGItMTgxYy00ZTU0LWFjZTMtMzM4ODllODM5ODhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDAyMTAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNmUxMThiODFiMDA0YmJhNDlmYTUyMzk0OWU5YTYwYjQzMWYyZDJkOWNjNDE1YWVlNTEwOTQzNzQ4YTI1MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WTDDLywHdcI-PMitX4dlgdFsuXF9Z4t4tc-LKcPjuV0)

Yeah, that's how it's supposed to work.

**Closed** 2024-03-22 03:01 UTC
Labels: bug
