### ISSUE TITLE
Rustdesk unable to keep up with stream

### ISSUE THREAD

**Issue by alexandru-bagu** [rustdesk/rustdesk#8136] opened 2024-05-24 06:57 UTC
### Bug Description

It seems that when there is a lot of traffic the Rustdesk client will keep on storing frames in RAM but not render them fast enough to drop them from the RAM which leads the system to become sluggish and at some point it will hang the whole system.
I've tested streaming with 100% image quality and 60 fps and after a few seconds Rustdesk starts hogging the RAM and using a lot of CPU.

### How to Reproduce

Open youtube, with a video that has a rate of decent movement. Set image quality to 100% and 60 fps. Then check ram and cpu usage for Rustdesk.
In the video I uploaded you can see that after a few seconds the whole video slows down except my cursor as I desperately try to switch chrome tabs to stop Rustdesk from eating my system's RAM.
The codec used is H265 but the issue is not restricted to H265.

### Expected Behavior

I would expect that in the worst case when Rustdesk cannot keep up it will start dropping frames not hog the RAM and make the whole system unresponsive.

### Operating system(s) on local side and remote side

macOS -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.4 -> 1.2.4

### Screenshots

[video](https://drive.google.com/file/d/1Drs09cOEjbgmaRwmC5H0nsCdHv1aDc1E/view?usp=sharing)
![image](https://github.com/rustdesk/rustdesk/assets/5436943/289ff619-ab7d-4fa4-9d6c-f0e716c4926e)
![image](https://github.com/rustdesk/rustdesk/assets/5436943/e990b78b-4377-4b49-ae0f-cca61dfe1046)

### Additional Context

I understand that Rustdesk is not meant to be used to stream video however it causing the system to freeze is not acceptable.
It also seems that Rustdesk is using more CPU that I would expect even when it is using the GPU to decode the stream.
I also understand that the client system needs to be "beefy" enough to process the traffic from the remote side but at the moment there are no restrictions which allows users to trigger a system freeze.

The remote side in my case is streaming 1440p. At the same time, this computer is able to process 4k/60fps without many frames dropped on youtube with vp09 and generally video playback is fluid.

**Comment by rustdesk** [comment] 2024-05-24 07:04
Mac has not used GPU decode yet.

**Comment by rustdesk** [comment] 2024-05-24 07:13
Neverthless, @21pages let us fix memory accumulation issue because of software decode slow

**Comment by rustdesk** [comment] 2024-05-24 07:46
@alexandru-bagu we decrease the fps automatically when seeing the frame accumulation, then memory usage will drop. Can not you see?

**Comment by alexandru-bagu** [comment] 2024-05-24 07:48
> Mac has not used GPU decode yet, pure software (We do windows/linux/android hardware codec first, later we will do mac). vpx software decode is faster.

Interesting. Any idea when that is going to be implemented? Is ffmpeg being used to accelerate development? It seems that `avcodec_find_decoder_by_name("h264_vda")` is an option for hw accelerated decoding in ffmpeg for macOS.




> @alexandru-bagu we decrease the fps automatically when seeing the frame accumulation, then memory usage will drop. Can not you see?

My tests did not show that though, the fps did not really decrease for me and if I had not changed tabs in chrome my system would have become frozen due to no ram being available. If the fps did indeed decrease it didn't have the desired effect.

**Comment by rustdesk** [comment] 2024-05-24 07:49
> an option

Yes, for you, it is just an option, but not for me. :(

**Comment by rustdesk** [comment] 2024-05-24 07:52
It keeps 6G, will not drop any more?

**Comment by alexandru-bagu** [comment] 2024-05-24 07:54
If I don't manually intervene the system will run out of memory. It has happened at least once, I don't really feel like rebooting my system again.
Even so, even if it would hang around 6 GB, my system would be unusable and that is not a good option either.

**Comment by rustdesk** [comment] 2024-05-24 07:59
Could you test vp9/vp8 codec of RustDesk?

**Comment by alexandru-bagu** [comment] 2024-05-24 08:01
Just tested vp9. RustDesk did not stop eating ram. It got to the point where the whole system was responding very slow. Had to kill rustdesk

**Comment by 21pages** [comment] 2024-05-24 08:07
Could you check whether the memory usage of RustDesk is growing rapidly or gradually, and what is the rate of growth? Please kill RustDesk first before testing.

**Comment by alexandru-bagu** [comment] 2024-05-24 08:14
Here is an updated video with VP9.

https://drive.google.com/file/d/10k9AejIQGbuOtjyKj3Rr8zEIQ_G6yufZ/view?usp=sharing

I also managed to catch a bug where the video does not render at all unless I go in fullscreen. Oddly enough, the ram kept going up.

**Comment by alexandru-bagu** [comment] 2024-05-24 08:16
The bug regarding video not rendering happens every once in a while when the application is not fullscreen. It doesn't really bother me as I pretty much always have it full screen but it is annoying if you are not aware of it.

**Comment by 21pages** [comment] 2024-05-24 08:19
Thanks, both not rendering and memory usage are abnormal, and fps control can be improved, we'll try to reproduce and fix them.

**Comment by alexandru-bagu** [comment] 2024-05-24 08:20
Here is an another video where you can see how the rendering is "restored" once I go fullscreen and window mode.

https://drive.google.com/file/d/1w_BYNGSWT-NVc1mYGI2L6lRfQfsdJDJf/view?usp=sharing

**Comment by 21pages** [comment] 2024-05-24 08:36
The abnormal memory usage can be reproduced on mac m1.

**Comment by rustdesk** [comment] 2024-05-24 11:02
The new nightly build is ready now.

**Comment by alexandru-bagu** [comment] 2024-05-24 11:15
Just tested. The issue is not resolved.

**Comment by 21pages** [comment] 2024-05-24 12:06
Does the nightly fix the delay?

https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64-x86_64-texture-render.dmg
This program includes pr 8137 and use rgba texture render, should fix all the issue, could you try it ?

**Comment by alexandru-bagu** [comment] 2024-05-24 12:11
Cannot start this version.

`Process:               RustDesk [96571]
Path:                  /Users/USER/Downloads/RustDesk.app/Contents/MacOS/RustDesk
Identifier:            com.carriez.rustdesk
Version:               1.2.4 (39)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RustDesk [96571]
User ID:               502

Date/Time:             2024-05-24 15:10:36.549 +0300
OS Version:            Mac OS X 10.15.7 (19H2026)
Report Version:        12
Anonymous UUID:        8D515FF7-14E7-101C-F8D9-434C655A7A89

Sleep/Wake UUID:       70BFD24A-7EB4-4F50-AE6E-047A59931B78

Time Awake Since Boot: 340000 seconds
Time Since Wake:       74000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x5] Code Signature

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/FlutterMacOS.framework/Versions/A/FlutterMacOS
  Referenced from: /Users/USER/Downloads/RustDesk.app/Contents/MacOS/RustDesk
  Reason: no suitable image found.  Did find:
	/Users/a.bagu/Downloads/RustDesk.app/Contents/MacOS/../Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS: code signature in (/Users/a.bagu/Downloads/RustDesk.app/Contents/MacOS/../Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS) not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)

Binary Images:
       0x109054000 -        0x10905bfff +com.carriez.rustdesk (1.2.4 - 39) <8E853059-DF60-3EE4-B425-61238A5E42B8> /Users/USER/Downloads/RustDesk.app/Contents/MacOS/RustDesk
       0x10e668000 -        0x10e6fa267  dyld (750.7) <9F48F7F8-94D0-3793-99B7-DDEF657EF956> /usr/lib/dyld
    0x7fff29073000 -     0x7fff2926eff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff2aa87000 -     0x7fff2b845ffb  com.apple.AppKit (6.9 - 1894.70.110) <058D0F31-D353-36D9-83CD-1709EBB1390E> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff644bc000 -     0x7fff644bdfff  libSystem.B.dylib (1281.100.1) <5A20AE6C-BF4D-3689-B7D2-19F0721F6375> /usr/lib/libSystem.B.dylib
    0x7fff6631e000 -     0x7fff66351fde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff66ee9000 -     0x7fff66ef2fff  libswiftCoreMIDI.dylib (??? - ???) <81408BBB-9648-37CB-8646-707C7CDCE15C> /usr/lib/swift/libswiftCoreMIDI.dylib
    0x7fff67185000 -     0x7fff6718af47  libswiftOSLog.dylib (??? - ???) <5DCDF2D6-91E8-36D1-AB51-B6B0B592D543> /usr/lib/swift/libswiftOSLog.dylib

Model: iMac18,3, BootROM 451.140.1.0.0, 4 processors, Quad-Core Intel Core i5, 3,4 GHz, 8 GB, SMC 2.41f2
Graphics: kHW_AMDRadeonPro570Item, Radeon Pro 570, spdisplays_pcie_device, 4 GB
Memory Module: BANK 0/DIMM0, 4 GB, DDR4 SO-DIMM, 2400 MHz, 0x802C, 0x344154463531323634485A2D3247334532202020
Memory Module: BANK 1/DIMM0, 4 GB, DDR4 SO-DIMM, 2400 MHz, 0x802C, 0x344154463531323634485A2D3247334532202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x16F), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.7)
Bluetooth: Version 7.0.6f8, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: APPLE HDD ST1000DM003, 1 TB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
USB Device: FaceTime HD Camera (Built-in)
USB Device: Lenovo USB Optical Mouse
USB Device: Lenovo Traditional USB Keyboard
Thunderbolt Bus: iMac, Apple Inc., 41.4
`

**Comment by 21pages** [comment] 2024-05-24 12:14
Then 1.2.3-2 should not have the memory issue, because it uses the rgba texture render.

**Comment by alexandru-bagu** [comment] 2024-05-24 12:20
1.2.3-2 doesn't have H264 either. I can test with VP9 though.

**Comment by 21pages** [comment] 2024-05-24 12:22
You can test once #8136 is merged

**Comment by 21pages** [comment] 2024-05-24 12:34
Only the reaction delay is needed to be tested for nightly

**Comment by rustdesk** [comment] 2024-05-27 10:30
Please help test the nightly build

**Comment by alexandru-bagu** [comment] 2024-05-27 14:24
The ram issue is resolved.

Any idea when hardware decoding will be available on mac?

**Closed** 2024-05-27 15:01 UTC
Labels: bug
