### ISSUE TITLE
Rustdesk on android crashes frequently when trying to remote desktop my laptop

### ISSUE THREAD

**Issue by Growebis** [rustdesk/rustdesk#3314] opened 2023-02-21 13:42 UTC
### Bug Description

Currently, when I'm trying to remote desktop my laptop (On Android), it works completely fine. but after some time using the laptop remotely, the app crashes and every other process that was running in the background completely closes. I looked at the running services and the ram usage was fairly high ~250mb ram usage (idk if it's normal), and while using the app, sometimes it would spike even higher, ~500mb ram usage and it was random, sometimes it went back to ~250mb or goes even higher to the point of crashing. My only theory is thst some sort of memory leakage is happening.

### How to Reproduce

1. Open the Rustdesk app
2. Connect to the laptop remotely
3. Use it for some time (like a couple minutes) 
4. It crashes and all other processes running crash with it due to high ram usage.

### Expected Behavior

Should not crash at all while remote desktoping and be smooth

### Operating system(s) on local side and remote side

Android -> Windows 10

### RustDesk Version(s) on local side and remote side

nightly -> 1.19

### Screenshots

Do note that the crashing timing is inconsistent, sometimes less then a minute, other times after couple of minutes. (when the recording stops, that means it crashed) 
https://user-images.githubusercontent.com/113867283/220359203-d97f806b-15dd-4b77-b0c9-48df9b927af0.mp4

### Additional Context

I have currently tried the stable and more recently, the nightly version, both give the same result. I had the stable rustdesk on Fdroid

My phone is a Sony Xperia L1 with 2 gb of ram and running Android 7.

In currently using the public server but will soon try hosting my own server.

**Comment by rustdesk** [comment] 2023-02-21 13:49
@Heap-Hop

**Comment by Growebis** [comment] 2023-03-02 01:08
I'm just wondering what is the status of the issue?

**Comment by Heap-Hop** [comment] 2023-03-02 02:35
I tried to reproduce, but didn't have the same problem. 

> ~250mb ~500mb

Looks like normal memory usage, cause we need cache raw video frames.
There doesn't seem to be a serious memory leak.

We need more time to try to reproduce, and expect more related reports from others.

**Comment by rustdesk** [comment] 2023-03-09 12:31
Sorry, we can not fix for this low memory android.

**Closed by rustdesk** 2023-03-09 12:31 UTC

**Comment by Growebis** [comment] 2023-03-12 04:16
I recently tried using nightly on both devices but this time wth Linux and it seems to work fine, still the memory usage is large but manageable

**Comment by rustdesk** [comment] 2023-03-12 04:17
Thanks, good to know.

**Comment by Growebis** [comment] 2023-04-10 16:47
I think I know why it crashes, while controlling the laptop and doing statics things e.g browsing my files or maybe using a web browser, doesn't crash rustdesk. The second I start doing a lot of things at once (the bar for this is so low, like going into a website crashes the app), or the second gifs or videos start playing is the second the app becomes very slow then crashes

**Comment by rustdesk** [comment] 2023-04-10 23:56
try out nightly build.

**Comment by Growebis** [comment] 2023-04-11 02:11
I'm already using nightly build
