### ISSUE TITLE
clicking buttons below with a mouse will simultaneously act a click on remote device

### ISSUE THREAD

**Issue by Cybercll** [rustdesk/rustdesk#6002] opened 2023-10-12 11:54 UTC
### Bug Description

using a mouse to click keyboard button will simultaneously act a click on remote device. This is not what I expected.

### How to Reproduce

1. Android device connected to a mouse
2. connect to a windows remote device
3. click buttons below such as keyboard
4. somewhere below was clicked on remote device

### Expected Behavior

while clicking buttons, we do not expect to click on remote device.

### Operating system(s) on local side and remote side

Android 13 to Windows10

### RustDesk Version(s) on local side and remote side

1.2.3 nightly to 1.2.3

### Screenshots

we can see the remote device focused on Spotify
![Screenshot_2023-10-12-19-46-14-579_com carriez flutter_hbb](https://github.com/rustdesk/rustdesk/assets/25275727/09748175-92e5-4cb5-bbae-9947f8c08379)

using a mouse to click on chat button and something was opened out of expection
![Screenshot_2023-10-12-19-46-17-772_com carriez flutter_hbb](https://github.com/rustdesk/rustdesk/assets/25275727/3d18155a-9945-49e7-a3c2-69fcabf4b861)
search was opened
![Screenshot_2023-10-12-19-46-38-028_com carriez flutter_hbb](https://github.com/rustdesk/rustdesk/assets/25275727/03f19f65-3f79-46f2-81a5-07ea6bde6d84)

**Comment by fufesou** [comment] 2023-10-20 12:58
I tried the Android emulator.
In the simulator, mouse click events will be blocked by the chat window.
I can't bring up the soft keyboard, so I can't reproduce this issue.

> 1. Android device connected to a mouse

I'll try a "OTG adapter cable" to connect a physical mouse later.

**Comment by fufesou** [comment] 2023-10-22 04:05
Thanks for your feedback. I've reproduced this issue.

I'll fix it later.

**Comment by fufesou** [comment] 2023-10-22 12:41
This issue should be fixed by #6133 .

But I'm not sure if it is a problem that the area behind the bottom navigation bar can not be clicked.

![Untitled](https://github.com/rustdesk/rustdesk/assets/13586388/087cfddf-1126-4b74-b822-9bfb3cd21425)

It is ok for me though, I can use two finger to scale and then pan the image.

**Comment by rustdesk** [comment] 2023-10-22 14:52
close as fix merged.

**Closed** 2023-10-22 14:52 UTC
Labels: bug

**Comment by Cybercll** [comment] 2023-10-22 17:52
> This issue should be fixed by #6133 .
> 
> But I'm not sure if it is a problem that the area behind the bottom navigation bar can not be clicked.
> 
> ![Untitled](https://user-images.githubusercontent.com/13586388/277165039-087cfddf-1126-4b74-b822-9bfb3cd21425.png)
> 
> It is ok for me though, I can use two finger to scale and then pan the image.

I think its fine
