### ISSUE TITLE
Can listen to microphone of controlled client without audio chat

### ISSUE THREAD

**Issue by JohnnyHenver** [rustdesk/rustdesk#8718] opened 2024-07-15 10:43 UTC
### Bug Description

Upon establishing a connection with the controlled client we can listen to their microphone without starting an audio chat. The remote computer audio (applications) are not audible. When starting an audio chat there is a short break and then they are audible in the audio chat louder than before. Upon ending the audio chat, there is a short break and then we can hear them again a bit quieter. The audio of remote applications is not audible unless remote party manually changes audio input device to "System sounds".

Playback of audio input is not enabled for the microphone on the controlled client.

### How to Reproduce

We use a self-hosted rustdesk server pro 1.3.11 for our tests (docker).
There is no specific behaviour to cause this. It happens whenever we open a remote session. 
Default strategy is disabled. No other strategy is enabled for affected systems.

### Expected Behavior

I expect to hear the sound of remote applications.
The microphone input of the controlled client should not be audible unless starting an audio chat.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10, macOS 14.5 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.6 -> 1.2.6

### Screenshots

configuration of controlled client:
![image](https://github.com/user-attachments/assets/5b1cb0e1-63d3-4b93-9b88-3e054914bb7e)

configuration of controlling client:
macOS
![image](https://github.com/user-attachments/assets/264f80e7-d0c2-4000-a7bc-5eecc30ec84d)
windows
![image](https://github.com/user-attachments/assets/0cb0609b-2f67-410d-b02c-822829e9ede0)

### Additional Context

**This is obviously a major trust issue.** 
It seems to me like rustdesk defaults to the automatically configured audio input device for audio chat feature as source to transmit audio to the controlling client. If true these settings should be totally seperated as they have nothing to do with one another.

As a side note: Audio device choices for audio chat should be able to differenciate between input and output. Currently one can only choose an input device.

**Comment by rustdesk** [comment] 2024-07-15 10:49
By default, the option is not "System sounds"?

Could you check also our release? Need to confirm it is related to custom client.

**Comment by rustdesk** [comment] 2024-07-15 11:49
> As a side note: Audio device choices for audio chat should be able to differenciate between input and output. Currently one can only choose an input device.

Take note of this, while you do asio, add this.

**Comment by rustdesk** [comment] 2024-07-15 11:50
> As a side note: Audio device choices for audio chat should be able to differenciate between input and output. Currently one can only choose an input device.

Take note of this, while you do asio, add this. @fufesou

**Comment by rustdesk** [comment] 2024-07-15 12:19
Can it be reproduced on all your controlled Windows machine?

**Comment by fufesou** [comment] 2024-07-15 12:49
@JohnnyHenver Hi, can you  please run the simple test here https://github.com/fufesou/rust_simple_test/releases 

It prints the default audio output device.

https://github.com/fufesou/rust_simple_test/blob/main/src/main.rs

**Comment by JohnnyHenver** [comment] 2024-07-15 14:00
@rustdesk
I have replicated our tests with another device and cross-tested with the public client. The issue was reproducable in all scenarios, but there is a slight change:
It seems the issue is usually only showing, **after** audio chat has been used once with a microphone configured as input device. When the client is closed and started again, it is still pointing to the input device, which has been set during the earlier call (without the user knowing or being able to influence this). As such signal from the microphone is transmitted as "computer audio" outside of the audio chat. To fix, one has to enter a call and set audio input to  System sound manually. On the computer, where the issue happened before an audio chat, "System sound" was not available as input device during audio chat, so this might have been an edge case. I dont have access to that PC at the moment. 
@fufesou On my current clients your program correctly prints the name of the respective default output device (i.e. "Lautsprecher High-Definition Audio").

**The reproduction looks as follows:**

1. Start rustdesk client on controlled client
2. Establish connection with controlled client -> Computer audio is audible ✅ 
3. Start audio chat with the controlled client
  -> this sets audio input to microphone
4. Stop the audio chat and close client on controlled client
5. Start controlled client again
6. Establish connection with controlled client -> Microphone audio is audible ⚠️ 
7. Client has to enter audio chat and change audio input to "System Sound" to fix

If for some reason "System Sound" is not available, the issue appears right away.

![iScreen Shoter - tt-rustdesk - 240715133604](https://github.com/user-attachments/assets/795caecf-d210-4ecf-891e-998a1559c789)

To my understanding:
- Rustdesk should never choose any input device as audio capture for audio redirection. At least I can not think of a use case that validates this since a dedicated voice chat is integrated into the app.
- Audio input setting should be totally independent from audio capture for redirection (i assume this is fixed in #8703 @rustdesk ?).

**Comment by rustdesk** [comment] 2024-07-15 14:03
> It seems the issue is usually only showing, **after** audio chat has been used once with a microphone configured as input device. When the client is closed and started again, it is still pointing to the input device,

Thanks for your figuring out this. I believe https://github.com/rustdesk/rustdesk/pull/8703 fixed this. Could you help test the newest nightly build?

**Comment by rustdesk** [comment] 2024-07-18 03:32
close since fix merged

**Closed by rustdesk** 2024-07-18 03:32 UTC
Labels: bug
