### ISSUE TITLE
Freeze when closing main window and go to fullscreen [Linux 6.9.4-arch1-1 (Wayland) > Windows 10]

### ISSUE THREAD

**Issue by NicKoehler** [rustdesk/rustdesk#8363] opened 2024-06-15 07:35 UTC
### Bug Description

Rustdesk freezes if I'm connected to a remote host, I close the main window and toggle fullscreen on remote host.

### How to Reproduce

1. Connect to remote host
2. Close rustdesk main window
3. Put remote host on fullscreen
4. Rustdesk remains freezed

### Expected Behavior

Not to freeze.

### Operating system(s) on local side and remote side

Linux 6.9.4-arch1-1 (Wayland) > Windows 10

### RustDesk Version(s) on local side and remote side

Nightly

### Screenshots

How to trigger the bug:

[Video del 2024-06-15 09-00-10.webm](https://github.com/rustdesk/rustdesk/assets/53040044/c1cf3832-f539-4859-85ce-cd97e9bb4ab7)

**Comment by rustdesk** [comment] 2024-06-15 07:37
@fufesou

**Comment by fufesou** [comment] 2024-06-15 09:39
@NicKoehler Hi, is this issue reproduced every time you did the steps? I cannot reproduce it, or maybe it will be reproduced randomly.

Can you please run rustdesk in command line? It seems the client is crashed.

**Comment by NicKoehler** [comment] 2024-06-15 09:55
I can reproduce it every single time, is not crashing until I kill it

**Comment by rustdesk** [comment] 2024-06-15 11:58
> Can you please run rustdesk in command line?

There may be some output which we can track. Please run from command line, and paste the output.

**Comment by NicKoehler** [comment] 2024-06-15 12:56
Logs if I kill it:

`RUST_BACKTRACE=full rustdesk &>` [rustdesk.log](https://github.com/user-attachments/files/15847668/rustdesk.log)


I'll try to wait and see if actually crashes without my interaction.

**Comment by fufesou** [comment] 2024-06-15 13:14
> RUST_BACKTRACE=full rustdesk &> [rustdesk.log](https://github.com/user-attachments/files/15847668/rustdesk.log)

No helpful information is found.


I reinstalled archlinux by `archinstall` in virtualbox.

My gnome is still quit different from yours. And I still cannot reproduce this issue.

https://github.com/rustdesk/rustdesk/assets/13586388/4e5f1e9f-e969-48da-a20d-5cd737ad98bf

**Comment by NicKoehler** [comment] 2024-06-15 13:17
Maybe is hardware related? I can make you debug on my machine directly if you want.

**Comment by fufesou** [comment] 2024-06-15 13:21
@NicKoehler Thanks. Do you have the dev env or can I install the devenv, rust and flutter on your machine?

You can send me an email `bGlubG9uZzEyNjZAZ21haWwuY29t`  (base64)

**Comment by NicKoehler** [comment] 2024-06-15 13:22
I have sort of a dev env, but you can install whatever is needed.

**Comment by fufesou** [comment] 2024-06-17 00:34
Latest report, thanks for @NicKoehler 's kind help

This issue appears after closing main window and resizing the remote window.

1. After downgrading the nvidial driver, this issue dissapear.
2. There's no crash. The window may be frozen because the UI is in deadlock.

**Comment by NicKoehler** [comment] 2024-06-17 08:37
I'll update this when I'll install the new nvidia drivers once they are stable as I was using beta drivers.

**Comment by rustdesk** [comment] 2024-06-27 11:37
Close since related to nvidia driver.

**Closed by rustdesk** 2024-06-27 11:37 UTC
Labels: bug
