### ISSUE TITLE
Cannot exit Rustdesk gracefully

### ISSUE THREAD

**Issue by Creling** [rustdesk/rustdesk#912] opened 2022-07-04 03:17 UTC
The Taskbar icon of rustdesk is devoid of an Exit button. So, other than killing it via Task Manager, how to exit Rustdesk gracefully?

![图片](https://user-images.githubusercontent.com/43109504/177075518-6fa61815-4b91-4698-a587-6a8fb83c4be4.png)

**Comment by rustdesk** [comment] 2022-07-07 15:54
Need to check out tray icon show/hide behavior in the other vendors .

**Comment by betaxab** [comment] 2022-07-16 05:56
@rustdesk I would prefer to have an exit button added to the tray icon, so that it can directly close all processes, not to keep background tasks.

**Comment by shrinktofit** [comment] 2022-08-18 17:16
> 

Bump.

**Comment by CrysK** [comment] 2022-08-25 12:55
There is still no way to exit RustDesk gracefully. You have to kill the process in the task manager.

Also, it is a pity that RustDesk is automatically linked into the Windows Startup. Without asking, without being able to deselect this ... Again, you can only delete it manually, if you know where.

**Comment by HaamsterJoe** [comment] 2023-01-15 10:37
The issue is still active and confusing both me and my parents that I wanted to help. Also it raises some security concerns, like why the remote control service is always launched and can not be exited properly?

**Comment by test2a** [comment] 2023-01-16 08:02
In defence of rustdesk devs, I for one, who USES rustdesk for like 12 hours a day 7 days a week on 4-9 machines simultaneously this is OOTB good for me. I know I can install once, get the userid, accept and I am off to the races. 

This persists after restarts so I am able to remotely restart the machine and get it back online in a matter of minutes. 

Now, I would say there *should* be more config options with regards to if it should autostart on boot or if service should be enabled on ALL times or only during software is actively open but yeah. 


There should be proper messaging about this silent behavior. I udnerstand the devs, they want to replicate tw/ad where this also happens (I think anydesk calls it unattended access) and they have replicated that feature but I understand this should NOT be the default. 

So a couple of things. 

1. For now, we can have proper information about what is happening 

2. Next step would be to provide these configs and keep them OFF by default.

**Comment by FurtadoPires** [comment] 2023-01-16 15:09
Also I would like to point that closing / finishing the application should also finish all the process running in background. Keeping  processes running in background without the possibility of being closed by the user it's usually malicious software behavior.

![image](https://user-images.githubusercontent.com/7890832/212709722-93fdae7e-ccdb-447f-809b-8491882b6283.png)

**Comment by AnonymousWP** [comment] 2023-03-07 07:53
> Also I would like to point that closing / finishing the application should also finish all the process running in background. Keeping processes running in background without the possibility of being closed by the user it's usually malicious software behavior.
> 
> ![image](https://user-images.githubusercontent.com/7890832/212709722-93fdae7e-ccdb-447f-809b-8491882b6283.png)

Bump.

This is the only reason why I've not started to use RustDesk yet. I'm using AnyDesk now. Should be fairly simple to add an 'exit' button. Regarding the image above: it sometimes does close all processes, but then you need to end the right task of the 3.

**Comment by weirdal3333** [comment] 2023-04-12 15:47
A sort of opposite issue happens on the Linux side. Closing the rustdesk window kills all the processes!
More options regarding the background behavior are needed. Some people want it running in the background, and some don't. Take a look at how TeamViewer handles it, as that's how it should be done!

**Comment by CRC-Mismatch** [comment] 2023-04-15 14:00
@weirdal3333 I'm having the opposite happening to me now, on Kubuntu 22.04, on a laptop with Nvidia "Reverse Prime" setup in X11 and proprietary drivers. 
Sometimes one of the external screens gets "lost" when the system puts it into power-saving mode, and when this happens, after I unlock my Plasma session, if I had left Rustdesk's main window open (no matter where it was, what size it had or if it was still connected or not) it gets turned into a 1-pixel-wide "window", and Rustdesk's still-running processes hog up an entire CPU core each. If I then close the "window" (more like pixel-wide-windowframe) via Plasma Panel's "taskbar" (more correctly 'Task Manager with Icons'), instead of killing all processes, some are still left running hogging up cores, but I have no more Rustdesk window, tray icon or taskbar icon.

Here's a print of `htop` in this state. I only noticed Rustdesk was still running after half-a-day because when I came back to the laptop, it's fans are loudly and angrily spinning, as if it was running something rather intensive.

![image](https://user-images.githubusercontent.com/7253323/232228797-cf9da7f8-ca7e-433c-8b12-76f77876a92c.png)

**Comment by azsde** [comment] 2023-05-20 08:08
It is quite odd not being able to quit RustDesk gracefully indeed.

**Comment by win100000** [comment] 2023-05-20 15:32
Now also not convenient exit the program, is not very convenient, hope to improve

**Comment by rustdesk** [comment] 2023-06-07 06:27
close as fix merged

**Closed** 2023-06-07 06:28 UTC
Labels: enhancement, good first issue

**Comment by AnonymousWP** [comment] 2023-06-07 06:57
> close as fix merged

How will we be able to use this feature (including all recent commits) if the latest release dates from October (nightly) and May (stable) from last year? 😅

**Comment by rustdesk** [comment] 2023-06-07 07:23
![image](https://github.com/rustdesk/rustdesk/assets/71636191/d7b064c5-d787-4510-af4b-dc1104566b0d)

**Comment by AnonymousWP** [comment] 2023-06-07 08:24
> ![image](https://user-images.githubusercontent.com/71636191/243958499-50db99f1-4964-4850-9125-c7327b3d3800.png)

Ah I see, thanks a lot! These nightlies look and feel so much better.

**Comment by Otiel** [comment] 2023-06-07 16:44
@rustdesk Do you plan to release a new stable version soon?

**Comment by azsde** [comment] 2023-06-08 08:40
@Otiel just use the nightly

**Comment by FloBro94** [comment] 2024-02-07 09:00
When i quit rustdesk, the service is stopped 
I must start the service with admin right :(
