### ISSUE TITLE
Issue with connecting to Wayland GNOME (EndeavourOS Wayland)

### ISSUE THREAD

**Issue by poperigby** [rustdesk/rustdesk#2001] opened 2022-11-08 01:29 UTC
**Describe the bug you encountered:**

When I try to connect from a Mac to a Linux machine using GNOME (also tried connect from another Linux machine), a dialogue box asking me "Select monitor to share with the requesting application" pops up. I click on that, and I'm able to connect from my Mac, but it looks like this on the Mac side:
![image](https://user-images.githubusercontent.com/20866468/200449388-84b8029f-9799-46d4-9904-ce42f5a2a1de.png)

Then, it keeps asking me to select a monitor over and over again, even after I press the "Share" button. 

**What did you expect to happen instead?**
The Linux machine only asks me to select a monitor once, and there aren't any graphical glitches.

**How did you install `RustDesk`?**

The [`rustdesk-nightly`](https://aur.archlinux.org/packages/rustdesk-nightly) package from the AUR.

**RustDesk version and environment**

Puppet side info:
* OS: EndeavourOS
* DE: GNOME 43.1

**Comment by rustdesk** [comment] 2022-11-08 01:37
@fufesou

**Comment by fufesou** [comment] 2022-11-08 01:58
It seems that rustdesk keeps crashing. I'll test the latest version on my env.

**Comment by xxrlzzz** [comment] 2022-11-13 05:57
ubuntu 18/GNOME 3.28.2 works fine

**Comment by fufesou** [comment] 2022-11-13 06:02
> ubuntu 18/GNOME 3.28.2 works fine

@xxrlzzz Try Ubuntu 21 or upper. The crash seems appear on Wayland which works only on Ubuntu 21 or upper.

**Comment by fufesou** [comment] 2022-11-13 13:59
@poperigby Hi, I've reproduce the problem of asking dialgue showing again and again. Though picture on self-side is clear.
@xxrlzzz and I will try to fix this problem.

**Comment by fufesou** [comment] 2022-11-21 05:25
https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/31

@poperigby Can you please paster the output of `cat /usr/share/gnome/gnome-version.xml`

**Comment by poperigby** [comment] 2022-11-21 20:29
Oh, there we go. I have an AMD GPU, but let's see if updating fixes it.

**Comment by fufesou** [comment] 2022-11-22 14:45
@poperigby Thanks for your kindy response and trying.
I'm trying to improve the wayland support. The sharing dialog problem will be fixed. But it will take me a few days.

BTW, the picture in your issue is another problem. It is caused by wrong encode/decode process. I'll try to reproduce and fix it after wayland support is finished.

**Comment by fufesou** [comment] 2022-11-25 11:49
@poperigby  Partial fixed. The dialog asking for confirmation should not keeps popping up now. But there are stile some todos.
https://github.com/rustdesk/rustdesk/issues/2001

**Comment by ma0shu** [comment] 2022-11-27 05:11
Nightly 20221127, the dialog asking for confirmation starts popping up after using for about an hour.
dmesg:`[12280.824009] kauditd_printk_skb: 51 callbacks suppressed
[12280.824021] audit: type=1101 audit(1669525152.166:43226): pid=381912 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='op=PAM:accounting grantors=pam_unix,pam_permit,pam_time acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=success'
[12280.825126] audit: type=1110 audit(1669525152.169:43227): pid=381912 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='op=PAM:setcred grantors=pam_env,pam_fprintd acct="malingshu" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=success'
[12280.830409] audit: type=1105 audit(1669525152.172:43228): pid=381912 uid=0 auid=4294967295 ses=4294967295 subj=unconfined msg='op=PAM:session_open grantors=pam_systemd_home,pam_limits,pam_unix,pam_permit acct="malingshu" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=success'
[12281.522942] rustdesk[381913]: segfault at 2 ip 00007f461916fffd sp 00007ffe76a86408 error 4 in libc.so.6[7f461903b000+15b000]
[12281.522978] Code: e1 c5 f8 77 c3 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 89 f8 48 89 fa c5 f9 ef c0 25 ff 0f 00 00 3d e0 0f 00 00 0f 87 33 01 00 00 <c5> fd 74 0f c5 fd d7 c1 85 c0 74 57 f3 0f bc c0 c5 f8 77 c3 66 66
`

**Comment by rustdesk** [comment] 2022-11-27 05:21
@ma0shu Thanks for your report, it is a crash. @fufesou

**Comment by fufesou** [comment] 2022-11-27 12:11
>starts popping up after using for about 45min.

@ma0shu Thanks for your detailed report.

I can see rustdesk restart and crash many times. But `xdg-desktop-portal` is also restarting and crashing. It seems like your desktop environment has been corrupted. 

 Please give more infos here
1. Which distro you are using
2. Gnome version. `/usr/share/gnome/gnome-version.xml`

**Comment by ma0shu** [comment] 2022-11-27 13:48
> 1. Which distro you are using
Distro: Manjaro Linux (Rolling)
Kernel: 6.0.8-1-MANJARO arch: x86_64
> 2. Gnome version. `/usr/share/gnome/gnome-version.xml`
> '/usr/share/gnome/gnome-version.xml': No such file or directory 
Desktop: GNOME v: 43.1 tk: GTK v: 3.24.34 wm: gnome-shell dm: GDM v: 43.0

**Comment by howudodat** [comment] 2023-01-23 20:36
I have the same weird green screen running stock ubuntu 22.04 kernel 5.15.0-58 and ubuntu 22.04 with kernel 6.1.7 both running gnome 42.5

**Comment by rustdesk** [comment] 2023-01-23 23:56
@fufesou

**Comment by rustdesk** [comment] 2023-03-09 00:42
close to favor #3565

**Closed by rustdesk** 2023-03-09 00:42 UTC
Labels: bug
