### ISSUE TITLE
RustDesk client freezes on KDE Plasma X11 when touching the top edge of the screen in fullscreen (arch -> arch)

### ISSUE THREAD

**Issue by polyzium** [rustdesk/rustdesk#6505] opened 2023-11-23 10:33 UTC
### Bug Description

The RustDesk desktop client seems to freeze for 2 seconds or more (depends on how long you touch it for) whenever the mouse touches the top edge of the screen in fullscreen mode.

### How to Reproduce

1. Open the RustDesk desktop client
2. Connect to any server
3. Go fullscreen
4. Move the mouse to the very top until it hits the edge

### Expected Behavior

No freeze should occur.

### Operating system(s) on local side and remote side

Arch Linux X11 -> Arch Linux X11

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

https://github.com/rustdesk/rustdesk/assets/22579935/32502d23-6d04-4a91-9867-a5663a2a7280

### Additional Context

Using H265 codec, two monitors, and a custom ID+relay servers.

**Comment by polyzium** [comment] 2023-11-23 10:34
Relevant issue, this also seems to happen on mobile by moving the "touchpad" cursor to the top of the remote screen the same way.

**Comment by rustdesk** [comment] 2023-11-23 10:35
@sahilyeole

**Comment by sahilyeole** [comment] 2023-11-23 11:43
I could not reproduce it on mac/android <-> arch endeavour os x11. 

https://github.com/rustdesk/rustdesk/assets/73148455/af74ab39-9fce-4f09-b7d7-24bc3b8e4029

---
@polyzium Can you please confirm if this freeze on stream occurs when you move the cursor on top on both remote and local? Or does it only occur only moving it on top on the remote side?

**Comment by polyzium** [comment] 2023-11-23 11:49
I don't have physical access to the local machine right now, all I can say it does occur when doing so from the remote side.

However I don't think it freezes the local system to death, because I tried RustDesk's built-in screen recorder and it seems to record fine without any freezes.

**Comment by rustdesk** [comment] 2023-11-23 12:02
May have to test from arch to arch fullscreen. @sahilyeole can you have another VM running arch?

**Comment by sahilyeole** [comment] 2023-11-23 12:05
Sure, testing.

**Comment by sahilyeole** [comment] 2023-11-23 12:49
No, I still could not reproduce it. Arch -> Arch.

https://github.com/rustdesk/rustdesk/assets/73148455/88782af5-eb20-40d7-8422-6b9cdbaa93f3

**Comment by polyzium** [comment] 2023-11-23 13:37
Maybe that's due to resolution mismatch?

**Comment by sahilyeole** [comment] 2023-11-23 14:12
>Try setting local and remote to the same resolution and try again

Checked. Still could not reproduce :(

**Comment by rustdesk** [comment] 2023-11-23 14:14
@sahilyeole Thanks for your efffort, Let's wait for more feedback from the other users.

**Comment by polyzium** [comment] 2023-11-23 14:16
Well this sucks. How did this happen then?

**Comment by polyzium** [comment] 2023-11-23 14:20
> @polyzium you can also try out our nightly build. https://github.com/rustdesk/rustdesk/releases/tag/nightly

Nightly build didn't improve the situation any. Perhaps the problem is on the remote computer side, let me try

**Comment by polyzium** [comment] 2023-11-23 14:24
Nightly on both local and remote side. The bug is still present.

**Comment by polyzium** [comment] 2023-11-23 19:47
OK so I had a go at this once more.

I tried this again with Fluxbox X11 and KDE Plasma Wayland. The session does not freeze, so this seems to be a weird occurrence with KDE Plasma X11.

**Comment by rustdesk** [comment] 2023-11-28 09:28
tracked by https://github.com/rustdesk/rustdesk/issues/4367

**Closed** 2023-11-28 09:29 UTC
Labels: bug, unreproducible
