### ISSUE TITLE
RENDEZVOUS_SERVER and RS_PUB_KEY do not get embedded in Windows build

### ISSUE THREAD

**Issue by kwisatz** [rustdesk/rustdesk#3328] opened 2023-02-22 08:24 UTC
### Bug Description

The [documentation](https://rustdesk.com/docs/en/dev/build/all/) describes how to build the application with a preset for both parameters on all platforms by forking the repository and using Github Actions.

This works well enough for e.g. the Linux build, but we discovered that it does not work for the Windows build. The presets are not present in that build when run as portable app or when installed.

#### Checking that it doesn't work for the Windows build

Follow the instructions on https://rustdesk.com/docs/en/dev/build/all/ to fork the repository, set repository secrets and run the nightly build.
Download the resulting windows binary from the generated release files.
Check under `Settings > Network` that all fields are still empty.

#### Checking that it does work for the Linux builds

Download and install the Linux build
Check under `Settings > Network` that the preset values are correctly pre-filled .

### Expected Behavior

When running the nightly job and setting both repository secrets, then the Windows build should have network settings prefilled.

### Operating system(s) on local side and remote side

Windows 10 -> NA

### RustDesk Version(s) on local side and remote side

1.2.0 -> NA

### Screenshots

_(Screenshots wouldn't help here.)_

**Comment by rustdesk** [comment] 2023-02-22 08:40
Try to fix it then, we actually do not use it.

**Comment by rustdesk** [comment] 2023-02-22 08:40
#763

**Comment by rustdesk** [comment] 2023-02-22 08:42
#3126

**Comment by kwisatz** [comment] 2023-02-22 09:00
@rustdesk while I understand your reasoning in #763, I would suggest that you add a link to that (or other limitations) to the top of your issue form. It will save you the trouble of having to react to tickets like this.

I will look into #3126 and see if I can spot why it works for that person but not us. I also think that this feature that you do not use is actually a good selling point for companies – potential sponsors – that would like to use rustdesk as a tool for their support requirements.

**Comment by xxjasonxx1996** [comment] 2023-02-24 09:43
When the `RS_PUB_KEY` is set as a repository secret on GitHub, it appears that it does not get bundled into the software. I was able to confirm this by comparing a fresh installation of Rustdesk with no changes to the settings (see `ERROR_NAT_NETWORK_WITH_KEY_SECRET_SET`), and a fresh installation with custom settings (see `OK_NAT_NETWORK_WITH_KEY_MANUALLY_SET`) using Wireshark.

The problem appears to be associated with packet 22 in both capture files, where the absence of the `RS_PUB_KEY` in the former capture file suggests that the key was not bundled into the software correctly. This issue was consistently reproducible on both virtual machines and standalone computers running on Windows 10.

Picture of `ERROR_NAT_NETWORK_WITH_KEY_SECRET_SET`
![PICTURE_ERROR_NAT_NETWORK_WITH_KEY_SECRET_SET](https://user-images.githubusercontent.com/8620239/221143039-36f1dafb-e432-46ae-910f-06c4815e587d.png)

Picture of `OK_NAT_NETWORK_WITH_KEY_MANUALLY_SET`
![PICTURE_OK_NAT_NETWORK_WITH_KEY_MANUALLY_SET](https://user-images.githubusercontent.com/8620239/221145934-33c5e067-aa7a-45b3-93d0-6d5d6a60de65.png)

**Comment by nextgen-networks** [comment] 2023-02-28 10:53
@kwisatz & @xxjasonxx1996 breaking changes seems to be introduced in February 2023 see also: https://github.com/rustdesk/rustdesk/issues/3417#issuecomment-1447948608

**Comment by rustdesk** [comment] 2023-03-01 01:16
https://github.com/rustdesk/rustdesk/issues/3126#issuecomment-1425049236

**Comment by rustdesk** [comment] 2023-03-01 01:17
@nextgen-networks  could you confirm if RENDEZVOUS_SERVER and RS_PUB_KEY still work on your repo?

**Comment by zyk014** [comment] 2023-03-08 08:57
Hello, the author. When compiling Windows, RENDEZVOUS was added_ SERVER and RS_ PUB_ KEY variable, compiled, RS_ PUB_ KEY is not effective.
I try to modify libs\hbb_common\src\config.rs      82-84 lines

pub const RS_ PUB_ KEY: &str = match option_ env! ("RS_PUB_KEY") {
Some(key) if ! key.is_ empty() => key,
_ => "OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=",

Not effective 

I hope the author replies that trustdesk is a good software. I hope he can be better in the future

**Comment by rustdesk** [comment] 2023-03-08 09:16
```
  pub const RS_PUB_KEY: &str = match option_env!("RS_PUB_KEY") { 
      Some(key) if !key.is_empty() => key,
      _ => "OeVuKk5nlHiXp+APNn0Y3pC1Iwpwn44JGqrQCsWqmBw=",
  };
 
 fn main() {
     println!("{}", RS_PUB_KEY);
 }
```

![image](https://user-images.githubusercontent.com/71636191/223672360-4a151fa4-0840-4dbf-b533-d615215f8f61.png)

**Comment by zyk014** [comment] 2023-03-08 10:11
大佬 能直接说明下windows编译RS_PUB_KEY加进去怎么才会生效？
编译研究了好久，现在就是这个RS_PUB_KEY没有加进去。导致连接失败提示key错误

**Comment by nextgen-networks** [comment] 2023-03-08 12:57
> @nextgen-networks could you confirm if RENDEZVOUS_SERVER and RS_PUB_KEY still work on your repo?

@rustdesk sorry for my late reply
After deeper investigation I can confirm that RENDEZVOUS_SERVER is working in daily nightly builds.
Sadly RS_PUB_KEY does not.

I had previously written that with old builds the RS_PUB_KEY variable is correctly retrieved and transferred to the build, but I must correct myself here.

My assumption: On the systems I tested, there were still cached configuration data that were reloaded and where an RS_PUB_KEY was stored, but this was not displayed in the GUI.

After I cleaned all 3 involved test systems from the configuration data (in %AppData%\RustDesk\ and C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\) and uninstalled the installed services, I could not establish a connection on these systems without additional configuration of the pub key in the GUI.

On the other hand, the information in the GUI in the ID/Relay server tile does not need to be populated. They are obviously read correctly during the build process.

**Comment by zyk014** [comment] 2023-03-10 07:39
Sorry, I still can't understand. Can you tell me the simplest way to modify RS_ PUB_ KEY？
Thank you. This problem has troubled me for a long time

**Comment by rustdesk** [comment] 2023-03-10 14:27
Marked as help-wanted, leave to contributors fixing it since this feature came from contributors.

**Comment by jacotec** [comment] 2023-03-17 12:34
I'm looking for a solution to this as well. Interestigly hardcoding server and key in /libs/hbb/common/src/config.rs does not work for me as well (as @zyk014 has already mentioned above). Which is strange. Isn't this hardcoding used at all @rustdesk ?

Also I see this is a one-way problem. When I install my build on a PC without entering the Server URL / Key in the GUI, I still can do *outgoing* connections from that machine via the relay server - but the machine can't be reached by incoming connections.

Maybe this gives a hint to the root cause?

**Comment by yash1597** [comment] 2023-03-17 14:34
@zyk014 @nextgen-networks @kwisatz @xxjasonxx1996 
i am on windows10 i successfully build release for windows

"to hardcoded my server ip and key"

i changed in \rustdesk\libs\hbb_common\src\config.rs
pub const RENDEZVOUS_SERVERS: &[&str] = &[
"***my_server_ip***",
];

pub const RS_PUB_KEY: &str = match option_env!("RS_PUB_KEY") {
Some(key) if !key.isempty() => key,
=> "******my_server_key********",
};
so after that i build release, when i send that release to my colleague and after that when we try to connect then this "key mismatch" error is coming

and if i am doing wrong please correct me, thank you.

**Comment by jacotec** [comment] 2023-03-17 16:52
It looks for me like #2921

It's not working when the server is running with the -k _ option, because the public key is not written into the config. Once the key is written to the config, it works also on virgin installations without putting the data in the GUI.

I've created PR #3702 for this. That works for me.

**Comment by yash1597** [comment] 2023-03-17 17:14
thanks brother @jacotec i will surely check this and update to you.

**Closed** 2023-03-19 16:56 UTC
Labels: help wanted

**Comment by rustdesk** [comment] 2023-03-19 17:01
This commit https://github.com/rustdesk/rustdesk/commit/706e0800714af18fa5491b2d8a86a7f02d762e5f should fix the issue with github actions.

**Comment by deep-soft** [comment] 2023-03-19 23:18
> This commit [706e080](https://github.com/rustdesk/rustdesk/commit/706e0800714af18fa5491b2d8a86a7f02d762e5f) 

broke
Flutter Nightly Build
  jobs:
    build-for-windows

if let Some(lic) = windows::get_license() {
should be
if let Some(lic) = crate::platform::windows::get_license() {

**Comment by nextgen-networks** [comment] 2023-03-22 12:55
My builds (no hardcoded settings) are build without errors and they work like a charm with custom server and key settings! *yay* Thank you very much!

**Comment by yashpatel1599** [comment] 2023-03-31 09:59
@deep-soft @nextgen-networks @jacotec i checked your PR #3701 and i also add in my windows build it works perfect in windows when i follow same on linux is not working so my issue is key mismatched error is coming when i am trying to connect to others and it because of key is not embedded in .deb file ,do you guys know about how to with linux Ubuntu ?
i want a harcoded key so for that i make changes in this files 
\rustdesk\libs\hbb_common\src\config.rs where 
pub const RS_PUB_KEY: &str = match option_env!("RS_PUB_KEY") {
Some(key) if !key.isempty() => key,
=> "my_server_key**",
};
but still is not working.
