### ISSUE TITLE
audio stream present after remote desktop connection closed

### ISSUE THREAD

**Issue by liveuser1** [rustdesk/rustdesk#5767] opened 2023-09-21 00:31 UTC
### Bug Description

I closed window with remote screen. Did not close main program window on my side. Other side did not stop service. After some time (10 minutes+), other side run some music, I could hear it loud and clear, same as if I had remote desktop window open. 
For connection we are using private id server with latest docker img installed.

### How to Reproduce

I am currently not in the position to try to reproduce. Will update next time.

### Expected Behavior

Expecting connection close fully after remote desktop window closed.

### Operating system(s) on local side and remote side

my side - win7 sp1, other side - win11 22h2

### RustDesk Version(s) on local side and remote side

1.2.2-x86_64 -> 1.2.2-x86-sciter

### Screenshots

-

### Additional Context

rustdesk.exe consumes about 70Mb of memory (as task control shows) right after I run it (without active inbound connection service running). After some connections it consumes 200Mb+

**Comment by rustdesk** [comment] 2023-09-21 03:23
@21pages check if you can reproduce.

**Comment by 21pages** [comment] 2023-09-21 03:41
There are some things that need to be confirmed.
1. Is the controlled side installed or portable? if installed, that's expected.
2. When closing the main window of the controlled side, did "connect..." dialog appear on the local side?

**Comment by liveuser1** [comment] 2023-09-21 04:05
Service on controlled side is installed and set to autorun.
I closed main window on local side. Where were no open remote desktop window at the time, I am sure of it. There were no dialog windows when closing main program. It closed instantly and music stopped right away.

I can collect logs from both sides, if it helps, just don`t want to make them public. Where I can send them if you want it?
I`ll try to reproduce tomorrow.

**Comment by 21pages** [comment] 2023-09-21 04:13
Thanks for the details, I'll try to reproduce it. You can send the log to my email,  `cGFnZXMyMUAxNjMuY29tCg==` , base64

**Comment by rustdesk** [comment] 2023-12-03 03:51
Close since inactivity.

**Closed by rustdesk** 2023-12-03 03:51 UTC
Labels: bug
