### ISSUE TITLE
Input the fourth ID in the input box, and the cursor always jumps back to the previous position

### ISSUE THREAD

**Issue by intionwun** [rustdesk/rustdesk#1605] opened 2022-09-23 04:18 UTC
**Describe the bug you encountered:**

Input the fourth ID in the input box, and the cursor always jumps back to the previous position

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**

GitHub release-Windows portable

---

**RustDesk version and environment**
1.1.9  Windows 10 21H2

**Comment by rustdesk** [comment] 2022-09-23 04:51
Sorry, can not understand you, upload a video recording please.

**Comment by rustdesk** [comment] 2023-04-09 14:34
Close this because can not reproduced on our side, and no further report from the other users.

**Closed** 2023-04-09 14:34 UTC
Labels: bug, unreproducible
