### ISSUE TITLE
connection error:os error 10054

### ISSUE THREAD

**Issue by titilami** [rustdesk/rustdesk#1113] opened 2022-07-29 16:25 UTC
**Describe the bug you encountered:**
cannot connect remote compute.
error: 远程主机强迫关闭了一个现有连接。(os error 10054)
...

**What did you expect to happen instead?**

...

**How did you install `RustDesk`?**
self-host: ubuntu 18.0.4
remote client: mac
local: win 11.

---

**RustDesk version and environment**
version 1.1.9

**Comment by rustdesk** [comment] 2022-07-29 16:28
https://github.com/rustdesk/rustdesk/issues/411

**Comment by rustdesk** [comment] 2022-07-29 16:28
@21pages follow up.

**Comment by 21pages** [comment] 2022-07-29 22:51
It happens while connecting, or already connected ? Can you reconnect successfully next time ?

**Comment by titilami** [comment] 2022-07-30 02:20
> It happens while connecting, or already connected? Can you reconnect successfully next time? Is your network in good condition? This often happens when I switch networks.

i cann't connect. i restarted mac and windows rustdesk client, but it seems doesn't work.

**Comment by rustdesk** [comment] 2022-07-30 04:06
Probably firewall issue, no the other clue either.

**Comment by titilami** [comment] 2022-07-30 07:44
> Probably firewall issue, no the other clue yet.

it was connected succuss after installed. but several days later, connect error. self-host ubuntu 18.0.4 ufw  enable rustdesk tcp and udp port. teamview and sunlogin works well.

**Comment by 21pages** [comment] 2022-07-30 07:48
Have you tried using public server?

**Comment by titilami** [comment] 2022-07-30 08:14
> Have you tried public server?
yes, i tried public server and self-host.
![image](https://user-images.githubusercontent.com/15050609/181891580-a5d9dd42-a829-4d73-9ae4-d50216c4f6d8.png)

**Comment by titilami** [comment] 2022-07-30 08:19
> Have you tried public server?

but mac client can connect windows

**Comment by rustdesk** [comment] 2022-07-30 08:40
wondering if you can help us dig into the issuse? it confused us for long, but we can not reproduce. it seems you are a coder, you can give you help if you need.

**Comment by titilami** [comment] 2022-07-30 08:57
![image](https://user-images.githubusercontent.com/15050609/181903228-51fa9568-e627-411d-9946-a1bc0b83574f.png)

**Comment by titilami** [comment] 2022-07-30 08:58
> wondering if you can help us dig into the issuse? it confused us for long, but we can not reproduce. it seems you are a coder, we can give you help if you need.

ok

**Comment by rustdesk** [comment] 2022-07-30 09:03
You can follow this to run from source code,

https://rustdesk.com/docs/en/dev/build/osx/

Let me know if you have any problem.

**Comment by rustdesk** [comment] 2022-07-30 09:03
uninstall your RustDesk first before `cargo run`.

**Comment by 21pages** [comment] 2022-07-30 09:13
[wireshark](https://www.wireshark.org/#download) can capture tcp and udp, and you can use tcpdump on linux, eg: `tcpdump -i any -w any.cap` will capture all network interface, you can open cap file with wireshark.

**Comment by titilami** [comment] 2022-07-30 10:01
> uninstall your RustDesk first before `cargo run`.

i meet some problem while uninstall rustdesk. i have setting rustdesk auto run when mac reboot(https://support.apple.com/en-hk/guide/mac-help/mh15189/mac#:~:text=On%20your%20Mac%2C%20choose%20Apple,%2C%20then%20click%20Users%20%26%20Groups%20.&text=Select%20your%20user%20account%2C%20then,other%20item%2C%20then%20click%20Add.). but i cann't kill rustdesk process. if reboot mac, rustdesk may work well.

**Comment by rustdesk** [comment] 2022-07-30 10:03
You can unselect `enable service` from the main menu of RustDesk window. It will remove the services, then uninstall RustDesk.

**Comment by rustdesk** [comment] 2022-07-30 10:04
My wechat is `rustdesk`, you talk there if you like.

**Comment by titilami** [comment] 2022-07-30 10:14
![image](https://user-images.githubusercontent.com/15050609/181905817-d0deb8dd-db21-420b-8267-f55cf7d00f82.png)

**Comment by rustdesk** [comment] 2022-07-30 16:46
Conclusion (Thanks to @titilami 's colaboration): the direct connection was established, but it is later forcely closed somehow (maybe security software). I manually modifed code to use relay connection, it is ok.
Solution: how to force using relay connection in this case (10054, switching wifi connection also has this problem per @21pages, he solved this by turn off/on wifi)?

**Comment by rustdesk** [comment] 2022-07-30 16:53
Close this so that we can focus on its dup https://github.com/rustdesk/rustdesk/issues/1113#issuecomment-1200250142

**Comment by hexbinoct** [comment] 2022-11-10 10:24
> Probably firewall issue, no the other clue yet.

does rustdesk auto configures Windows firewall setting or we have to do it ourselves? Whats the port to configure if has to be done manually?

**Comment by Flexmaen** [comment] 2022-11-17 20:34
I have the same problem when trying to connect from one Windows computer to the other one.
From the Andorid tablet to the same Windows computer works.

**Comment by rustdesk** [comment] 2022-11-22 14:35
Can you try out nightly build? There is a fix, though not good enough, not sure if it works in your scenario.

**Comment by Flexmaen** [comment] 2022-11-22 14:56
The nightly build works! On the 1st try it fails with the mentioned error message but then it immediately starts a 2nd tray that works!
I did try with more devices and have these problems on one computer only.

**Comment by rustdesk** [comment] 2022-11-22 14:57
> The nightly build works! On the 1st try it fails with the mentioned error message but then it immediately starts a 2nd tray that works!

Yes, it is expected.

**Comment by kintaro1981** [comment] 2022-11-28 13:37
I have the same issue and nightly solved on second try.

**Comment by bilogic** [comment] 2023-02-20 13:44
What is the cause of this actually?

**Comment by bilogic** [comment] 2023-03-14 05:00
Rustdesk can punch through double NAT, but after a 30 seconds, it get cut off.. any idea why?
It would be good if it can maintain the connection, it is much faster

**Comment by rvkennedy** [comment] 2023-05-04 13:16
I'm not clear on what the solution was to this. I'm seeing the issue connecting Windows-to-Windows with the current version as of May 2023. After a few minutes, the connection cuts out. Only with one particular remote machine.

**Comment by TeamPattuki** [comment] 2023-06-16 07:43
I also encountered this 10054 os error on rustdesk, I tried using different versions like nightly, but didn't work. I was only able to fix this using vpn, but when i'm not connected to the vpn the error comes back, I think it is some networking problem. I tried teamviewer and it works for for me with/without vpn. But I prefer rustdesk for simplicity.

**Comment by Blacknana** [comment] 2023-07-01 02:17
I encountered the same 10054 os error, and nightly version didn't work. The sunlogin can connect successfully.

**Comment by rustdesk** [comment] 2023-07-01 02:26
@21pages readdress https://github.com/rustdesk/rustdesk/pull/1127

**Comment by rustdesk** [comment] 2023-07-01 02:29
@Blacknana can we connect to you machine for testing, if yes, please send mail to info@rustdesk.com

**Comment by cleudsoncosta** [comment] 2023-11-09 13:51
Hi, I installed Rustdesk on a client 4 computers on the same network, it only worked on 1, because on the others after 30 seconds the connection drops with the same error 0054 os error.
Debian server version 1.2.2

**Comment by 21pages** [comment] 2023-11-09 13:58
> after 30 seconds the connection drops

@cleudsoncosta  Connections receiving data will not be automatically relayed. Relay connection may solve the problem, try add \r after the id to connect.

**Comment by cleudsoncosta** [comment] 2023-11-09 14:14
> > after 30 seconds the connection drops
> 
> @cleudsoncosta Connections receiving data will not be automatically relayed. Relay connection may solve the problem, try append `/r` to the id to connect.
> 
> ![image](https://user-images.githubusercontent.com/71636191/281756181-e97b8ed2-6894-4ce6-a68b-3db67bc10880.png)
> 
> ![image](https://user-images.githubusercontent.com/71636191/281756140-3df947e9-b755-4e06-8606-7cfe0993e9e8.png)

ok its works for me tks

**Comment by rustdesk** [comment] 2023-11-09 14:18
> because on the others after 30 seconds the connection drops with the same error 10054 os error.

The messagebox did not remind you trying out force-relay?

**Comment by cleudsoncosta** [comment] 2023-11-09 14:20
> > because on the others after 30 seconds the connection drops with the same error 10054 os error.
> 
> The messagebox did not remind you trying out force-relay?

yes, its ok now. tks

**Comment by aquananu** [comment] 2024-04-16 11:08
hi i am having the same issue when connecting to a particular machine, the rust desk in 1.2.3.2 Build date: 2024-04-07 08:56, using a self hosted rustdesk server installed on debian container under proxmox server

Can someone help how to fix

**Comment by rustdesk** [comment] 2024-04-16 11:20
Solution: https://github.com/rustdesk/rustdesk/wiki/FAQ#force-relay

**Closed by rustdesk** 2024-04-16 11:20 UTC
Labels: bug, duplicate
