### ISSUE TITLE
Hebrew keyboard layout problems

### ISSUE THREAD

**Issue by fish7221** [rustdesk/rustdesk#2676] opened 2022-12-29 11:40 UTC
Hello,
I just wanted to report a problem I've seen when typing in hebrew in a remote PC using latest 1.19 rusdesk related to a specific key/character.
When both local and remote computers in hebrew writing mode, The characters "?" or "." which are used by the same "/" key (with or without shift) is presenting different characters. When I switch both computers to english, I can write those characters, But the switching is uncomfortable.
Thank you

**Comment by rustdesk** [comment] 2022-12-29 11:44
try out nightly build please.

**Comment by rustdesk** [comment] 2022-12-29 11:45
https://github.com/rustdesk/rustdesk/issues/1547

**Comment by fish7221** [comment] 2022-12-29 12:05
Thank you for the reply.
Nightly 1.20 version which I've installed on both computers still did NOT solved the problem.

**Comment by rustdesk** [comment] 2022-12-29 12:15
@fufesou

**Comment by rustdesk** [comment] 2022-12-29 12:16
What language and the type of keyboard?

**Comment by fish7221** [comment] 2022-12-29 12:22
The language is Hebrew and keyboard is "Hebrew (Standard) Keyboard"

**Comment by rustdesk** [comment] 2022-12-29 12:24
> Hebrew

Thanks, i thought it is Mac's homebrew, :)

**Comment by fufesou** [comment] 2022-12-29 13:12
@fish7221 Hi, I can't reproduce this issue on "Map mode".
What OS you're using on both sides? And what keyboard mode do you set?

![image](https://user-images.githubusercontent.com/13586388/209955537-cfa63e60-ad13-4d92-bba2-51f84f6c6e16.png)

**Comment by fish7221** [comment] 2022-12-29 13:42
Thank you SO MUCH. The map mode on v1.20 solved tthe hebrew problem.

**Comment by fufesou** [comment] 2023-01-06 05:31
> Nightly 1.20 version which I've installed on both computers still did NOT solved the problem.

@fish7221 It seems "Legacy mode" is used by default.

I've read the code. The default keyboard mode should be "Map mode" on Nightly build. Did you change the keyboard mode before.

BTY, please close the issue if you confirm it is fixed. Thanks.

**Closed** 2023-01-28 10:00 UTC
