### ISSUE TITLE
Failed to connect to client with 800x600 resolution (virtual display)

### ISSUE THREAD

**Issue by fernandeusto** [rustdesk/rustdesk#5521] opened 2023-08-26 22:41 UTC
### Bug Description

If you try to connect to a windows client with a resolution of 800x600 or less, rustdesk displays the message "connecting" indefinitely.

On the client computer you appear as connected, but the control computer does not see the remote screen and continues with the message "connecting"

This happens with any codec and screen configuration in rustdesk

If you change the resolution to higher than 800x600 from the client, then in the next attempt, the remote control can be connected immediately.

When you are already connected, if the client changes the resolution back to 800x600 on his pc, the remote control screen freezes and the client's movements are not seen, until a higher resolution is established again

### How to Reproduce

1 - set up a connection to a client and test that it works.
2 - disconnect
3 - on the client computer change the resolution to 800x600
4 - try to connect remotely again

### Expected Behavior

You should be able to see and control equipment with low resolutions of 800x600

### Operating system(s) on local side and remote side

Windows 11 --> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.3 --> 1.2.3 Nightly

### Screenshots

<img width="249" alt="image" src="https://github.com/rustdesk/rustdesk/assets/87156183/367366cb-6dba-4542-92f4-f2396c009e6f">

**Comment by rustdesk** [comment] 2023-08-27 01:43
@fufesou virtual display not working？

**Comment by fufesou** [comment] 2023-08-27 02:35
I don't think it is related to the virtual display, as the state is stuck at "Connection...".

I'll try to find the reason.

BTW, the virtual display logic also need to be improved.

**Comment by rustdesk** [comment] 2023-08-27 03:00
build a version wirhout 800 logic, he can try

**Comment by fufesou** [comment] 2023-08-27 04:37
@fernandeusto Hi, can you please help try if this build works when the controlled resolution is 800x600?

https://github.com/fufesou/rustdesk/releases/tag/tmp

**Comment by fernandeusto** [comment] 2023-08-27 09:54
> @fernandeusto Hi, can you please help try if this build works when the controlled resolution is 800x600?
> 
> https://github.com/fufesou/rustdesk/releases/tag/tmp

Yes, with this build it seems to work correctly. Please apply it to the official nightly. Thanks

**Comment by rustdesk** [comment] 2023-08-27 12:58
though https://github.com/rustdesk/rustdesk/pull/5525 fixed this issue, but this issue tell us virtual display implementation is buggy.

**Comment by fufesou** [comment] 2023-08-27 15:05
> though I guess #5525 fix this issue, but it is a workaround only, but this issue tells us virtual display implementation has unknown bug. I will keep this issue open until we really solve the underlying issue.


@fernandeusto Hi, can you please help test this build.
https://github.com/fufesou/rustdesk/releases/tag/tmp

The issue should be still there in this build.
I've added some logs to find the reason of the unknown bug.

Please make sure the connection is stuck, and then attach the log files here
```
C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\rustdesk_rCURRENT.log
```

**Comment by fernandeusto** [comment] 2023-08-27 22:52
I have not been able to replicate it again. When I reinstall after testing the temporary build that you sent me, and return to the official one, with the "--reinstall" command, the problem has been resolved.
I found that the virtual display controller driver was installed but with the exclamation of driver not found, when it gave the error.
Now it works fine with the official build, the only way to replicate the bug is to manually uninstall the virtual display driver from device manager and then connect but the control stays with the "connecting..." screen and so it reproduces the error.
On other computers with 800x600 resolution, the virtual display driver does not appear in the device manager and yet it works after the "--reinstall" option. I don't know why the driver appears on some computers and not on others.
thank you very much for the excellent support
At the moment it seems that it has been solved by running:
"rustdesk-1.2.3-x86_64.exe --reinstall"

**Comment by rustdesk** [comment] 2023-08-28 02:20
> the exclamation of driver

This is the biggest problem, we have the other users reporting this, absolutely it is very common, because we have few users using virtual display. Without resolving this issue, our virtual display implmentation is almost unusable.

**Comment by rustdesk** [comment] 2023-08-28 02:22
@fufesou let's remove 800 before we can solve "the exclamation of driver".

**Comment by fufesou** [comment] 2023-08-28 02:43
Ok. I also reproduced this issue by mannually remove the driver directory.

I'll remove the virtual display. And then fix this underlying bug.

**Comment by fufesou** [comment] 2023-08-28 13:56
> the underlying issue

1. The virtual display will try 20 times to plug in virtual display. The interval is 1 second.
2. Querying the displays will try to plug in the virtual display everytime.
3. Sending the peer info will query the displays twice. 2 * 20s = 40s.

So the connection will timeout.

https://github.com/rustdesk/rustdesk/pull/5534

I will continue to find the cause of "the exclamation of driver".

**Comment by fernandeusto** [comment] 2023-08-28 14:01
In my case, on the client side it appears as a connected control, but in the control I kept seeing the connecting sign. If at that moment the client increases the resolution, the control sees the screen normally, if it goes down again to 800x600 the last frozen image stays.

**Comment by fufesou** [comment] 2023-08-28 14:49
@fernandeusto Hi, can you please try the idd demo? To see if "the exclamation of driver" also exists on the demo.

https://github.com/fufesou/RustDeskIddDriver/releases/tag/v0.3


https://github.com/rustdesk/rustdesk/assets/13586388/4a584c46-5214-4186-8642-c9b2ffce68dc

1. Run "install_cert_runas_admin.bat" as Administrator.
2. Run "RustDeskIddApp.exe" as Administrator.
3. Command "c" --> "i" --> "a" ...

**Comment by fernandeusto** [comment] 2023-08-29 08:52
> 2\. RustDeskIddApp.exe
<img width="987" alt="image" src="https://github.com/rustdesk/rustdesk/assets/87156183/7ffb775f-87db-4f06-920c-8ca7333ff4ab">

error executing command 2
The reinstallation is done and the display driver does not appear in the device manager

<img width="507" alt="image" src="https://github.com/rustdesk/rustdesk/assets/87156183/6e160a80-10a7-4828-804b-032fb53e66d2">

<img width="537" alt="image" src="https://github.com/rustdesk/rustdesk/assets/87156183/c7a9caa6-b9da-48b0-8722-cfec0811fdb3">

**Comment by fufesou** [comment] 2023-08-29 09:37
Thanks for your feedback.

> The original version run ok on 800x600 as default install whitout driver. no error now

Yes, RustDesk has currently removed the virtual display driver, as it is not able to fix "the exclamation of driver".


And sorry for the missing files in the RustDeskIddApp.exe pack.
Can you please try this build again? Thx.

https://github.com/fufesou/RustDeskIddDriver/releases/tag/v0.3.1

**Comment by fernandeusto** [comment] 2023-08-29 21:31
Now I have been able to follow the indicated steps and the driver is installed correctly.

<img width="497" alt="image" src="https://github.com/rustdesk/rustdesk/assets/87156183/048f5a29-3cd6-4a6e-ae02-108ebfb51936">

but in windows it appears as an extended screen with maximum resolution. I understand that it should appear as a duplicate screen and with the same resolution.

<img width="1180" alt="image" src="https://github.com/rustdesk/rustdesk/assets/87156183/e1f06c5c-21aa-4269-bb18-9ac14f9322f3">

the connection to the remote computer is correct in any resolution although I understand that rustdesk does not use the virtual driver now

**Comment by fufesou** [comment] 2023-08-29 23:37
"RustDeskIddApp.exe" inserts a fixed 1920x1080 virtual display.

**Comment by rustdesk** [comment] 2023-10-30 09:22
close as duplicate https://github.com/rustdesk/rustdesk/issues/5582

**Comment by rustdesk** [comment] 2023-10-30 09:22
Please try out the latest nightly build, we have some fix for this. https://github.com/rustdesk/rustdesk/releases/nightly

**Closed by rustdesk** 2023-10-30 09:22 UTC
Labels: bug
