### ISSUE TITLE
"Copy and paste" between the local and remote side doesn't work in the first connection

### ISSUE THREAD

**Issue by BeingNoAbility** [rustdesk/rustdesk#5910] opened 2023-10-04 16:56 UTC
### Bug Description

"Copy and paste" between the local and remote side doesn't work in the first connection. I have to disconnect the connection and then reconnect to copy and paste, whether a file or plain text.

### How to Reproduce

Connect to the remote side

### Expected Behavior

"Copy and paste" should work in the first connection.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

No useful screenshot to show this issue.

**Comment by rustdesk** [comment] 2023-10-05 03:23
@fufesou

**Comment by rustdesk** [comment] 2023-10-05 08:58
@sahilyeole please reproduce this.

**Comment by sahilyeole** [comment] 2023-10-05 20:14
I almost made 30-35 attempts but this issue did not occur.

@BeingNoAbility Can you please check this video and let me know if I'm attempting it correctly or not?

https://github.com/rustdesk/rustdesk/assets/73148455/45e405f5-d9b1-4910-8974-bdfda401d84f

**Comment by BeingNoAbility** [comment] 2023-10-06 06:24
> I almost made 30-35 attempts but this issue did not occur.
> 
> @BeingNoAbility Can you please check this video and let me know if I'm attempting it correctly or not?
> 
>  20231005_124858.mp4

@sahilyeole Maybe I have described it wrong. The remote service is always on. "First connection" means connecting to the remote side again since I last connected to it, maybe a day ago.
I also enabled "lock the computer when it's disconnected". So when I connect to the remote side in the first connection, it remains locked. I don't know whether it's related.

**Comment by sahilyeole** [comment] 2023-10-07 21:08
Sorry but I could not reproduce it, I tried waiting for longer intervals between connections with "lock when disconnected" feature but copy paste was always working. Also can't afford to wait for a day between connections while keeping a remote windows always on as I need to work on other environments too.

@BeingNoAbility If you can tell the approximate minimum interval of time it takes between connections to occur and the frequency of the times it occurs, I can still try more.
But again it's quite hard to reproduce since it's random and takes time.

**Comment by rustdesk** [comment] 2023-10-08 03:52
Marked as unreproduciable, @sahilyeole can pause on this issue.

**Comment by BeingNoAbility** [comment] 2023-10-08 06:32
@sahilyeole I think it's related to the screen that turns off.

Let me detail what I have done.
1. Change the Windows setting to let the screen turn off after 1 minute instead of 15 minutes.
2. Wait 1 minute, copy some texts on the local side(maybe related), then connect to the remote side.
3. Because I enabled "Auto Login" in the rustdesk, it will press "Enter", and then show the enter password interface.
4. But in the first connection, the "Auto Login" will stop here, not entering the password automatically.
5. I have to click the "Operating System Password" in the toolbar of rustdesk, and then it will enter the password.
6. Copy and paste doesn't work
7. Disconnect
8. Reconnect immediately to the remote side. The "Auto Login" will work as intended; no need to click the "Operating System Password".
9. Copy and paste works

I reproduced the issue once by this procedure, though it's still not steady.

**Comment by rustdesk** [comment] 2023-10-08 06:37
> * Change the Windows setting of the remote side to let the screen turn off after 1 minute instead of 15 minutes.
> * Wait 1 minute, copy some texts on the local side(maybe related), then connect to the remote side.
> * Because I enabled "Auto Login" in the rustdesk, it will press "Enter", and then show the enter password interface.
> * But in the first connection, the "Auto Login" will stop here, not entering the password automatically.
> * I have to click the "Operating System Password" in the toolbar of rustdesk, and then it will enter the password.
> * Copy and paste doesn't work
> * Disconnect
> * Reconnect immediately to the remote side. The "Auto Login" will work as intended; no need to click the "Operating System Password".
> * Copy and paste works

@sahilyeole let's have the final attempts.

Thanks @BeingNoAbility  for your patience.

**Comment by sahilyeole** [comment] 2023-10-08 08:24
Ok, I have reproduced it. Thanks for the details.
It's related to this
>copy some texts on the local side(maybe related), then connect to the remote side.

Copying text **BEFORE** making a connection does not work, **ONLY** if "lock when disconnected" is enabled otherwise it is working. Also when it does not work if I copy something **after making the connection, it works**, it can be pasted.

@BeingNoAbility So, please confirm this:
```
1. have "lock when disconnected" enabled
2. copy some text on local
3. make connection
4. login screen appears, then login
5. try to paste, it does not paste the text you have copied
6. but now after making the connection, try copy-paste, it works
```

If the above things are true, it's a very specific case issue, and the title of this issue can be changed since:
1. copy-paste always works on the first connection
2. it also works on the first connection if "lock when disconnected" is enabled, if you copy-paste something after making the connection
3. it only does not work when 2. case is true but you copy something before making the connection and then try to paste it, but copy-paste works if you copy something after making the connection

https://github.com/rustdesk/rustdesk/assets/73148455/906413bd-d7de-46eb-8a58-4f9e20720d9c

Copying text before connection works if no login screen (no "lock when disconnected" feature) on the remote side:

https://github.com/rustdesk/rustdesk/assets/73148455/981411e5-e772-4115-bb3f-5e168ef27a5f

**Comment by rustdesk** [comment] 2023-10-08 08:26
@fufesou please give some hint to @sahilyeole for possible solution.

**Comment by BeingNoAbility** [comment] 2023-10-08 09:26
@sahilyeole 

> 1. have "lock when disconnected" enabled
> 2. copy some text on local
> 3. make connection
> 4. login screen appears, then login
> 5. try to paste, it does not paste the text you have copied
> 6. but now after making the connection, try new copy-paste, it works

It shouldn't be this simple. As I remember, 6 is not true. New copy-paste also doesn't work. But I'm now questioning whether I remembered wrong. I'll test again to see if that's true.

**Comment by BeingNoAbility** [comment] 2023-10-08 11:21
> 1. have "lock when disconnected" enabled
> 2. copy some text on local
> 3. make connection
> 4. login screen appears, then login
> 5. try to paste, it does not paste the text you have copied
> 6. but now after making the connection, try new copy-paste, it works

@sahilyeole I've checked 6. If you copy text, for example "test" before connection, then you can't paste the same text "test" after connection, even if I recopy "test" at the local side when the connection is still on. But if I recopy something else, for example "rustdesk", then I will be able to copy and paste "test" again.

This is strange but kind of understandable. Thank you so much for doing so many tests!

**Comment by sahilyeole** [comment] 2023-10-08 11:26
>you can't paste the same text

Oh, interesting. I'll look into it. Thanks.

**Comment by rustdesk** [comment] 2023-10-08 11:41
> > you can't paste the same text

This is very normal for many app.

**Comment by rustdesk** [comment] 2023-10-08 11:41
Let's pause here.

**Closed by rustdesk** 2023-10-08 11:41 UTC
Labels: bug, unreproducible
