### ISSUE TITLE
control macos cant trigger hot coner and hided dock bar

### ISSUE THREAD

**Issue by ctermiii** [rustdesk/rustdesk#2883] opened 2023-01-20 14:44 UTC
**Describe the bug you encountered:**
windows control macos cant trigger hot corner and hided dock bar
...

**What did you expect to happen instead?**
remote control macos as local use
...

**How did you install `RustDesk`?**
windows: from github releases
macos: from brew and github releases all the same.

---

**RustDesk version and environment**
1.20 nightly build

**Comment by rustdesk** [comment] 2023-02-03 04:15
reproduced， @fufesou

**Comment by rustdesk** [comment] 2023-02-03 05:07
I believe windows has the same issue if we auto hide windows taskbar.

**Comment by fufesou** [comment] 2023-02-06 03:18
@ctermiii Hi, thanks for your feedback.

The dock bar will not show if fullscreen is set. It is a problem and should be fixed.

Please choose window mode if this doesn't bother you.

https://user-images.githubusercontent.com/13586388/216875807-9ee9040f-ebd7-4a50-9d44-165bced2c96c.mp4

**Comment by ctermiii** [comment] 2023-02-06 03:20
> @ctermiii Hi, thanks for your feedback.
> 
> The dock bar will not show if fullscreen is set. It is a problem and should be fixed.
> 
> For now, please choose window mode if it doesn't bother you.
> 
>  sss.mp4

thanks for your response.

**Comment by rustdesk** [comment] 2023-03-09 12:29
@Kingtous

**Comment by rustdesk** [comment] 2023-03-09 12:36
and docker/menu shows up on controlling side (osx) in full screen.


https://user-images.githubusercontent.com/71636191/224024986-fdc278e5-e584-4efb-ac4b-b624379c0b66.mp4

**Comment by rustdesk** [comment] 2023-03-09 14:05
https://user-images.githubusercontent.com/71636191/224049333-4d61c6df-904c-465c-a5e2-ef7f341898d5.mp4

**Comment by ctermiii** [comment] 2023-03-12 14:50
windows下nightly 客户端远程连接macos13，测试发现使用原始分辨率，可以正常触发hide dock和hot conner；使用adaptive scale，只能触发右上角(默认的note)，偶尔触发了一次右下角(不能重现)，左上左下未触发。

**Comment by rustdesk** [comment] 2023-03-12 15:02
@fufesou

**Comment by fufesou** [comment] 2023-03-13 01:42
@ctermiii Thanks for your feedback. I can trigger the dock bar with both "Original scale" and "Adaptive scale".

What're the resolutions on both size? Can you please upload a video?

https://user-images.githubusercontent.com/13586388/224588169-a87e0aee-d118-4136-8395-a097d80d75a8.mp4

But it seems the dock bar cannot be triggered if mouse is moved here. (In the red rectangle)
![image](https://user-images.githubusercontent.com/13586388/224589428-43f02d90-750b-4ff1-9669-247b4e2f6a9b.png)


I'll test more and improve the experience.

**Comment by fufesou** [comment] 2023-03-13 01:53
https://user-images.githubusercontent.com/13586388/224590575-3341e88a-0f3b-49ac-a739-d7ec8b319265.mp4

**Comment by rustdesk** [comment] 2023-03-29 00:41
close since fix merged

**Closed** 2023-03-29 00:41 UTC
Labels: bug

**Comment by rustdesk** [comment] 2023-04-01 11:11
address right edge later, we can not stop here.

**Comment by rustdesk** [comment] 2023-04-09 15:22
> Address right edge with lower priority, we can not pause here. added in milestone. @fufesou
> 
> * [ ]  As for mouse selection, it should work undouteless in full screen.
> * [ ]  In the other windows mode it seems unavoidable because of sizing detection, let's decide after checking AnyDesk.
> * [ ]  As for triggering taskbar which is placed on left/right side, it should work on all window modes.

@fufesou confirm above

**Comment by fufesou** [comment] 2023-04-11 01:48
> Address right edge with lower priority, we can not pause here. added in milestone. @fufesou
> 
> * [x]  As for mouse selection, it should work undouteless in full screen.
> * [x]  In the other windows mode it seems unavoidable because of sizing detection, let's decide after checking AnyDesk.
> * [x]  As for triggering taskbar which is placed on left/right side, it should work on all window modes.

Win -> Win Works fine for me.
