### ISSUE TITLE
Keyboard Input not working

### ISSUE THREAD

**Issue by MrMineDe** [rustdesk/rustdesk#6338] opened 2023-11-08 14:28 UTC
### Bug Description

If I type something with the keyboard with the phone connected, nothing happens. No key seems to work.
I tried all 3 Keyboard modes, but the behavior did not change. I also checked the settings. The disable keyboard option is not enabled. On my controlling device, the keyboard layout is colemak_dh. I changed this to the default qwerty layout(with setxkbmap) and restarted the program. The issue persisted though.

### How to Reproduce

Install RustDesk on Android (11) via Release Section on Github
Start Server and add permissions for everything(i mean not everything is needed, but i had all enabled just to be sure...)

Install RustDesk AUR package (on Arch Linux)
(this doesnt seem to have an impact but maybe im just not seeing it:)
Change keymap to colemak_dh in Xorg:
setxkbmap us -variant colemak_dh
start rustDesk and connect to Android Client via ID 

### Expected Behavior

Be able to use the keyboard

### Operating system(s) on local side and remote side

Android 11 -> Arch Linux 

### RustDesk Version(s) on local side and remote side

1.2.3 -> 1.2.3

### Screenshots

There is no screenshot that would describe this behavior.

### Additional Context

To change to qwerty i only changed the setxkbmap setting back to the default: 
setxkbmap us

Maybe the application still has an issue with that. But even then, I don't think it straight up shouldn't work with other keyboard layouts.

**Comment by sahilyeole** [comment] 2023-11-08 22:38
I could not reproduce with AUR (1.2.3) on arch linux (X11). Colemak is working. Desktop -> linux is also working.
If you are on arch linux (wayland) let me know, and I'll check.

https://github.com/rustdesk/rustdesk/assets/73148455/ef91f57c-5142-4bf6-b310-e65e3e46234e

**Comment by MrMineDe** [comment] 2023-11-09 05:59
Hey, thanks for the response. maybe i got it wrong. The client who was broadcasting its screen was the phone, the controlling device the linux device. I tried to type with the linux device keyboard and that didnt work. Typing with the phone keyboard with the mouse as you seem to do work seemlessly for me too.

I will try with normal keyboard settings again later to see if colemak is even the problem.

**Comment by sahilyeole** [comment] 2023-11-09 07:30
Oh, ok. So physical keyboard linux -> android is not working.
We recently had this feature merged https://github.com/rustdesk/rustdesk/pull/6097.
Please try the latest nightly release.

**Closed** 2023-11-09 07:34 UTC
Labels: bug

**Comment by rustdesk** [comment] 2023-11-09 07:36
https://github.com/rustdesk/rustdesk/pull/6097

**Comment by MrMineDe** [comment] 2023-11-10 15:57
Hey, thanks for the help! Nightly solves the problem of not being able to write.
However, I am still unable to paste from Linux into android (normal text).
I thought this was also a feature of rustdesk. Am I mistaken there?

**Comment by sahilyeole** [comment] 2023-11-11 00:34
Yes, it's a feature but missing for now on a few environments.

**Comment by Magustructor** [comment] 2024-01-17 19:16
I don't know if here's the right place for reporting it but I have a problem with using keyboard in Windows 10 (R. ver.1.2.4)-> Android 11 (R. ver. 1.2.4) scenario.
The keyboard generally works properly except Enter key.
The Enter moves the cursor to the next line instead of confirming/accepting text when used in any search field like google.
I tried both legacy and translation modes.

Am I doing something incorrectly or it's a bug?
