### ISSUE TITLE
cannot type an underbar on JP keyboard

### ISSUE THREAD

**Issue by gloomy-lemon-debatable** [rustdesk/rustdesk#904] opened 2022-07-02 13:36 UTC
**Describe the bug you encountered:**
cannot type an underbar "\_" on JP keyboard
...
**What did you expect to happen instead?**
Typing shift+backslash "\\" always outputs bar "|" instead of underbar "\_"
Perhaps this may be due to the fact that the JPY symbol "¥" and backslash "\\" are treated as the same thing on JP keyboard
Please Take a look at these links:
[Wikipedia: Keyboard layout](https://en.wikipedia.org/wiki/Keyboard_layout#/media/File:KB_Japanese.svg)
[Why does backslash ('\\') look like ('¥') in Japanese and ('₩') in Korean systems?](https://www.quora.com/Why-does-backslash-look-like-in-Japanese-and-in-Korean-systems)
...

**How did you install `RustDesk`?**
simply installed from the official website

---

**RustDesk version and environment**
rustdesk-1.1.9-windows_x64

**Comment by rustdesk** [comment] 2022-07-02 13:52
Thanks!

**Comment by rustdesk** [comment] 2022-07-02 13:53
@asur4s

**Comment by asur4s** [comment] 2022-07-03 03:38
I reproduced the problem. Can you show your keyboard layout? Maybe this can help you. https://unix.stackexchange.com/questions/111624/how-to-display-the-current-keyboard-layout

Can you try typing backslashes directly in remote Linux? As far as I know, the backslash key is not supported on Linux(https://bugs.launchpad.net/ubuntu/+source/onboard/+bug/552425). I don't have a Japanese physical keyboard to test Ubuntu's bug.
@gloomy-lemon-debatable

**Comment by gloomy-lemon-debatable** [comment] 2022-07-03 09:05
Here's my jp106 keyboard layout exported by gkbd-keyboard-display:
![image](https://user-images.githubusercontent.com/91877885/177032530-a1b5ed80-ca69-4790-8911-4b87e65a84a1.png)
Although for some reason not shown, there's actually a JPY key to the left of the backspace key and a backslash key to the left of the right shift key; see [Wikipedia: Keyboard Layout](https://en.wikipedia.org/wiki/Keyboard_layout#/media/File:KB_Japanese.svg).

Both JPY key or backslash key seem to work fine in my environment (of course bar and underbar do).

**Comment by asur4s** [comment] 2022-07-03 09:09
Thanks, can you try the backslash to the left of shift again?

**Comment by gloomy-lemon-debatable** [comment] 2022-07-03 09:20
I apologize for my lack of understanding, but do you want me to try with RustDesk v1.1.9? If so, I regret to say it has not been fixed yet.

**Comment by asur4s** [comment] 2022-07-03 09:23
No, Input directly in remote Linux without rustdesk.  I don't have a Japanese physical keyboard to test.

**Comment by asur4s** [comment] 2022-07-03 09:28
> missing backslash-underscore key in Japanese layout -> https://bugs.launchpad.net/ubuntu/+source/onboard/+bug/552425

According to this bug, the combination of shift + \ => _ does not exist in ubuntu.

**Comment by gloomy-lemon-debatable** [comment] 2022-07-03 09:36
I get it now.
On linux, typing JPY key and backslash key by this keyboard outputs both as a backslash. However, when combined with the Shift key, JPY key outputs bar and backslash key does underbar.

**Comment by asur4s** [comment] 2022-07-03 09:44
Thanks for your help. I'll figure out a way to fix it.

**Comment by gloomy-lemon-debatable** [comment] 2022-07-03 09:48
I would appreciate it if you could fix it soon.
For other similar applications (AnyDesk, DWService, etc.), the output results were as expected, so it is probably a RustDesk specific issue.

**Comment by rustdesk** [comment] 2022-11-08 16:14
@gloomy-lemon-debatable could you please try out nightly build?

**Comment by aibou-kit** [comment] 2022-11-19 06:14
I used nightly 1.2.0 in map mode with a Japanese keyboard.
(I used nightly 1.2.0 for both remote and client computers).
In my case, typing “_” (shift + \ next to the right shift) outputs “>”.
Besides, I found some other wrong keyboard mappings.
- "\” next to the right shift outputs "<"
- "¥" next to the backspace outputs "]"
- "|" (shift + ¥ next to the backspace) outputs "}"

Remote OS: ubuntu 22.04
Client OS: windows 11

**Comment by rustdesk** [comment] 2022-11-19 06:15
Thanks for your report.

**Comment by rustdesk** [comment] 2022-11-23 16:39
#1547

**Comment by fufesou** [comment] 2023-01-05 03:59
@aibou-kit Hi, can you please try the nightly build, with "Map mode"? This issue should be fixed now.

<img width="235" alt="20230104201351" src="https://user-images.githubusercontent.com/13586388/210698984-6d95d7a3-c00a-4cb5-9694-2c335e14609e.png">

**Comment by fufesou** [comment] 2023-01-05 05:25
There's still some problems. I'll fix it soon.

**Comment by fufesou** [comment] 2023-01-05 05:50
@aibou-kit In my PCs, "Map mode" is Ok. The "Legacy mode" has some problems.

**Comment by aibou-kit** [comment] 2023-01-05 10:40
@fufesou
I tried nightly build now.
As you said, "Map mode" seems OK but "Legacy mode" has some problems.
On my PC, when using Rustdesk with “Legacy mode”, shift + ¥ outputs “_” instead of “|”.

By the way, I often fail to connect remote PC with the error “接続エラー 相手がリセットしました” in Japanese. 
Is this a known issue?
It might be my unique error, so I will try with another PC later.

**Comment by fufesou** [comment] 2023-01-07 02:02
> By the way, I often fail to connect the remote PC with the error “接続エラー 相手がリセットしました” ("reset by peer").
Is this a known issue?

@aibou-kit Hi, the message above means your rustdesk crashed on the remote side. What's your OS? If you can, please provide some infos, like the system log?

**Comment by aibou-kit** [comment] 2023-01-08 07:30
@fufesou 
My remote OS is ubuntu 22.04.
These are the log files just after the crash.
- "log.zip" contains log files under /var
- "logs.zip" contains log files under ~/.local/share/

[log.zip](https://github.com/rustdesk/rustdesk/files/10367898/log.zip)
[logs.zip](https://github.com/rustdesk/rustdesk/files/10367899/logs.zip)

**Comment by fufesou** [comment] 2023-01-08 10:42
@aibou-kit Thx.
I've downloaded the attached files.
Please delete the files to avoid leaking your private information.

**Comment by fufesou** [comment] 2023-01-08 11:08
Thanks for your helpful report.
I can see rustdesk crash once the connecting is established.
But it may take a little more time to find out the reason.

```
...
Jan  8 15:36:48 aibou-OptiPlex-7060 rustdesk.desktop[8501]: flutter: launch args: []
Jan  8 15:36:48 aibou-OptiPlex-7060 rustdesk.desktop[8501]: flutter: initializing FFI main
Jan  8 15:36:48 aibou-OptiPlex-7060 rustdesk.desktop[8501]: flutter: _appType:main,info1-id:324e052cab684cf69353a7a364f20f82,info2-name:Ubuntu,dir:/home/aibou/Documents
Jan  8 15:36:48 aibou-OptiPlex-7060 rustdesk.desktop[8501]: flutter: _globalFFI init
Jan  8 15:36:48 aibou-OptiPlex-7060 rustdesk.desktop[8501]: flutter: _globalFFI init end
Jan  8 15:36:48 aibou-OptiPlex-7060 rustdesk.desktop[8501]: flutter: registerEventHandler callback_query_onlines recent peer
Jan  8 15:36:48 aibou-OptiPlex-7060 rustdesk.desktop[8501]: flutter: registerEventHandler load_recent_peers recent peer
Jan  8 15:36:48 aibou-OptiPlex-7060 rustdesk.desktop[8501]: flutter: [MultiWindowHandler] active window changed: [0]
Jan  8 15:40:29 aibou-OptiPlex-7060 rustdesk[13232]: flutter: launch args: [--cm]
Jan  8 15:40:29 aibou-OptiPlex-7060 rustdesk[13232]: flutter: --cm started
Jan  8 15:40:29 aibou-OptiPlex-7060 rustdesk[13232]: flutter: initializing FFI main
Jan  8 15:40:29 aibou-OptiPlex-7060 rustdesk[13232]: flutter: _appType:main,info1-id:324e052cab684cf69353a7a364f20f82,info2-name:Ubuntu,dir:/home/aibou/Documents
Jan  8 15:40:29 aibou-OptiPlex-7060 rustdesk[13232]: flutter: _globalFFI init
Jan  8 15:40:29 aibou-OptiPlex-7060 rustdesk[13232]: flutter: _globalFFI init end
Jan  8 15:40:29 aibou-OptiPlex-7060 rustdesk[13232]: flutter: registerEventHandler theme theme
Jan  8 15:40:29 aibou-OptiPlex-7060 rustdesk[13232]: flutter: registerEventHandler language language
Jan  8 15:40:29 aibou-OptiPlex-7060 gnome-shell[2470]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a00003
Jan  8 15:40:29 aibou-OptiPlex-7060 kernel: [  678.106412] rustdesk[13232]: segfault at 0 ip 00007f3ef010a97d sp 00007ffe332ebc58 error 4 in libc.so.6[7f3eeff95000+195000]
Jan  8 15:40:29 aibou-OptiPlex-7060 kernel: [  678.106421] Code: f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 89 f8 48 89 fa c5 f9 ef c0 25 ff 0f 00 00 3d e0 0f 00 00 0f 87 33 01 00 00 <c5> fd 74 0f c5 fd d7 c1 85 c0 74 57 f3 0f bc c0 c5 f8 77 c3 66 66
Jan  8 15:40:29 aibou-OptiPlex-7060 gnome-shell[2470]: message repeated 2 times: [ Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2a00003]
Jan  8 15:40:29 aibou-OptiPlex-7060 systemd[1503]: Starting Notification regarding a crash report...
Jan  8 15:40:29 aibou-OptiPlex-7060 systemd[1]: Started crash report submission.
Jan  8 15:40:30 aibou-OptiPlex-7060 update-notifier-crash[13309]: /usr/bin/whoopsie
Jan  8 15:40:30 aibou-OptiPlex-7060 whoopsie[13306]: [15:40:30] Using lock path: /var/lock/whoopsie/lock
Jan  8 15:40:30 aibou-OptiPlex-7060 systemd[1]: whoopsie.service: Deactivated successfully.
Jan  8 15:40:30 aibou-OptiPlex-7060 systemd[1503]: Finished Notification regarding a crash report.
Jan  8 15:40:32 aibou-OptiPlex-7060 systemd[1503]: Starting Notification regarding a crash report...
Jan  8 15:40:32 aibou-OptiPlex-7060 systemd[1]: Started crash report submission.
Jan  8 15:40:32 aibou-OptiPlex-7060 update-notifier-crash[13378]: /usr/bin/whoopsie
Jan  8 15:40:32 aibou-OptiPlex-7060 whoopsie[13377]: [15:40:32] Using lock path: /var/lock/whoopsie/lock
Jan  8 15:40:32 aibou-OptiPlex-7060 systemd[1]: whoopsie.service: Deactivated successfully.
Jan  8 15:40:32 aibou-OptiPlex-7060 update-notifier-crash[13380]: rustdesk
Jan  8 15:40:33 aibou-OptiPlex-7060 systemd[1]: Started crash report submission.
Jan  8 15:40:34 aibou-OptiPlex-7060 whoopsie[13492]: [15:40:34] Using lock path: /var/lock/whoopsie/lock
Jan  8 15:40:34 aibou-OptiPlex-7060 systemd[1]: whoopsie.service: Deactivated successfully.
Jan  8 15:40:52 aibou-OptiPlex-7060 gnome-shell[2470]: Object .Gjs_ui_messageTray_Notification (0x5596fd699320), has been already disposed — impossible to emit any signal on it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Jan  8 15:40:52 aibou-OptiPlex-7060 gnome-shell[2470]: == Stack trace for context 0x5596fd0fd170 ==
Jan  8 15:40:52 aibou-OptiPlex-7060 gnome-shell[2470]: #0   55970384c198 i   resource:///org/gnome/shell/ui/messageTray.js:493 (30354ae51ec0 @ 69)
Jan  8 15:40:52 aibou-OptiPlex-7060 gnome-shell[2470]: #1   55970384c0f0 i   resource:///org/gnome/shell/ui/messageTray.js:489 (30354ae51e70 @ 56)
Jan  8 15:40:52 aibou-OptiPlex-7060 gnome-shell[2470]: #2   55970384c068 i   resource:///org/gnome/shell/ui/calendar.js:796 (30354ae5e0b0 @ 22)
Jan  8 15:40:52 aibou-OptiPlex-7060 gnome-shell[2470]: == Stack trace for context 0x5596fd0fd170 ==
Jan  8 15:40:52 aibou-OptiPlex-7060 gnome-shell[2470]: #0   55970384c198 i   resource:///org/gnome/shell/ui/messageTray.js:494 (30354ae51ec0 @ 84)
Jan  8 15:40:52 aibou-OptiPlex-7060 gnome-shell[2470]: #1   55970384c0f0 i   resource:///org/gnome/shell/ui/messageTray.js:489 (30354ae51e70 @ 56)
Jan  8 15:40:52 aibou-OptiPlex-7060 gnome-shell[2470]: #2   55970384c068 i   resource:///org/gnome/shell/ui/calendar.js:796 (30354ae5e0b0 @ 22)
Jan  8 15:40:52 aibou-OptiPlex-7060 gnome-shell[2470]: Object .Gjs_ui_messageTray_Notification (0x5596fd699320), has been already disposed — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
...
```

**Comment by fufesou** [comment] 2023-01-09 02:20
@aibou-kit Hi, can you please send me the crash file through an email (shuanglongchen@yeah.net) . Thx.

/var/crash/_usr_lib_rustdesk_rustdesk.1000.crash

```
Jan  8 16:04:28 aibou-OptiPlex-7060 whoopsie[44120]: [16:04:28] Parsing /var/crash/_usr_lib_rustdesk_rustdesk.1000.crash.
Jan  8 16:04:28 aibou-OptiPlex-7060 whoopsie[44120]: [16:04:28] Uploading /var/crash/_usr_lib_rustdesk_rustdesk.1000.crash.
Jan  8 16:04:28 aibou-OptiPlex-7060 systemd[1503]: update-notifier-crash.service: Unit process 44119 (sh) remains running after unit stopped.
Jan  8 16:04:28 aibou-OptiPlex-7060 systemd[1503]: update-notifier-crash.service: Unit process 44121 (rustdesk) remains running after unit stopped.
Jan  8 16:04:28 aibou-OptiPlex-7060 systemd[1503]: Finished Notification regarding a crash report.
Jan  8 16:04:28 aibou-OptiPlex-7060 systemd[1503]: update-notifier-crash.service: Consumed 39.416s CPU time.

```

**Comment by rustdesk** [comment] 2023-03-24 07:05
close since no response

**Closed by rustdesk** 2023-03-24 07:05 UTC
Labels: bug
