### ISSUE TITLE
[Bug] Prevents local printer installation after Rustdesk is installed

### ISSUE THREAD

**Issue by dasruralgeek** [rustdesk/rustdesk#3129] opened 2023-02-08 22:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

Operating System: KDE neon 5.26
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 5.19.0-17.2-liquorix-amd64 (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-7700 CPU @ 3.60GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630
Manufacturer: Dell Inc.
Product Name: OptiPlex 7050

Rustdesk Version 1.1.9  Prevents local printer installation after Rustdesk is installed. System will locate network printers. But wiil not allow printer database to load or manually browse PPD file. Issue effects both GUI printer interface and CUPS web interface. (localhost:631).  This may also effect Thunderbirds add account wizard. Does not effect printers installed prior to installing Rustdesk. 
Current workaround: Remove Rustdesk, install printer, reinstall Rustdesk.
also , Thunderbird account addition works normally when Rustdesk is removed  

Issue was also reproduced on Various HP laptops and desktops HP840G5, HP650G9, HP800G1AiO

### How to Reproduce

Rustdesk Version 1.1.9  Prevents local printer installation after Rustdesk is installed. System will locate network printers. But wiil not allow printer database to load or manually browse PPD file. Issue effects both GUI printer interface and CUPS web interface. (localhost:631).  This may also effect Thunderbirds add account wizard. Does not effect printers installed prior to installing Rustdesk. 

### Expected Behavior

System will locate network printers. But wiil not allow printer database to load or manually browse PPD file. Issue effects both GUI printer interface and CUPS web interface. (localhost:631). 

### Operating system(s) on local side and remote side

Linux to Linux 

### RustDesk Version(s) on local side and remote side

1.1.9-1.1.9

### Additional Context

Current workaround: Remove Rustdesk, install printer, reinstall Rustdesk.

**Comment by rustdesk** [comment] 2023-02-09 01:06
Sadly, totally no clue yet.

**Comment by Kundanagrawalofficial** [comment] 2023-02-11 00:35
Ok will try on it if you give me chance

**Comment by DeCiZoR** [comment] 2023-02-16 15:51
I have reproduced same bug with:
**Ubuntu 22.04 JAMMY** 
(gnome-shell 42.5)
on many computers or virtual machines (virtualbox).

When i try to add a new printer with **/usr/share/system-config-printer/system-config-printer.py**   (gnome's default advanced printer tool), it finds local or network printers but cannot show us PPD choice window.   

Debug mode :
```
/usr/share/system-config-printer/system-config-printer.py --debug
```


**"lpinfo -m"** command should list availables PPDs but only returning :
```
lpinfo: Success
```

For information, "system-config-printer.py" calls **"/usr/lib/cups/driver/driverless"** which calls **"/usr/bin/ippfind"** with these parameters:
```
-T 0 _ipps._tcp _ipp._tcp ! --txt printer-type --and ( --txt-pdl image/pwg-raster --or --txt-pdl application/PCLm --or --txt-pdl image/urf --or --txt-pdl application/pdf ) -x echo -en {service_scheme} {service_name} {service_domain} {txt_usb_MFG} {txt_usb_MDL} {txt_product} {txt_ty} {txt_pdl} {txt_UUID} {txt_rfo} ;
```
"**-T 0**" means no timeout whereas a 3sec timeout was configured under Ubuntu 20.04.

With another tests: 
```
strace -s 1000 -f /usr/bin/ippfind -T 0 _ipps._tcp _ipp._tcp ! --txt printer-type --and \( --txt-pdl image/pwg-raster --or --txt-pdl application/PCLm --or --txt-pdl image/urf --or --txt-pdl application/pdf \) -x echo -en {service_scheme} {service_name} {service_domain} {txt_usb_MFG} {txt_usb_MDL} {txt_product} {txt_ty} {txt_pdl} {txt_UUID} {txt_rfo} \;
```
i found that **"ippfind"** makes call to DBUS /org/freedesktop/DBUS org.freedesktop.DBus


So many hypothesis were tested/debugged and finally i found it was rustdesk's service fault.   
When it is running, rustdesk systemd service is flooding DBUS system bus. You can show that with :
```
sudo dbus-monitor --system
```
If we stop rustdesk service, DBUS flood stops immediately and we can add a printer without any bug.
And now **"lpinfo -m"** command can return us availables PPDs for printers.

Maybe rustdesk service needs a pause/sleep between every DBUS calls but i dont know how.

Thank you for your attention.

**Comment by rustdesk** [comment] 2023-02-17 01:33
@fufesou take a look. check out who are doing  this unnessary dbus call when no connection.

**Comment by rustdesk** [comment] 2023-02-17 01:34
@DeCiZoR Thank you very much.

**Comment by rustdesk** [comment] 2023-02-17 02:06
1.1.9 does not have explicit dbus call. Wierd.

**Comment by rustdesk** [comment] 2023-02-17 02:08
> DBUS flood stops

Do you know what dbus function is called by rustdesk service?

**Comment by rustdesk** [comment] 2023-02-17 15:18
How often the dbus is called?

**Comment by rustdesk** [comment] 2023-02-17 15:23
https://github.com/rustdesk/rustdesk/blob/cbf0c4863b9451ffb087491a2967804bb65f00c7/src/platform/linux.rs#L287
some function here calls dbus repeatly.

**Comment by DeCiZoR** [comment] 2023-02-17 16:21
> How often the dbus is called?

i count more than 600 DBUS connections in 60sec.

**Comment by rustdesk** [comment] 2023-02-18 00:55
> i count more than 600 DBUS connections in 60sec.

how to count?

**Comment by DeCiZoR** [comment] 2023-02-20 10:02
> > i count more than 600 DBUS connections in 60sec.
> 
> how to count?

```
systemctl stop rustdesk
timeout 60 strace -s 1000 -f /usr/bin/rustdesk --service >/tmp/strace.log 2>&1
grep -cE " connect\(.*/run/dbus/system_bus_socket" /tmp/strace.log
```

**Comment by tatavignot** [comment] 2023-02-24 09:47
After modifying **SERVICE_INTERNAL** constant value from 300 to 3000, it seems to resolve the bug. I'm now able to add a local printer, "CUPS PDF Reader" in my case.

Using @DeCiZoR count method:

`systemctl stop rustdesk`
`timeout 60 strace -s 1000 -f /usr/bin/rustdesk --service >/tmp/strace.log 2>&1`
`grep -cE " connect\(.*/run/dbus/system_bus_socket" /tmp/strace.log`

I go from **522** DBUS connections in 60sec to **97** DBUS connections.

I've also check an eventual performance degradation but I've nothing to report regarding that.

**Comment by rustdesk** [comment] 2023-02-24 10:18
@fufesou check what is calling dbus in the loop.

**Comment by chiehw** [comment] 2023-03-01 06:21
@rustdesk 

`get_display_server` is used to detemine whether the current system is x11 or wayland

https://github.com/rustdesk/rustdesk/blob/846948985d55888341575506938ef88d42ecd5c3/libs/hbb_common/src/platform/linux.rs#L30

`get_display_server` use `loginctl`, `loginctl` is based on DBUS

![image](https://user-images.githubusercontent.com/99897242/222059579-b2b9931d-8b99-450a-bc2a-692c330f675a.png)

Some service will keep calling `get_display_server`, Cause dbus to be called frequently. Are there any better alternatives to loginctl?

**Comment by rustdesk** [comment] 2023-03-01 12:56
@


> After modifying **SERVICE_INTERNAL** constant value from 300 to 3000, it seems to resolve the bug. I'm now able to add a local printer, "CUPS-PDF-Printer" in my case.
> 
> Using @DeCiZoR count method:
> 
> `systemctl stop rustdesk` `timeout 60 strace -s 1000 -f /usr/bin/rustdesk --service >/tmp/strace.log 2>&1` `grep -cE " connect\(.*/run/dbus/system_bus_socket" /tmp/strace.log`
> 
> I go from **522** DBUS connections in 60sec to **97** DBUS connections.
> 
> I've also check an eventual performance degradation but I've nothing to report regarding that.

@fufesou we have to refactor the loop to reduce the dbus calling by comparing uid change first.

**Comment by tatavignot** [comment] 2023-03-13 16:06
@chiehw Will your pull request be merged sometimes ? I see it's closed at the time ? Why is that ?

**Comment by rustdesk** [comment] 2023-03-13 16:23
It's buggy.

**Comment by Spheerys** [comment] 2023-03-14 16:32
I have the same issue with Linux Mint 21.1.
I can't add printer if Rust is installed

**Comment by rustdesk** [comment] 2023-03-19 12:09
Please try it out tomorrow.

**Comment by tatavignot** [comment] 2023-03-19 13:39
Will do !

**Comment by dasruralgeek** [comment] 2023-03-27 03:20
Thank you for all the work on this issue. Sadly the issue is not completely fixed. I just loaded the nightly build (Version: 1.2.0 - Build Date: 2023-03-27 00:21) on my machine.  Indeed local install now appears to work correctly. I was able to access the printer database without error. However if I attempt to remotely install a printer the local device still produces the database error as originally reported.

**Comment by rustdesk** [comment] 2023-04-25 01:52
> However if I attempt to remotely install a printer the local device still produces the database error as originally reported.

Frankly, we wont test this for you. Looking for contributors for this this.

**Comment by sahilyeole** [comment] 2023-09-04 16:58
Yes, https://github.com/rustdesk/rustdesk/pull/5276/commits/ebfebdffa7a23c66f7aa508f9fb02e0dedb7acc5 is causing more calls to `loginctl` than before.

I did that to ensure the active user is also a seat0 value, in order to fix the login issue some users were facing on restarting linux machine.
Didn't know it could cause other problems.

Earlier, in the scenario where the `refresh()` has to be skipped(return) there was only one call to `loginctl` due to `isactive()`.
Now in the same scenario, there are two calls to `loginctl`, from `isactive()` and `get_values_of_seat0()`.

I can try to fix it by combining `isactive()` and `get_values_of_seat0()` into separate function only for this, so that it makes only one call to `loginctl`.

**Closed** 2023-12-03 03:39 UTC
Labels: help wanted
