### ISSUE TITLE
Flatpak from nightly crashes. 

### ISSUE THREAD

**Issue by VarLad** [rustdesk/rustdesk#2439] opened 2022-12-03 18:49 UTC
**Describe the bug you encountered:**
Rustdesk crashes with:
```
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:1cfccb96d2f1465b9d473dbb94cad7d4,info2-name:Freedesktop.org,dir:/var/home/username/Documents
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: window position saved, but cannot be parsed
```

**How did you install `RustDesk`?**

Via Flatpak from nightly build.

**RustDesk version and environment**

1.2.0
Fedora 37 SilverBlue GNOME, got the flatpak from nightly and installed via `flatpak install`
Run with `flatpak run org.rustdesk.rustdesk`

**Comment by rustdesk** [comment] 2022-12-04 01:40
@Kingtous

**Comment by DrSchnagels** [comment] 2022-12-05 15:12
It also makes Discovery app crash after installing it via flatpak install on the Steam Deck

**Comment by Kingtous** [comment] 2022-12-06 15:15
> It also makes Discovery app crash after installing it via flatpak install on the Steam Deck

Let's check the problem. Thanks for the reply.

**Comment by Kingtous** [comment] 2022-12-08 07:33
I cannot reproduce it on KDE plasma 5.25 + Manjaro unstable. Are u using x11 or wayland?

![image](https://user-images.githubusercontent.com/39793325/206386244-266b8d6a-a891-409d-9359-4c641033750d.png)

**Comment by VarLad** [comment] 2022-12-08 09:18
@Kingtous GNOME 43 Wayland. Although I can tell you about Plasma Wayland in a minute

**Comment by Kingtous** [comment] 2022-12-08 09:36
> 

I'm preparing a patch for the display server detection, where the previous code is not working in flatpack sandbox before. The artifacts is building here. https://github.com/Kingtous/rustdesk/actions/runs/3647024411

Once it done (about 30minutes), u can download patched flatpak package

https://github.com/Kingtous/rustdesk/releases/tag/nightly

 and test whether it resolves this issue. : )

**Comment by Kingtous** [comment] 2022-12-08 09:37
> 

Pretty new GNOME version...
Can u test in GNOME 43 classic (x11) too?  :)

**Comment by VarLad** [comment] 2022-12-08 21:54
@Kingtous It works with GNOME 43 X11. But I still get this when I run it in Wayland:

```
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:1cfccb96d2f1465b9d473dbb94cad7d4,info2-name:Freedesktop.org,dir:$HOME/Documents
flutter: _globalFFI init
flutter: _globalFFI init end
thread '<unnamed>' panicked at '[-] grab error in rdev: MissingDisplayError', /root/.cargo/git/checkouts/rdev-a53ad59d4a4a3444/4051761/src/linux/grab.rs:177:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Any reason why its just printing the path to my Documents folder to the log?

**Comment by Kingtous** [comment] 2022-12-09 00:08
> @Kingtous It works with GNOME 43 X11. But I still get this when I run it in Wayland:
> 
> ```
> flutter: launch args: []
> flutter: initializing FFI main
> flutter: _appType:main,info1-id:1cfccb96d2f1465b9d473dbb94cad7d4,info2-name:Freedesktop.org,dir:$HOME/Documents
> flutter: _globalFFI init
> flutter: _globalFFI init end
> thread '<unnamed>' panicked at '[-] grab error in rdev: MissingDisplayError', /root/.cargo/git/checkouts/rdev-a53ad59d4a4a3444/4051761/src/linux/grab.rs:177:13
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Any reason why its just printing the path to my Documents folder to the log?

this error had been fixed by a more recently commit. please wait for nightly build in this official repo. thanks.

**Closed** 2023-02-01 07:33 UTC
Labels: bug
