### ISSUE TITLE
RustDeskIddDriver not installed automatically （failed to install driver sometimes)

### ISSUE THREAD

**Issue by davidebeatrici** [rustdesk/rustdesk#4597] opened 2023-06-09 08:19 UTC
### Bug Description

Problem:

The remote setup consists in a Windows 11 virtual machine with an Nvidia Tesla M40 passed through it.

If I leave the SPICE interface with the corresponding virtual GPU enabled, the remote desktop experience is excellent, aside from the lack of 3D acceleration.

However, if I leave only the dedicated GPU the entire RustDesk session becomes extremely slow, to the point that the remote system seems frozen. It even takes a very long time to connect and sometimes goes into timeout or throws an error.

---

Solution:

Setting the SPICE display resolution to 640x480 (in order for the virtual display adapter to show up) and installing the corresponding driver in Device Manager fixes the issue.

### How to Reproduce

Install RustDesk when at least one display is present and with a resolution equal or higher to 800x600 (#4560).

### Expected Behavior

The driver should be installed automatically, so that Windows finds it when the virtual display adapter shows up.

### Operating system(s) on local side and remote side

Any -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.0 -> 1.2.0

### Screenshots

![](https://github.com/rustdesk/rustdesk/assets/5897523/8562a9ba-5878-48c0-9c70-a5350808ffa3)

**Comment by rustdesk** [comment] 2023-06-09 08:24
no idea what you are saying.

**Comment by rustdesk** [comment] 2023-06-09 08:25
what is `automatically`?

**Comment by davidebeatrici** [comment] 2023-06-09 08:27
The driver should be installed along with RustDesk. It can be done even if the device is not available yet.

**Comment by rustdesk** [comment] 2023-06-09 08:28
idddriver is installed with RustDesk, but if starting the virtual display depends on https://github.com/rustdesk/rustdesk/issues/4359#issuecomment-1582338893

**Comment by davidebeatrici** [comment] 2023-06-09 08:31
In my case it was not installed... I had to do it myself in Device Manager. The device was there but had the yellow exclamation mark next to it due to no driver present.

**Comment by rustdesk** [comment] 2023-06-09 08:33
we only install the cert, the driver will be installed when starting virtual display.

@fufesou  please correct me.

**Comment by davidebeatrici** [comment] 2023-06-09 08:34
I can confirm the cert was installed as the digital signature is recognized.

**Comment by rustdesk** [comment] 2023-06-09 08:36
We have no plan to install it automatically for the time being. But we will consider this together with https://github.com/rustdesk/rustdesk/issues/4359#issuecomment-1582338893 together in the future.

**Comment by davidebeatrici** [comment] 2023-06-09 08:40
Alright, no problem.

**Comment by rustdesk** [comment] 2023-06-09 08:40
> However, if I leave only the dedicated GPU the entire RustDesk session becomes extremely slow

https://github.com/rustdesk/rustdesk/issues/3434

**Comment by rustdesk** [comment] 2023-06-09 08:42
@fufesou why don't we install the driver together with the cert?

**Comment by fufesou** [comment] 2023-06-09 08:42
> In my case it was not installed... I had to do it myself in Device Manager. The device was there but had the yellow exclamation mark next to it due to no driver present.

During my testing, this problem happened occasionally. I don't know why the driver is not installed. It may be related to the way Windows trusts certificates.

**Comment by rustdesk** [comment] 2023-06-09 09:02
> In my case it was not installed... I had to do it myself in Device Manager. The device was there but had the yellow exclamation mark next to it due to no driver present.

@fufesou just confirmed we had this issue sometimes (automatically install driver / device while starting virtual display), have to manually install.

**Comment by davidebeatrici** [comment] 2023-06-09 09:14
> @davidebeatrici Do you need to manually confirm every time you start a virtual display?

Nope, everything's working flawlessly even after rebooting and the resolution is fixed.

I'm also not experiencing #3434 with any codecs.

**Comment by dignow** [comment] 2023-07-02 06:18
There is currently no thinking or progress on this issue.

Running the command below seems to work without issue.

```
.\CertMgr.exe /add RustDeskIddDriver.cer /s /r localMachine root
```

But what this command does is also add to the registry and the system's certificate cache.

When the Windows system uses a certificate, it will first search the certificate cache, and if it cannot find it in the cache, it will look in the registry.

I don't think caching is the cause of the yellow exclamation mark failure.

**Closed** 2023-07-03 12:50 UTC
Labels: bug
