### ISSUE TITLE
Keyboard not working on M2 Mac （some hibernations maybe）

### ISSUE THREAD

**Issue by chris-only** [rustdesk/rustdesk#6357] opened 2023-11-09 20:13 UTC
### Bug Description

Keyboard stops working after some successful sessions and wont come back until restart of the Mac.

### How to Reproduce

Just do some sessions, your other daily work, some hibernations maybe and the keyboard will stop working in remote sessions :(

### Expected Behavior

Keyboard should work all the time

### Operating system(s) on local side and remote side

MacOS Sonoma 14.1

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

not needed

### Additional Context

My Mac is a M2 version and i use rustdesk arm64

**Comment by rustdesk** [comment] 2023-11-11 11:24
@sahilyeole please help confirm

**Comment by sahilyeole** [comment] 2023-11-11 12:23
I tried 20, 10, and 5 minute sessions. This issue did not occur.
@chris-only Can you please tell the approx duration and frequency of the sessions? Also, does the mouse work when this issue occurs?

**Comment by chris-only** [comment] 2023-11-11 12:42
Thanks for your work!

I cant tell a duration, but i´ll try to measure it.
The mouse works fine, i can send crtl-alt-del command but i cannot type a password.

Unfortunately i only have windows clients and servers to connect to :(

Do you think rustdesk could interfere with other software? Networking related software on my mac is anydesk, wireguard, tailscale, UTM and VMWare Fusion

**Comment by sahilyeole** [comment] 2023-11-11 22:40
I just now tested 3 hrs of session but this issue did not occur.

>Do you think rustdesk could interfere with other software? Networking related software on my mac is anydesk, wireguard, tailscale, UTM and VMWare Fusion

No, I don't think it should.

On a side note, please check if this issue persists when rustdesk is uninstalled. I'm asking because it reminds me of an issue I had with my MBA M1 a few months ago. My keyboard stopped working after a few hours of normal use or when I put it to sleep. The mouse was working, but the keyboard only started working again when I restarted mac. It turned out to be a hardware issue.

**Comment by sahilyeole** [comment] 2023-11-12 08:37
Duplicate of #6335

**Comment by rustdesk** [comment] 2023-11-12 13:19
close as duplicate

**Closed by rustdesk** 2023-11-12 13:19 UTC
Labels: bug, duplicate
