### ISSUE TITLE
Excel copy cancels itself

### ISSUE THREAD

**Issue by jacoblockett** [rustdesk/rustdesk#3952] opened 2023-04-06 18:54 UTC
### Bug Description

When trying to copy and paste in Excel, the copy event seems to cancel itself the first time a new cell/group of cells is selected and copied. Here's a video:

https://user-images.githubusercontent.com/24402122/230468172-f1dcd444-c37f-4b11-b8c4-d95a16f7ea6b.mp4

At first, this was happening indefinitely and I couldn't find a rhyme or reason. I tried every combination of disabling/re-enabling clipboard, restarting both machines, and restarting both rustdesk clients. Some combination seemed to work yesterday and I thought it was fixed but then it started happening again. While I was creating the video above, I seemed to have isolated at least one scenario where it's consistent - if the clipboard has anything copied on it currently, the Excel copy will fail on the first attempt, but succeed on subsequent attempts. If there's nothing on the clipboard, it works from scratch, and pressing Esc (clear clipboard in Excel) and then copying also succeeds.

### How to Reproduce

Follow the above video

### Expected Behavior

Copy event fires properly and copies to clipboard of both machines.

### Operating system(s) on local side and remote side

Windows 11 -> Windows 10

### RustDesk Version(s) on local side and remote side

Nightly -> Nightly

### Screenshots

See above

### Additional Context

Copy operations worked perfectly in the 1.1.9 release, but not nightly

**Comment by rustdesk** [comment] 2023-04-07 00:56
@fufesou i have done manu job for clipboard sync in 1.1.9, obviously those are broken in nightly.

**Comment by rustdesk** [comment] 2023-04-07 01:56
https://github.com/rustdesk/rustdesk/commit/d825d30e53c6916c71dda69ab38c174b4ea88869

**Comment by fufesou** [comment] 2023-04-07 10:21
> clipboard initial sync

A --> B


Before conn:
"AA" in A's clipboard.
"BB" in B's clipboard.

After conn:

1. If A press `Ctrl + V` first, then B press `Ctrl + V`. Both "BB" are printed.
2. If B press `Ctrl + V` first, then A press `Ctrl + V`. Both "AA" are printed.

**Comment by rustdesk** [comment] 2023-04-07 10:57
> * If A press `Ctrl + V` first, then B press `Ctrl + V`. Both "BB" are printed.
> * If B press `Ctrl + V` first, then A press `Ctrl + V`. Both "AA" are printed.

Wrong then

**Comment by rustdesk** [comment] 2023-04-07 10:58
Anyway, clipboard initial sync is another issue, may have nothing to do with this issue.

**Comment by fufesou** [comment] 2023-04-07 14:53
@jacoblockett Hi, thanks for your feedback. 

But I cann't understand what issue you've methioned.

Is the following steps the same to you?

I've established a connection. All operations are on the remote side.

https://user-images.githubusercontent.com/13586388/230629153-c167ae7c-9ad3-4cbc-98e6-bd9f1eefee5a.mp4

**Comment by rustdesk** [comment] 2023-04-07 15:16
i think if you can make clipboard syncing perfectly birectionally, this issue can be solved.

**Comment by fufesou** [comment] 2023-04-07 15:30
> i think if you can make clipboard syncing perfectly birectionally as 1.1.9, this issue can be solved.

OK, I'll fix the synchronization first.

**Comment by jacoblockett** [comment] 2023-04-07 16:56
Hey, @fufesou

Yeah, I see what you're doing. So I've done a bit more testing on this issue in the meantime and I've come to find it's actually a lot more specific than I originally thought. Typically I'm copying values from one excel workbook to another, and in order to paste those values, I rely on "paste values" rather than just "paste" or "paste formatting", etc. To achieve this, you'd go into the context menu and choose "paste values" in the paste menu. So it turns out the data is in the clipboard, but Excel is not recognizing it as it's own "virtual" clipboard? I guess. Here's what I'm talking about:

https://user-images.githubusercontent.com/24402122/230647446-b3f9350b-47f4-405b-9ea3-d9acb22b4f92.mp4

As you can see, the first operation works as intended (as long as nothing was on the clipboard to begin with). After the first operation, the data copied is added to the clipboard but you lose all of the paste operations that Excel provides. Sorry, didn't realize this issue was so granular until recently. Let me know if you need more!

**Comment by fufesou** [comment] 2023-04-09 07:27
Thanks. I can reproduce your issue.

1.1.9 also works fine for me.

I'll try to find the differences.

**Comment by rustdesk** [comment] 2023-04-09 14:49
> > * If A press `Ctrl + V` first, then B press `Ctrl + V`. Both "BB" are printed.
> > * If B press `Ctrl + V` first, then A press `Ctrl + V`. Both "AA" are printed.
> 
> mstc: do the second，do nothing for the first one anydesk: do nothing both

After discussion, since initial sync in nightly is buggy (sometimes works, sometimes not), we decide to follow 1.1.9 behavior rather than mstc behavior.

**Comment by rustdesk** [comment] 2023-04-10 09:29
close since fix merged

**Closed by rustdesk** 2023-04-10 09:29 UTC
Labels: bug

**Comment by jacoblockett** [comment] 2023-04-10 13:55
> @jacoblockett Can you please try the next nightly build? This issue should be fixed.

Excellent, it has been fixed for me as well with this update. Thanks for looking into that! I'll pop back in if anything related comes up.

**Comment by GrupoBure** [comment] 2026-08-15 18:18
Please excuse me for necroing this post, but I’m having this issue with version 1.4.9.

In the latest versions, this has become a huge problem. Whether I’m connected remotely or not, as long as RustDesk is open, the clipboard fails constantly.

I have two PCs at home, and they are connected through RustDesk. If I have Excel open on both PCs, sometimes whatever I copy on one PC ends up being pasted into the Excel file on the other PC.

And when I’m only using Excel on one PC, I’ll copy something and the clipboard operation gets canceled. I have to copy it several times until, suddenly, it works. The same thing happens when copying something from the remote PC sometimes it copies correctly and sometimes it doesn’t.

I’ve tried pretty much everything in the settings, but nothing seems to work. I’m not sure what else I can do or how to fix this.
