### ISSUE TITLE
The main interface cannot be displayed when using multiple monitors

### ISSUE THREAD

**Issue by SamGenTLEManKaka** [rustdesk/rustdesk#6223] opened 2023-10-30 08:26 UTC
### Bug Description

My laptop has an extended monitor, (the laptop's monitor is the main monitor) I open rustdesk's main interface on the extended monitor and remote others, then I finish remotely shutting down the software, I unplug the extended monitor and just use the laptop's Monitor, when I open the rustdesk software at this time, the main interface cannot be displayed on the main screen of the laptop. I guess it should be opened on the non-existent extended monitor.

### How to Reproduce

Exiting rustdesk on the extended monitor, then unplugging the extended monitor and running the rustdesk software again can reproduce the problem stably.

### Expected Behavior

When it runs again, it should correctly identify the monitor status and open it on the correct monitor.

### Operating system(s) on local side and remote side

windwos10

### RustDesk Version(s) on local side and remote side

1.2.3

### Screenshots

none

**Comment by rustdesk** [comment] 2023-10-30 08:34
@fufesou

**Comment by fufesou** [comment] 2023-10-30 09:01
@SamGenTLEManKaka Thanks for your feedback.

But I cannot reproduce this issue.

Can you please give some screenshots of the display settings before and after you unplugging the extended monitor? Thx

**Comment by SamGenTLEManKaka** [comment] 2023-10-31 01:28
@fufesou 
Thanks for the reply!
I have found many computers that can reproduce this problem stably.
And if I want to really see the main interface of the software running, I have to plug the extended monitor back in, otherwise I can't use the software.
Here is a screenshot of my configuration
![img_v2_216f8925-7b7d-4a3c-8fe0-2e28c4b9e9eg](https://github.com/rustdesk/rustdesk/assets/24671601/7014ca8c-e3f6-4239-9130-4b751b0cca6c)
![img_v2_9e6d6d69-8d72-40c8-9d62-2cf10340993g](https://github.com/rustdesk/rustdesk/assets/24671601/918f22f9-ed06-4e02-9dfe-bf6756337225)

**Comment by fufesou** [comment] 2023-10-31 06:58
Thanks for your kind reply.

> i use sciter not flutter

It must be the reason. We did not handle the position well in sciter version.
I'll try fix it.

**Comment by DMSnz** [comment] 2023-10-31 20:28
In the mean time until a fix is out, what happens if you hover over the taskbar icon (dont click), once the preview window shows RustDesk, RIGHT click and say maximise or restore, does that flick it back to laptop monitor?
May not work but we had a weird similar bug in a program we use, this was how we got around it.

**Comment by SamGenTLEManKaka** [comment] 2023-11-01 02:01
> In the mean time until a fix is out, what happens if you hover over the taskbar icon (dont click), once the preview window shows RustDesk, RIGHT click and say maximise or restore, does that flick it back to laptop monitor? May not work but we had a weird similar bug in a program we use, this was how we got around it.

Thanks for the reply!
Your approach can solve the problem!

**Comment by fufesou** [comment] 2023-11-02 10:02
Getting the visible area of the screens requires some extra work.

This issue is not high priority.

1. This issue is not a common one.
2. We are currently working on the flutter version.

I will deal with it if more people give feedback.

**Comment by rustdesk** [comment] 2023-11-02 10:09
Agree

**Comment by SpikySpam** [comment] 2023-11-03 18:26
Hi,

I have the same on my setup (_like in the screenshot_). It's:

- **Left**: 3840*2160 at 225%
- **Right**: 5120*1440 at 100%

![rustdesk](https://github.com/rustdesk/rustdesk/assets/89944977/995873d2-f735-47ed-b245-709f283908e5)

Sometimes I can see a corner (when I did close the app on the left monitor), but it's completely gone when I close the app on the right (completely to the far right).

PS.:
I can't fit a bigger monitor on my desk 😂
Almost got it to work on my side.
Thanks!

**Comment by rustdesk** [comment] 2023-12-03 03:35
> PS: i use sciter not flutter

@SamGenTLEManKaka could you try flutter version?

**Comment by AlcorSystem** [comment] 2023-12-13 23:31
Same for us, dual monitor, the main GUI goes offscreen...
Now is totally usable, is there a tweak to overcome this ?

**Comment by PotatoYummy** [comment] 2024-01-24 03:36
不知是否是同一个问题，小米笔记本外接扩展屏，成功安装rustdesk，配置了自己的中继服务器，第一天正常使用。第二天程序打不开了，启动的时候一直闪退。尝试卸载重装，结果安装包也闪退
Windows 10 家庭中文版，rustdesk-1.2.3-x86_64.exe

**Comment by rustdesk** [comment] 2024-02-15 07:38
No idea if this can help.


https://answers.microsoft.com/en-us/windows/forum/all/program-open-in-task-bar-but-not-visible-on-screen/ef424c12-5f57-46eb-bb81-66563e284050
Or try modify %APPDATA%\RustDesk\config\RustDesk_local.toml by removing the line starting with wm_Main.

**Comment by rustdesk** [comment] 2024-02-15 07:41
solutions
- [ ] when storing postion, check postion against display coordinates, if it make sense, restore, otherwise use default pos.
- [ ] saving displays information also, when restoring check if can match

**Comment by NewEraCracker** [comment] 2024-02-25 14:53
I am having the exact same problem, but with the accept connection window.

I need to go trough hops like couple of WIN+D (to desktop, out of desktop), ALT+SPACE to bring context menu, and then restore, move or WIN+UP_ARROW to maximize.

Some helpful links:
https://superuser.com/questions/53585/how-to-move-windows-that-open-up-offscreen
https://superuser.com/questions/1099093/move-off-screen-window-back-to-screen-on-windows-10
https://superuser.com/questions/1267176/recover-windows-10-opening-off-screen

Please improve these mechanisms.

**Comment by rustdesk** [comment] 2024-05-20 08:42
I think this https://github.com/rustdesk/rustdesk/pull/8075 fix the problem, please verify.

**Comment by clavelm** [comment] 2024-08-23 14:11
I had a very similar problem today.
I’m on RustDesk x64 1.3.0, just updated from 1.2.7.

I’m on windows 10 with 2 monitors.
Monitor 1 is my laptop’s, monitor 2 is an external one.
I’m in extended projection.
My main display is the 1 (it’s the display where the icons near the clock in the taskbar are visible).

Last time I used RustDesk 1.2.7, I had display 1 on the left and display 2 on the right.
RustDesk windows was on display 2.
![2024 08 23 160443 - ApplicationFrameHost](https://github.com/user-attachments/assets/1adea966-dfc6-40cf-b5d5-b69d214518ee)

Since then, I’ve physically changed my monitors location.
I’m still in extended projection, but with display 2 on the left of display 1.
Display one is still the main one.

When I launched RustDesk 1.3.0 after update, the window was not visible.
I did not try https://github.com/rustdesk/rustdesk/issues/6223#issuecomment-1787984126 as I’ve fixed the problem before coming here to report the issue.
![2024 08 23 160428 - ApplicationFrameHost](https://github.com/user-attachments/assets/2e2d3aee-056d-400b-9633-87f50a1d9dbb)


I’ve found the RustDesk window by putting back display 2 on the right of display 1 in Windows display settings.
RustDesk window was then visible on display 2, I’ve moved it on display 1 and put back my displays as before.

**Comment by fufesou** [comment] 2024-10-30 02:42
@clavelm Hi, thanks for your feedback.

I tried your steps, but failed to reproduce your issue. Could you please tell me what I was missing?

https://github.com/user-attachments/assets/6fdb307e-5572-42bd-9398-d5e08b7961e4

I also read the code, RustDesk has a check and guarantee that it will show in the visible screens.

https://github.com/rustdesk/rustdesk/blob/415d2c5c60a309f4b869452366acfbf19e75fca7/flutter/lib/common.dart#L1821

It will restore window in the main monitor center if the previous save position is in current invisible area.


Could you please also reproduce this issue and give more clues? Thanks!

Just run the executable in the command line
```
installed: "C:\Program Files\RustDesk\rustdesk.exe" | more
non-installed: "%localappdata%\rustdesk\rustdesk.exe" | more
```

Please paste the `restore lpos` line here when the offset is not correct, thanks.

<img width="650" alt="image" src="https://github.com/user-attachments/assets/61978853-959a-40f0-8f13-522f12ae068a">

**Comment by clavelm** [comment] 2024-10-30 12:52
@fufesou Hi,
I’m now on rustdesk-1.3.2-x86_64.exe and I can still reproduce the behavior on my system.

```
flutter: restore lpos: 800.0/600.0, offset:2327.5/169.5, devicePixelRatio:2.5, isMaximized: false, isFullscreen: false
flutter: restore new offset: 2327.5/169.5, scale:1.0
```

I did some tries to pinpoint a way to reproduce.

1. It’s only doing it when the app was closed on the secondary display arranged on the right of the main one, and re-launched once that secondary display was arranged on the left. (The app is somewhere outside on the right, because when I trigger the minimization from the task bar, there is an animation done by Windows that clearly come from the right.)

    If the app was closed on the secondary display arranged on the left of the main and re-launched once that secondary display was rearranged on the right, the app screen is shown on the main display
    
    ![1](https://github.com/user-attachments/assets/b6276a7f-d223-4cbb-b344-a313ed25b886)
    ![2](https://github.com/user-attachments/assets/cda0760f-58ea-409f-baac-f1c5f422fa50)

2. It’s not doing it if the app was closed while maximized, but maybe it’s because of something else.

    When I close rustdesk maximized and re-launch it without changing my displays, it’s still maximized, but with some pixels visible of the border visible on the other screen and maybe it prevents to trigger the behavior.
    I think it’s a bug from Windows’ display because I’m getting it from other apps from time to time.

    ![3](https://github.com/user-attachments/assets/6fbe3e41-c671-47d1-ba83-1fd18e3db5cf)


I’ve just learnt of the key combination to move an app window between displays: windows key + shift + left/right, and it can be used to move the rustdesk window back on a display.
Rearranging the displays also bring the window back on the right secondary display, and rearranging back keeps it visible.

**Comment by fufesou** [comment] 2024-10-30 13:01
Thank you very much for your testing, detailed instructions and easy to understand diagrams.

> It’s only doing it when the app was closed on the secondary display arranged on the right of the main one, and re-launched once that secondary display was arranged on the left.

But it seems my video https://github.com/rustdesk/rustdesk/issues/6223#issuecomment-2445706426 did the same thing.

Could you please confirm again?

> RustDesk has a check and guarantee that it will show in the visible screens.

> ```
> flutter: restore lpos: 800.0/600.0, offset:2327.5/169.5, devicePixelRatio:2.5, isMaximized: false, isFullscreen: false
> flutter: restore new offset: 2327.5/169.5, scale:1.0
> ```

There may be a potential bug here. For example, if it cannot get the current display list, then it cannot get the visible area.

**Comment by clavelm** [comment] 2024-10-30 13:12
@fufesou 
> But it seems my video [#6223 (comment)](https://github.com/rustdesk/rustdesk/issues/6223#issuecomment-2445706426) did the same thing. Could you please confirm it?

Yes, you are doing the same thing in the video, but is it a Windows 11 in a VM?
I’m still on Windows 10, it may be triggered by something that was fixed in Windows 11.

(I don’t understand what use case would necessitate Windows to allow a window to be completely outside of the display zone.)

**Comment by fufesou** [comment] 2024-10-30 13:26
> but is it a Windows 11 in a VM?

No. I've tested both Win10 and Win11, not in VM.

The bug may be in `window_size.getScreenList()`.

https://github.com/rustdesk/rustdesk/blob/415d2c5c60a309f4b869452366acfbf19e75fca7/flutter/lib/common.dart#L1838

If it failed to get the screen list, RustDesk will use the default rect `(0, 0, 3840, 3840)` as the visible screen rect.

https://github.com/rustdesk/rustdesk/blob/415d2c5c60a309f4b869452366acfbf19e75fca7/flutter/lib/common.dart#L1859


I'll try to fix it. But I can't reproduce it, so I probably can't fix it.

**Comment by clavelm** [comment] 2024-10-30 13:52
@rustdesk @fufesou there are really no problem with my time. I can’t give you money for your very useful app, I really can take some time.
There is a workaround to get back the window visible with "windows key + shift + left/right". And in my use case, I don’t unplug my secondary monitor frequently, so I should not trigger that bug anytime soon.

If you have a way to activate more logging via a flag, or a debug version doing it for Windows, I can run it and provide the logs back.

**Comment by clavelm** [comment] 2024-10-30 15:04
> @clavelm Thanks!
> 
> Please run the temp build here https://github.com/fufesou/rustdesk/releases/tag/tmp
> 
> Still the command line
> 
> ```
> installed: "C:\Program Files\RustDesk\rustdesk.exe" | more
> non-installed: "%localappdata%\rustdesk\rustdesk.exe" | more
> ```
> 
> Please paste the lines that contain `============` and `restore lpos` here.

```
flutter: registerEventHandler check_software_update_finish check_software_update_finish
flutter: ======================== _adjustRestoreMainWindowOffset, desktop: true, window rect: (2545.5, 270.0, 800.0, 600.0)
plugin: ========================== get screen list
flutter: ======================== _adjustRestoreMainWindowOffset, screen 1, visibleFrame: Rect.fromLTRB(0.0, 0.0, 3840.0, 2084.0)
flutter: ======================== _adjustRestoreMainWindowOffset, screen 2, visibleFrame: Rect.fromLTRB(-3840.0, 0.0, 0.0, 2100.0)
flutter: ======================== _adjustRestoreMainWindowOffset, visible frame 1: (-3840.0, 0.0, 3840.0, 2100.0)
flutter: restore lpos: 800.0/600.0, offset:2545.5/270.0, devicePixelRatio:2.5, isMaximized: false, isFullscreen: false
plugin: ========================== get screen list
flutter: restore new offset: 2545.5/270.0, scale:1.0
```

**Comment by fufesou** [comment] 2024-10-30 15:22
Thanks a lot!

I find the reason. "devicePixelRatio" was not taken into account when comparing rects.

I'll take a look at where devicePixelRatio needs to be considered.

**Comment by rustdesk** [comment] 2024-11-11 00:42
@clavelm  could you test the new nightly?

**Comment by clavelm** [comment] 2024-11-12 15:12
> @clavelm could you test the new nightly?

@rustdesk  Fixed on my system with the nightly. The window now opens on the main display. 👍

**Closed** 2024-11-12 15:13 UTC
Labels: bug
