### ISSUE TITLE
Build error on iOS

### ISSUE THREAD

**Issue by nicerghost** [rustdesk/rustdesk#708] opened 2022-06-04 08:06 UTC
**Describe the bug you encountered:**

Building the iOS version produces an error on the final step at the "flutter run" command:

lib/generated_bridge.dart:139:27: Error: The parameter 'ptr' of the method 'RustdeskWire.store_dart_post_cobject' has type 'Pointer<NativeFunction<Bool Function(Int64, Pointer<Void>)>>', which does not match the corresponding type, 'Pointer<NativeFunction<Uint8 Function(Int64, Pointer<Void>)>>', in the overridden method, 'FlutterRustBridgeWireBase.store_dart_post_cobject'.
 - 'Pointer' is from 'dart:ffi'.
 - 'NativeFunction' is from 'dart:ffi'.
 - 'Bool' is from 'dart:ffi'.
 - 'Int64' is from 'dart:ffi'.
 - 'Void' is from 'dart:ffi'.
 - 'Uint8' is from 'dart:ffi'.
Change to a supertype of 'Pointer<NativeFunction<Uint8 Function(Int64, Pointer<Void>)>>', or, for a covariant parameter, a subtype.
    DartPostCObjectFnType ptr,
                          ^

Tried on iPhone and Simulator with same result.

**What did you expect to happen instead?**

Expected RustDesk to run on iPhone or Simulator

**How did you install `RustDesk`?**

Cloned RustDesk repo and followed iOS build instructions.

---

Latest version of RustDesk 1.2.0 from github, using latest build instructions.

MacBook Air Intel
MacOS Monterey 12.4
Flutter 3.0.1
vcpkg, llvm, flutter_rust_bridge_codegen installed

**Comment by SoLongAndThanksForAllThePizza** [comment] 2022-06-05 15:04
This is an issue caused by flutter_rust_bridge generating dart binding wrongly. There's no fix for this yet, but since you've already generated all the needed binding files, you can consider stopping the binding files from being generated and manually fix the generated dart binding file.
1. Go to your build.rs file in the project root path, and comment the line `gen_flutter_rust_bridge();`. This will stop the binding files from being generated.
2. Go to your generated_bridge.dart file(wherever it is), look for```typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;```, change that Bool into Uint8. After modifying, it should look like ```typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Uint8 Function(DartPort, ffi.Pointer<ffi.Void>)>>;```

**Closed** 2022-06-13 16:42 UTC
Labels: bug

**Comment by piaojin** [comment] 2022-07-19 06:21
I failed at step VCPKG_ROOT=$HOME/vcpkg ./flutter/ios_x64.sh. From guide https://rustdesk.com/docs/en/dev/build/ios/

How do you successfully run command  ‘VCPKG_ROOT=$HOME/vcpkg ./flutter/ios_x64.sh’.😂

**Comment by trinvh** [comment] 2023-06-22 07:16
Copy vcpkg folder to your $HOME folder

> I failed at step VCPKG_ROOT=$HOME/vcpkg ./flutter/ios_x64.sh. From guide https://rustdesk.com/docs/en/dev/build/ios/
> 
> How do you successfully run command ‘VCPKG_ROOT=$HOME/vcpkg ./flutter/ios_x64.sh’. @nicerghost 😂

**Comment by trinvh** [comment] 2023-06-22 08:16
For anyone comes after this post.

I'm able to build the IPA to sideload with AltServer. The docs (https://rustdesk.com/docs/en/dev/build/ios/) is outdated and the dependent files are missing `aom` library, so I have to build it (not remember how I did, I'm not a rush developer but will post my `history` if anyone needs).

You can download the update dependent files (including aom) attached below:
[arm64-ios.zip](https://github.com/rustdesk/rustdesk/files/11830773/arm64-ios.zip)
