### ISSUE TITLE
On click will input two same characters when using ipad app control win10 (physical keyboard)

### ISSUE THREAD

**Issue by ynnie** [rustdesk/rustdesk#777] opened 2022-06-14 14:16 UTC
**Describe the bug you encountered:**
Using iPad app connect to a win10 desktop. The connection can be established and the desktop showed normally. But the keyboard was not work normally, click one key will input two sam characters.

**What did you expect to happen instead?**
Click one key will only input one character.
---

**How did you install `RustDesk`?**

Win10: installer from the official website
Ipad: from app store

---

**RustDesk version and environment**
1.1.9

**Comment by ynnie** [comment] 2022-06-14 14:17
The virtual keyboard works normally, the bug appeared when using the apple magic keyboard.

**Comment by rustdesk** [comment] 2022-06-14 14:18
We do not test magic keyboard yet, I do not have it. :)

**Comment by Heap-Hop** [comment] 2022-06-14 14:42
https://github.com/rustdesk/rustdesk/commit/708801bdf623f0fc1d6a69aeaa1bc0610f78835d#diff-4c307d92f13b5bff43b2e30f7b5becd76e84e95afdf6c3759aef1a2e6a81fc2bR738
Maybe same problem, I will check.

**Comment by Sproropo** [comment] 2022-08-14 13:08
Same problem here with magic keyboard for ipad. Also on the contrary, double clicking the touchpad converts in a single click on the guest os (ubuntu in my case).

**Comment by hubkabel** [comment] 2022-11-24 22:51
I'm on the iPad Pro App with an magic keyboard, too. Version of the Client App is 1.1.10 and the Remote Host is a MBP (Version 1.1.9 of RustDesk).
The issue is not present on the magic keyboard, if the virtual keyboard is shown at the same time.

Perhaps this helps to understand the bug.

**Comment by Dakoteus** [comment] 2023-01-20 15:59
Having the same issue with the Logitech Folio Touch. I see in the #907 thread that this issue was fixed on android 3 weeks ago. Was this fixed for iPad? If so, do iPad users have to wait until this next version is released to the apple store? Or is there some other way to install the pre-release of nightly?

Thanks.

**Comment by rustdesk** [comment] 2023-01-21 00:30
github ci support ios?

**Comment by juchems** [comment] 2023-03-08 03:33
I am experiencing this same issue on iPad with magic keyboard.  Same workaround - show onscreen keyboard and it works as expected, hide the keyboard and double characters entered.  I am not aware of a way to update to a more recent build other than to update from the app store.  When does that get updated?  This is the killer app I bought the magic keyboard for, so I am excited to see it work!

**Comment by rustdesk** [comment] 2023-03-08 03:36
Fixed in nightly build, but we have no nightly build for iOS yet.

**Closed** 2023-03-24 07:07 UTC
Labels: bug, help wanted
