### ISSUE TITLE
Win key, special keys like Alt-Tab do not work

### ISSUE THREAD

**Issue by mtelis** [rustdesk/rustdesk#3928] opened 2023-04-04 22:02 UTC
### Bug Description

As %subj suggests, Win and some other special keys stopped working a few nightly builds ago. I'm using the same nightly builds (now it's the latest available) on both local and remote machines. Local is Win10, remotes are Win7 and Win10.

I tried all available keyboard modes.

### How to Reproduce

Connect to remote machine, press Win key, press Alt-Tab - the remote won't respond.

### Expected Behavior

Win key should bring up menu, Alt-Tab show switch between tasks.

### Operating system(s) on local side and remote side

Windows 10 -> Windows 10, Windows 10 -> Windows 7

### RustDesk Version(s) on local side and remote side

1.2.0 Build Date: 2023-04-04 00:24

### Screenshots

Not applicable

**Comment by rustdesk** [comment] 2023-04-05 01:29
@fufesou

**Comment by fufesou** [comment] 2023-04-05 05:27
@mtelis Hi, I've tried 
Win10 -> Win10
1.2.0 Build Date: 2023-04-04 00:24

Win + D, Alt-Tab work fine.

But single "Win" key has no effect.

**Comment by fufesou** [comment] 2023-04-05 15:15
I reproduced this issue. After changing the input method on the remote end, the issue disappeared.

I'm still not sure how to reproduce it and where the keyboard is broken.

I'll keep on fixing it.

**Comment by fufesou** [comment] 2023-04-05 15:16
I reproduced this issue. After changing the input method on the remote end, the issue disappeared.

I'm still not sure how to reproduce it and where the keyboard is broken.

I'll keep on fixing it.

**Comment by rustdesk** [comment] 2023-04-06 03:36
win key, alt tab etc work fine for me with today build.

**Comment by mtelis** [comment] 2023-04-06 03:45
Win and Win-D work fine, Alt-Tab doesn't work.

Today's nightly build on both ends.

> Mike

**Comment by fufesou** [comment] 2023-04-06 04:23
There's nothing changed.
This could be a issue that is not easy to reproduce.

**Comment by fufesou** [comment] 2023-04-06 04:36
@mtelis Is this issue inevitable for you? Have you installed RustDesk?

**Comment by mtelis** [comment] 2023-04-06 04:52
Yes, I installed Rustdesk. Haven't had this issue before, with earlier
builds. Previous was dated March 19th, if I'm not mistaken.

> Mike

**Comment by rustdesk** [comment] 2023-04-06 05:00
@fufesou since can not reproduced on our side, no need to spend time on it, let it be open

**Comment by cypherpunks03** [comment] 2023-04-06 06:19
Stop blindly testing your keyboard using some junk IDEs and editors. Take utilities for monitoring the state of the keyboard and see what events come from it. I'll just leave [this](https://github.com/rustdesk/rustdesk/files/11166987/KeyboardTestUtility.zip) here.

**Comment by fufesou** [comment] 2023-04-06 06:45
Hi, @mtelis can you please run the build here?

The only difference are:
1. "CapsLock" and "NumLock" are not synchronized.
2. Some key logs are added.

Please attach the log file here if you have run it.

```
%UserProfile%\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
```

**Comment by cypherpunks03** [comment] 2023-04-06 08:23
@fufesou, now everything works perfectly, except for alternative English layouts with QWERTY-VK-codes. The alternative Russian layout works fine, Hebrew layout works fine, all hotkeys are sent correctly, both Ctrl+ and Win+ work fine. As long as you don't break anything.

**Comment by fufesou** [comment] 2023-04-06 08:33
@cypherpunks03 Do you means today's nightly build fron rustdesk's repo also behaves like @mtelis on you PC?
Win + , Alt + Tab are broken.

And my tmp build works fine?

https://github.com/rustdesk/rustdesk/compare/master...fufesou:rustdesk:tmp/remove_led_sync

**Comment by mtelis** [comment] 2023-04-06 14:56
> Hi, @mtelis can you please run the build [here](https://github.com/fufesou/rustdesk/releases/tag/nightly)?
> 
> ![1680763993175](https://user-images.githubusercontent.com/13586388/230294817-b4ed34fd-f5bd-4c35-8c2f-d63e4141e0bb.png)
> 
> The only differences are:
> 
> 1. "CapsLock" and "NumLock" are not synchronized.
> 2. Some key logs are added.
> 
> [master...fufesou:rustdesk:tmp/remove_led_sync](https://github.com/rustdesk/rustdesk/compare/master...fufesou:rustdesk:tmp/remove_led_sync)
> 
> Please attach the log file here if you have run it.
> 
> ```
> %UserProfile%\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
> C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
> ```
> 
> As the nightly tag will be overwritten every nightly. I've updated the build tag to "tmp". https://github.com/fufesou/rustdesk/releases/tag/tmp Please use the app here if new build is released here.


The build I'm running on both machines is Build Date: 2023-04-06 03:07.

Alt-Tab doesn't work.

[Local_RustDesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/11171835/Local_RustDesk_rCURRENT.log)

[RustDesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/11171845/RustDesk_rCURRENT.log)

Attached both local and remote logs.

**Comment by ForsakenRei** [comment] 2023-04-06 15:56
> I reproduced this issue. After changing the input method on the remote end, the issue disappeared.
> 
> I'm still not sure how to reproduce it and where the keyboard is broken.
> 
> I'll keep on fixing it.

For some Chinese input method you can tap `shift` to switch between Chinese and English input mode without changing the input method, therefore if I have a Chinese input method on the remote side I should be able to tap `shift` to switch input mode. It works in nightly build before but not in recent ones. Seems to be related to the original issue?

**Comment by mtelis** [comment] 2023-04-06 19:02
Let me know when you have an update, I'll check if it works.

**Comment by fufesou** [comment] 2023-04-07 01:55
> It works in nightly build before but not in recent ones. 

@ForsakenRei Which OS do you use on both side?

It works on my PCs. Win -> Win

"Shift" is a simple key that is transmitted and simulated directly.

**Comment by fufesou** [comment] 2023-04-07 02:01
@mtelis Thanks for you test. But your attached file dose not write logs about keyboard simulations.

https://github.com/fufesou/rustdesk/blob/cf83760ab3ce7c9a80a660c5db74b19dbda0ec4a/src/server/input_service.rs#L995
https://github.com/fufesou/rustdesk/blob/cf83760ab3ce7c9a80a660c5db74b19dbda0ec4a/src/server/input_service.rs#L1425

```
%UserProfile%\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
```

Can you please try again and attach the file.

The log should be something like
```
[src\server\input_service.rs:1425] REMOVE ME =========================================== handle_key_ KeyEvent { down: true, press: false, modifiers: ), special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[src\server\input_service.rs:1425] REMOVE ME =========================================== handle_key_ KeyEvent { down: false, press: false, modifiers: , special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[src\server\input_service.rs:995] REMOVE ME =========================================== simulate_ KeyRelease(RawKey(ScanCode(30)))
[src\server\input_service.rs:1425] REMOVE ME =========================================== handle_key_ KeyEvent { down: true, press: false, modifiers: 5)), special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[src\server\input_service.rs:995] REMOVE ME =========================================== simulate_ KeyPress(RawKey(ScanCode(57435)))
[src\server\input_service.rs:1425] REMOVE ME =========================================== handle_key_ KeyEvent { down: false, press: false, modifiers: otkey(5963776)), special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[src\server\input_service.rs:1425] REMOVE ME =========================================== handle_key_ KeyEvent { down: true, press: false, modifiers: 5)), special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[src\server\input_service.rs:995] REMOVE ME =========================================== simulate_ KeyPress(RawKey(ScanCode(57435)))
[src\server\input_service.rs:1425] REMOVE ME =========================================== handle_key_ KeyEvent { down: false, press: false, modifiers: [], mode: Translate, union: Some(Win2winHotkey(5963776)), special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
```

**Comment by ForsakenRei** [comment] 2023-04-07 02:18
> > It works in nightly build before but not in recent ones.
> 
> @ForsakenRei Which OS do you use on both side?
> 
> It works on my PCs. Win -> Win
> 
> "Shift" is a simple key that is transmitted and simulated directly.

Both Windows, let me try the latest nightly build, noticed the one I used is different by the file name.

**Comment by fufesou** [comment] 2023-04-07 02:32
This is so abnormal. I feel like there's no event triggering the shift key locally.
Can you please try `a` and `Shift` + `a` using "Map mode"?

**Comment by mtelis** [comment] 2023-04-07 05:07
> @mtelis Thanks for you test. But your attached file dose not write logs about keyboard simulations.

That's the thing! I did press Alt-Tab several times and switched keyboard modes in between. I have a hunch you're right about the local Rustdesk missing keyboard events.

**Comment by ForsakenRei** [comment] 2023-04-07 05:11
> This is so abnormal. It seems there's no `Shift` event is triggered locally. Can you please try `a` and `Shift` + `a` using "Map mode"?

Normal `shift` works just fine. I noticed it only happens to one of my machines. I use A to connect to B and `Shift` works as intended with input methods and others. But if I use B to connect to A it won't work. It's so weird...

**Comment by fufesou** [comment] 2023-04-07 05:27
> That's the thing! I did press Alt-Tab several times and switched keyboard modes in between.

@mtelis Thx.

Please also try type: 
1. Some letters
2. Alt + Tab
3. Some letters.

So I can see if the events are sent to the host side.

**Comment by fufesou** [comment] 2023-04-07 05:33
> I noticed it only happens to one of my machines.

@ForsakenRei I have not encountered this situation. It wired.

BTW, did you have RustDesk installed on Machine A? Please try again after installing if you have not installed it.

**Comment by cypherpunks03** [comment] 2023-04-07 06:19
@fufesou Awesome! Now everything works great for me! All of my weird keyboard layouts are handled amazingly! This is how you leave it! Now it remains to wait until it will be possible to switch layouts on the local machine with the keys Alt + Shift , Win + Space or Ctrl + Shift . But this is a controversial issue and it needs to be resolved in an optional way.

**Comment by fufesou** [comment] 2023-04-07 06:30
> now everything works perfectly, except for alternative English layouts with QWERTY-VK-codes. 

Is this issue also fixed? @cypherpunks03
I have not changed anything.

> Now it remains to wait until it will be possible to switch layouts on the local machine with the keys `Alt + Shift` , `Win + Space` or `Ctrl + Shift` .

I cannot understand. Swithing layouts is a shortcut defined by the OS user, or applications.  
RustDesk only handles key mappings.

**Comment by fufesou** [comment] 2023-04-07 06:33
@mtelis @ForsakenRei Can you please try this build https://github.com/fufesou/rustdesk/releases/tag/tmp_3_17 ?
They're built form the code of March 17th.

> Please also try type:
> 1. Some letters
> 2. Alt + Tab
> 3. Some letters.

> So I can see if the events are sent to the host side.

@mtelis Please also try these steps. So I can get some logs.

**Comment by cypherpunks03** [comment] 2023-04-07 06:38
@fufesou I just downloaded the build 2023-04-07 05:33

**Comment by fufesou** [comment] 2023-04-07 06:52
> now everything works perfectly, except for alternative English layouts with QWERTY-VK-codes.

To be honest, I don't know this issue clearly. But I'm glad to hear it is solved.

**Comment by mtelis** [comment] 2023-04-07 12:27
> @mtelis @ForsakenRei Can you please try this build https://github.com/fufesou/rustdesk/releases/tag/tmp_3_17 ? They're built form the code of March 17th.

Downloaded and installed it on local machine. Win key works, Alt-Tab doesn't.

Installed on local machine only. Just to clarify, I always uninstall previous version and install new version of Rustdesk.

Local log, I typed some chars and tried Alt-Tab in between.



[RustDesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/11178839/RustDesk_rCURRENT.log)

**Comment by fufesou** [comment] 2023-04-07 12:46
Thx. 
It seems the "Alt-Tab" issue is not caused by recent changes after March 17th. Or there is some changes of your local machine.

Sorry for the confusion. Can you please try the build here?  https://github.com/fufesou/rustdesk/releases/tag/tmp

There're special logs in this build https://github.com/fufesou/rustdesk/releases/tag/tmp

There's no special log in this build https://github.com/fufesou/rustdesk/releases/tag/tmp_3_17.

**Comment by mtelis** [comment] 2023-04-07 13:07
Tried /tmp build, behavior is still the same.

[RustDesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/11179093/RustDesk_rCURRENT.log)

I'm on long vacation, didn't change anything in my machines (except for automatic windows updates)

**Comment by fufesou** [comment] 2023-04-07 14:41
> Tried /tmp build, behavior is still the same.
> 
> [RustDesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/11179093/RustDesk_rCURRENT.log)
> 
> I'm on long vacation, didn't change anything in my machines (except for automatic windows updates)

I can't find records like 
```
[src\server\input_service.rs:1425] REMOVE ME =========================================== handle_key_ KeyEvent { down: true, press: false, modifiers: ), special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[src\server\input_service.rs:1425] REMOVE ME =========================================== handle_key_ KeyEvent { down: false, press: false, modifiers: , special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[src\server\input_service.rs:995] REMOVE ME =========================================== simulate_ KeyRelease(RawKey(ScanCode(30)))
```

Sorry, I was wrong about the file locations. But can you please try again? Thx @mtelis 

The logs are written on the controlled(remote) side.

For portable version, the server log is:
```
%UserProfile%\AppData\Roaming\RustDesk\log\RustDesk_rCURRENT.log
```

For installed version, the server log is:
```
C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
```

**Comment by ForsakenRei** [comment] 2023-04-07 16:00
> > I noticed it only happens to one of my machines.
> 
> @ForsakenRei I have not encountered this situation. It wired.
> 
> BTW, did you have RustDesk installed on Machine A? Please try again after installing if you have not installed it.

It's really weird. 
They all have RustDesk installed, on machine A I even clean reinstalled(clear reg and appdata files etc.) but nothing really changes. I tried Anydesk just to verify and it works as expected.
So it's probably something wrong on machine A, or when connected to machine A? I can grab some logs when I get back as well.

**Comment by mtelis** [comment] 2023-04-08 00:15
> Sorry, I was wrong about the file locations. But can you please try again? Thx @mtelis
> 
> The logs are written on the controlled(remote) side.

Yes, I can try again. Which version do I install on both machines for this experiment?

**Comment by fufesou** [comment] 2023-04-08 01:32
https://github.com/fufesou/rustdesk/releases/tag/tmp

This build.

**Comment by mtelis** [comment] 2023-04-08 02:22
> For installed version, the server log is:
> 
> ```
> C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
> ```

![image](https://user-images.githubusercontent.com/335301/230699111-9fda41ed-5a75-43b8-ad05-9103bd0e1faa.png)

With all due respect, there is no "server" folder at the path you specified.

Anyway, I installed /tmp version on both local and remote machines and (suprise!) both Win and Alt-Tab are working! PrtScr is not working, though -- but it's a trifle.

**Comment by fufesou** [comment] 2023-04-08 02:47
@mtelis It seems you are looking at the wrong path.

![image](https://user-images.githubusercontent.com/13586388/230699724-77df46fb-04d4-41b2-8cd7-defc269992d0.png)

> I installed /tmp version on both local and remote machines and (suprise!) both Win and Alt-Tab are working! 

It is strange, I have not changed the tmp build.
Did you use tmp build on the remote machine in the previous tests?

1. Can you please check the file on the remote machine, and the attach here?
```
C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
```
2. Can you please try again the [3_17](https://github.com/fufesou/rustdesk/releases/tag/tmp_3_17) build and the latest [nightly](https://github.com/rustdesk/rustdesk/releases/tag/nightly) build? So I can know that if the `Alt + Tab` is broken by recent changes?

> PrtScr is not working

Is it the same issue https://github.com/rustdesk/rustdesk/issues/3740?

**Comment by mtelis** [comment] 2023-04-08 02:54
> It is strange, I have not changed the tmp build.
> Did you use tmp build on the remote machine in the previous tests?

No, it wasn't tmp build because we all assumed (wrongly!) that it's the local machine who failed to send keyboard events.

Realized my mistake with the path, working on the answers to your questions.

**Comment by fufesou** [comment] 2023-04-08 02:57
> Update: Just realized I can use https://keyboard-test.space/ to test what keystroke was sent. It seems on machine A, if I press `Shift` it will receive `Num Lock`, `Num Lock` and `Shift`. While on other machines using RustDesk, or if I use other software it will just receive a normal `Shift`.

@ForsakenRei Thanks. It is the reason.

I've tried, pressing `Shift`, `NumLock` click, releasing `Shift`. Then `Shift` has no effects.

`Num Lock`, `Num Lock` and `Shift`" is the side effect of led lock state synchronizing.

**Comment by fufesou** [comment] 2023-04-08 03:03
@mtelis It seems your issue and @ForsakenRei 's issue are caused by recent "led lock state synchronition".

But except for reproducing once before, I cannot reproduce your issue now.

**Comment by mtelis** [comment] 2023-04-08 03:04
Uninstalled /tmp version, installed the latest nightly build, both on the local and remote machines. Win works, Alt-Tab doesn't, and I can't switch keyboard language using Ctrl-Shift combination. All that worked in /tmp build.

Log is below, hope it's the right one (finally!)
[RustDesk_rCURRENT.log](https://github.com/rustdesk/rustdesk/files/11182397/RustDesk_rCURRENT.log)

**Comment by mtelis** [comment] 2023-04-08 03:09
> But except for reproducing once before, I cannot reproduce your issue now.

Cheshire bug, really! Shrodinger's cat, it's there and not there! And like Cheshire cat, appears and disappears all the time.

Unlike Alice in Wonderland, I'm too old to believe in miracles. I think you're right, it's a self-inflicted bug induced by the LED sync code. Speaking of which, I noticed that Numlock key and LED are behaving erratically. It started not so long ago, wasn't as annoying as the Alt-Tab and I postponed this investigation for the later, when I have more time and inspiration.

**Comment by ForsakenRei** [comment] 2023-04-08 05:35
> @mtelis It seems your issue and @ForsakenRei 's issue are caused by recent "led lock state synchronition".
> 
> But except for reproducing once before, I cannot reproduce your issue now.

I see. But I still cannot understand why it only happens to one of my 3 machines, they all have Win10, the only difference will probably be machine A(which has that bug) is a desktop PC, others that didn't have that issue are all laptops. Though the keyboard on it is a 65% so no num pad...

**Comment by fufesou** [comment] 2023-04-08 06:18
> I see. But I still cannot understand why it only happens to one of my 3 machines

You can check if the `NumLock` led state.
"Machine A" should have the state on, and the other two should have the state off.

**Comment by cypherpunks03** [comment] 2023-04-08 06:55
@fufesou , ah shi..., here we go again. =(

**Comment by ForsakenRei** [comment] 2023-04-08 17:11
> > I see. But I still cannot understand why it only happens to one of my 3 machines
> 
> You can check if the `NumLock` led state. "Machine A" should have the state on, and the other two should have the state off.

You are right. I did some more tests about NumLock and Caps Lock. As long as those are on at the remote side, no matter what status on the host(match or not), it won't work properly. I will try the new nightly build once it runs and report back.

**Comment by fufesou** [comment] 2023-04-09 14:08
@mtelis @ForsakenRei Can you please try the next nightly build?
I've ignored `Alt`, `Shift`, `Tab` while processing the led state sync.

**Comment by mtelis** [comment] 2023-04-10 04:44
> @mtelis @ForsakenRei Can you please try the next nightly build?
> I've ignored `Alt`, `Shift`, `Tab` while processing the led state sync.

Works just fine for me, thank you!

**Comment by ForsakenRei** [comment] 2023-04-10 05:02
> @mtelis @ForsakenRei Can you please try the next nightly build? I've ignored `Alt`, `Shift`, `Tab` while processing the led state sync.

NumLock issue was gone with Shift, Thank you for the fix!

Through the tests I noticed if remote side has Caps Lock on and a input methods on, if host has Caps Lock on as well then upper case can be registered however if host has Caps Lock off then some Chinese input methods are not working properly, but this should be a really rare case probably no one will even encounter, thus not something to be fixed unless others reported.

**Comment by fufesou** [comment] 2023-04-10 12:50
@mtelis @ForsakenRei Thanks for your tests and feedback. :smiley:

**Comment by cypherpunks03** [comment] 2023-04-10 13:26
@fufesou , why in all layouts do you send VK_PACKET , but in alternative layouts Dvorak , Colemak and AZERTY you rely on VK codes corresponding to QWERTY ?

**Comment by fufesou** [comment] 2023-04-10 13:51
@cypherpunks03 Do you mean "Translate mode"?

RustDesk does not detect the keyboard layout for now?

"Translate mode" tries to send 
1. The "Unicode" generated by most keystrokes.
2. The "Unicode|VK code" while processing hotkeys.
3. The position codes (scan codes) if the non-letter keys are pressed.

You can refer here for more informations. https://github.com/fufesou/rustdesk/wiki/Keyboard-mode----Translate-Mode

**Closed** 2023-04-11 02:00 UTC
Labels: bug, unreproducible

**Comment by rustdesk** [comment] 2023-04-11 02:08
https://github.com/rustdesk/rustdesk/blob/b22fe7fc77ae7840e4ce704459b2225239353d93/src/server/input_service.rs#L1377
