### ISSUE TITLE
Active app lost focus when connecting to windows

### ISSUE THREAD

**Issue by fernandeusto** [rustdesk/rustdesk#4010] opened 2023-04-10 22:35 UTC
### Bug Description

With the option "hide connection management window" is active, when connecting to a windows computer, the active application loses focus. 
This is especially serious when you connect in view only mode, and the client loses focus on the application it is working on.

### How to Reproduce

![image](https://user-images.githubusercontent.com/87156183/231010441-bba9215d-35cd-4304-9bb9-3a66fe4b228a.png)

Active this option

Open Notepad on client windows.

Connect to client 

### Expected Behavior

the client must not perceive the connection and its work must not be interrupted

### Operating system(s) on local side and remote side

Windows10 > windows 10

### RustDesk Version(s) on local side and remote side

Last Nighty

### Screenshots

<img width="594" alt="image" src="https://user-images.githubusercontent.com/87156183/231011640-6edc93b4-686f-4387-8090-9ab503029fde.png">
Screenshot Before conection

<img width="585" alt="image" src="https://user-images.githubusercontent.com/87156183/231011788-35242a5a-01d0-4305-b475-d8416597a89f.png">
screenshot After connection

Notepad lost focus

**Comment by 21pages** [comment] 2023-04-10 23:34
Reproduced, the window lost focus, clicking the mouse will regain the focus, but what effect will this cause?

**Comment by rustdesk** [comment] 2023-04-11 00:00
let wait for more feedback

**Comment by rustdesk** [comment] 2023-04-11 00:15
but it is hiding cm windows, since no cm pops out, current active window should not lose focus.

**Comment by rustdesk** [comment] 2023-04-11 02:25
close since fix merged

**Closed by rustdesk** 2023-04-11 02:25 UTC
Labels: bug, wontfix

**Comment by rustdesk** [comment] 2023-04-11 08:59
Ready tommorrow.

**Comment by fernandeusto** [comment] 2023-04-12 08:51
Works perfect now
thank you
