### ISSUE TITLE
JIS (Japan Industrial Standards) key mapping issues (mac -> win)

### ISSUE THREAD

**Issue by kmk-matsui** [rustdesk/rustdesk#5027] opened 2023-07-16 16:46 UTC
### Bug Description

The conversion key and non-conversion key on the JIS keyboard are not working.

### How to Reproduce

When inputting the English and Japanese keys from a Mac, the non-conversion key and conversion key are recognized on Windows.

### Expected Behavior

When keydown the Eisu（英数） key on a Mac, the non-conversion（無変換） key are recognized on Windows.
When keydown the Kana（かな） key on a Mac, the conversion（変換） key are recognized on Windows.

### Operating system(s) on local side and remote side

MacOS(Ventura 13.4.1(c)) -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.1 -> 1.2.1

### Screenshots

Reference: [Wikipedia - Language input keys](https://en.wikipedia.org/wiki/Language_input_keys )
<img width="972" alt="スクリーンショット 2023-07-17 1 43 20" src="https://github.com/rustdesk/rustdesk/assets/28127360/73fc11ca-9e8f-445d-b3ea-7f61c9a95ace">

**Comment by rustdesk** [comment] 2023-07-17 00:15
@fufesou

**Comment by fufesou** [comment] 2023-07-17 15:06
Bellow is the soft keyboard layout of my macOS.

![image](https://github.com/rustdesk/rustdesk/assets/13586388/36ce0949-3375-4b26-b7ef-8d0cd839a81d)

**Comment by kmk-matsui** [comment] 2023-07-17 15:21
@fufesou 

I think the non-conversion key and the conversion key on Windows correspond to the 英数(eisu) key and the かな(kana) key on MacOS.

press a key "non-convertion key"(英数キー)
```
name: Some(UnicodeInfo { name: Some(" "), unicode: [32], is_dead: false }), type: KeyPress(Lang2), code: 0x66, scan: 0x0000
name: None, type: KeyRelease(Lang2), code: 0x66, scan: 0x0000
```

press a key "converion key" (かなキー)
```
name: Some(UnicodeInfo { name: Some(" "), unicode: [32], is_dead: false }), type: KeyPress(Lang1), code: 0x68, scan: 0x0000
name: None, type: KeyRelease(Lang1), code: 0x68, scan: 0x0000
```

**Comment by fufesou** [comment] 2023-07-17 15:30
@kmk-matsui 

The soft keyboard cannot be grabbed by the process.

I've plugged in a physical JIT keyboard, but the "non-convertion key" and "converion key" can not be grabbed.

Thanks for the quick and useful  reply. I'll add the key-code map later.

**Comment by rustdesk** [comment] 2023-07-18 03:37
The fix is merged, please test with the nightly build. https://github.com/rustdesk/rustdesk/releases/nightly.

**Comment by kmk-matsui** [comment] 2023-07-18 04:18
@fufesou 
I installed the nightly version on both macOS and Windows.
And I tested the  "non-convertion key" and "converion key" keys on the website (https://anysweb.co.jp/keycheck/#google_vignette) using Windows, but they were not recognized.

**Comment by kmk-matsui** [comment] 2023-07-18 05:27
@fufesou 
Operating system(s) on local side and remote side: Windows10 -> Windows11
In the above case he "non-convertion key" and "converion key" keys were recognized.
version 1.2.1 on local side is not nightly version.

**Comment by fufesou** [comment] 2023-07-18 05:38
There's no "key-code" map between the same OSs.

I'll try to find the map later by another test method.

**Comment by fufesou** [comment] 2023-07-18 23:59
@kmk-matsui Hi, I've tried mac -> win.

My mac cannot detect key event of "Non-Convert" and "Convert". I'll try to find the reason.
It's strange that the "grab" process works on your computer.

I can send Non-Convert and Convert from my mac computer to windows computer by exchanging the mapping of "A" with "Non-Convert" and "B" with "Convert". It works fine.

**Comment by kmk-matsui** [comment] 2023-07-19 06:27
@fufesou 
On Mac, the keys "Non-Convert" and "Convert" are not recognized. Instead, there are keys labeled "Eisu" (英数) and "Kana" (かな). These keys are used to switch between input methods.

**Comment by dignow** [comment] 2023-07-19 06:38
Thanks.
But I can't detect keypress events on either side of the spacebar. :upside_down_face:
I'll try to find why they cannot be detected later.

**Comment by fufesou** [comment] 2023-07-19 06:46
Thanks.
But I can't detect keypress events on either side of the spacebar. 🙃
I'll try to find out why they cannot be detected later.

**Comment by fufesou** [comment] 2023-10-24 09:52
> > I can send Non-Convert and Convert from my mac computer to windows computer by exchanging the mapping of "A" with "Non-Convert" and "B" with "Convert". It works fine.
> 
> you mean by exchanging the mapping on windows, or in rustdesk, or where?
> 

I changed rustdesk.
On the mac side, when I pressing "A", I send the "Non-Convert" key event to the remote side.

I mean, the key mappings from mac to win are right. But I cannot detect the key events on my mac.

**Comment by My1** [comment] 2023-10-24 09:59
> > > I can send Non-Convert and Convert from my mac computer to windows computer by exchanging the mapping of "A" with "Non-Convert" and "B" with "Convert". It works fine.
> > 
> > 
> > you mean by exchanging the mapping on windows, or in rustdesk, or where?
> 
> I changed rustdesk. On the mac side, when I pressing "A", I send the "Non-Convert" key event to the remote side.
> 
> I mean, the key mappings from mac to win are right. But I cannot detect the key events on my mac.

meaning you dont get to see the Lang1 and Lang2 when pressing the keys on a mac keyboard?
because ideally if you can see the Lang1 and Lan2 events you should be able to tell rust desk, that if it gets an incoming Lang1/2 and the remote side is not running on Apple, that the remote rustdesk understands Convert/nonconvert

**Comment by fufesou** [comment] 2023-10-24 11:24
> meaning you dont get to see the Lang1 and Lang2 when pressing the keys on a mac keyboard? or are you using a standard JIS kb on a mac?

Yes, there are no key events when I pressing or releasing the keys aside to the space key.

It may be caused by the system of my macOS, or the implementation of detecting the keys. Windows can detect the keys.

**Comment by rustdesk** [comment] 2023-10-24 11:29
Does AnyDesk work?

**Comment by fufesou** [comment] 2023-10-24 11:43
I've tried AnyDesk (mac -> Win, Map 1:1 mode), the keys aside the space also do not send key events.

**Comment by fufesou** [comment] 2023-10-24 11:55
But the keys can be detected https://github.com/rustdesk/rustdesk/issues/5027#issuecomment-1638367991 by @kmk-matsui 

I've already added the code mappings. But I cannot understand why there's still an issue here.

> On Mac, the keys "Non-Convert" and "Convert" are not recognized. Instead, there are keys labeled "Eisu" (英数) and "Kana" (かな). These keys are used to switch between input methods.
On Windows, the keys labeled "Eisu" (英数) and "Kana" (かな) correspond to the "Non-Convert"" and "Convert" keys.
The key codes for "Eisu" (英数) and "Kana" (かな) keys are different from those of "Non-Convert" and "Convert" keys on Windows.

RustDesk uses the position code mapping, the keys' function will not affect the mapping.

**Comment by rustdesk** [comment] 2023-10-24 11:58
> I've tried AnyDesk (mac -> Win, Map 1:1 mode), the keys aside the space also do not send key events.

If so, should we continue to spend time on this?

**Comment by My1** [comment] 2023-10-24 12:07
not sure if it's unsolvable or anydesk didnt have enough japanese customers needing this (if at all)

https://github.com/rustdesk/rustdesk/issues/5027#issuecomment-1638367991
the part that is interesting tbh is how this key grabber can see the keys, but not rustdesk.

**Comment by rustdesk** [comment] 2023-10-24 12:13
tracked by https://github.com/rustdesk/rustdesk/issues/4367 to mark as low priority, hope Japanese dev can work on this.

**Closed by rustdesk** 2023-10-24 12:13 UTC
Labels: bug, Hacktoberfest

**Comment by rustdesk** [comment] 2023-10-24 12:22
> anydesk didnt have enough japanese customers needing this (if at all)

I don't think any commercial company would like give up a big market like Japan.

**Comment by My1** [comment] 2023-10-24 12:27
> > anydesk didnt have enough japanese customers needing this (if at all)
> 
> I don't think any commercial company would like give up a big market like Japan.

I wouldnt say give up, but just that some things may not be seen unless someone asks and it is a bit specific as you need to both be japanese and go mac -> win.

**Comment by My1** [comment] 2023-10-24 12:31
aside from being weird af, one thing that might need to be checked is how this works in mac to mac connections, I mean if the local mac's rustdesk doesnt even see the Lang1/2 keys in the first place it couldnt send the keys to the remote mac either.

**Comment by kmk-matsui** [comment] 2023-10-24 12:43
Similarly, Lang1 and Lang2 were not recognized by chrome remote desktop, so I mapped F11 and F12 to Lang1 and Lang2 in karabiner and assigned the non-conversion and conversion keys to F11 and F12 in the chrome remote desktop keymap.

**Comment by kmk-matsui** [comment] 2023-10-24 12:47
If rundesk has a keymap assignment function like chrome remote desktop, it would be possible to support the above.

**Comment by rustdesk** [comment] 2023-10-24 12:51
We do want to add keymap, though not high priority.

**Comment by fufesou** [comment] 2023-10-24 12:54
> If rundesk has a keymap assignment function like chrome remote desktop, it would be possible to support the above.

But the real problem is that Lang1/2 is recognized on your computer and then there is something wrong with the mapping.

Maybe this issue could also be solved later sometime, not now.

**Comment by rustdesk** [comment] 2023-10-24 12:57
> on your computer

So this issue is better to be solved by an Japanese dev, since we do not have the keyboard and super low efficiency.

**Comment by My1** [comment] 2023-10-24 13:29
or at the very least a dev/hacker with access to a mac and a japanese apple keyboard.
