### ISSUE TITLE
the rustdesk screen has problem (osx -> x)

### ISSUE THREAD

**Issue by cengzhijie3** [rustdesk/rustdesk#3424] opened 2023-02-28 02:22 UTC
### Bug Description

the screen is invisible,  can not see the android screen

### How to Reproduce

use macbook and try to control the android system

### Expected Behavior

the screen is invisible,  can not see the android screen

### Operating system(s) on local side and remote side

mac os13.2.1 > androdid

### RustDesk Version(s) on local side and remote side

nightly version

### Screenshots

<img width="1381" alt="截圖 2023-02-28 上午10 17 43" src="https://user-images.githubusercontent.com/89333400/221736184-7043ec4f-84fb-4ae9-a949-8cbc37fbcd0a.png">

### Additional Context

the screen is invisible,  can not see the android screen

**Comment by Heap-Hop** [comment] 2023-02-28 03:27
Thx, does it occur every time on your device?
How about changing the screen direction to horizontal?

And please tell me your Android device's screen pixel size(height width).

**Comment by cengzhijie3** [comment] 2023-02-28 03:42
Samsung Galaxy A32 screen size is 6.4 inch with ~ 84.6% body ratio of
actual device size. Physical dimensions for Samsung Galaxy A32 device is
6.26 x 2.90 x 0.33 INCH or ( 158.9 x 73.6 x 8.4 MM).

CSF ***@***.***> 於 2023年2月28日 週二 上午11:27 寫道：

**Comment by Heap-Hop** [comment] 2023-02-28 08:43
@cengzhijie3 Hi, what is your Android system version? 
I tried Samsung Galaxy A32 Android12 as screen service by https://developer.samsung.com/remote-test-lab .
But I couldn't reproduce. :(

Does it occur every time on your device?
or does it also occur between different devices? Could you please try out some other device control your Android device or use your mac os13.2.1 control other device?

**Comment by cengzhijie3** [comment] 2023-03-01 00:05
sorry, i just use the only one android phone, i do not have any other device that could be controlled by my macOS

**Comment by RichardBurt65** [comment] 2023-03-01 15:49
I have this from todays nightly build for macOS too. Connecting from macOS to any machine shows the same display issue.

**Comment by Heap-Hop** [comment] 2023-03-02 02:13
@RichardBurt65 Thanks, seems like we should focus on macOS.

**Comment by fufesou** [comment] 2023-03-02 02:58
For me

1. macOS -> Win works fine.
2. macOS -> android has this issue.
3. win -> android wors fine.

**Comment by rustdesk** [comment] 2023-03-02 03:00
Probably related to texture.

**Comment by rustdesk** [comment] 2023-03-02 03:01
and display size related.

**Comment by rustdesk** [comment] 2023-03-02 03:01
@Kingtous

**Comment by fufesou** [comment] 2023-03-03 03:56
@cengzhijie3 @RichardBurt65 Hi, this issue should be fixed by PR 3477.

**Comment by rustdesk** [comment] 2023-03-03 06:37
try out https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-apple-darwin.dmg please.

**Comment by fufesou** [comment] 2023-03-03 06:51
> Black screen to 1 x Win and 1 x Mac machines

@RichardBurt65 Hi, what do you mean by 1 x Win and 1x Mac?

**Comment by RichardBurt65** [comment] 2023-03-03 06:52
Connected remotely from my Mac to another Mac and another Win 11 machine. Both remote machines show a black screen

**Comment by rustdesk** [comment] 2023-03-03 06:52
@RichardBurt65 please let us know your display resolution on controlled side.

**Comment by RichardBurt65** [comment] 2023-03-03 06:55
Win machine: 1377 x 768 (recommended)

Mac machine: 3024 × 1964 (Retina)

**Comment by RichardBurt65** [comment] 2023-03-03 06:59
On other resolutions on the Win machine I'm seeing artefacts (silver bar top of screen - see screenshot)

<img width="1512" alt="Screenshot 2023-03-03 at 10 58 21" src="https://user-images.githubusercontent.com/110833650/222652751-e464e9d6-3ea3-4112-b377-0d8cb1c26400.png">

**Comment by rustdesk** [comment] 2023-03-03 07:53
@RichardBurt65 could you try out this new https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.0-x86_64-apple-darwin.dmg please?

**Comment by rustdesk** [comment] 2023-03-03 07:59
Wait a moment.

**Comment by NicKoehler** [comment] 2023-03-03 08:03
Having this issue too windows -> linux

![immagine](https://user-images.githubusercontent.com/53040044/222665119-4b83a47b-cb9b-479e-905d-090ea279d048.png)

**Comment by rustdesk** [comment] 2023-03-03 08:07
Yes, fixing.

**Closed** 2023-03-09 11:52 UTC
Labels: bug, good first issue

**Comment by cengzhijie3** [comment] 2023-03-26 07:38
I can access my macbook with the ip of my vps in android, but my macbook cannot access my android rustdesk
![WechatIMG22](https://user-images.githubusercontent.com/89333400/227762018-ad22bb0b-fb6e-4b8a-9bf5-bddd899ed0e3.jpeg)
![WechatIMG23](https://user-images.githubusercontent.com/89333400/227762021-c3c86a97-911b-4688-839f-ff17ee52fee8.jpeg)
<img width="912" alt="截圖 2023-03-26 下午12 24 57" src="https://user-images.githubusercontent.com/89333400/227762030-358c8b36-88cf-440a-98a3-d05a3607e390.png">
<img width="1381" alt="截圖 2023-03-26 下午12 24 50" src="https://user-images.githubusercontent.com/89333400/227762043-d2fc25d2-3d8d-4611-aa56-73696ce86304.png">
