### ISSUE TITLE
Blank Screen on RustDesk

### ISSUE THREAD

**Issue by muaaz0412** [rustdesk/rustdesk#447] opened 2022-04-14 12:29 UTC
While running from the .app the blank screen appears whereas when i start it from the content inside the .app package and it starts from terminal and works fine. i need to fix this issue everything is okay and fine in code using the original code.
<img width="1440" alt="Screenshot 2022-04-14 at 5 22 20 PM" src="https://user-images.githubusercontent.com/88825079/163389929-b621eeb7-2bb7-457d-bdc8-23fa9020bb87.png">

**Comment by grummbeer** [comment] 2023-01-20 12:54
please try with nightly version https://github.com/rustdesk/rustdesk/releases/tag/nightly

probably a duplicate of #80

**Closed** 2023-01-21 00:40 UTC
