### ISSUE TITLE
[Bug]The Mac version cannot be stopped manually and the window cannot pop up when the icon is clicked

### ISSUE THREAD

**Issue by zhangbo8418** [rustdesk/rustdesk#3260] opened 2023-02-18 01:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug Description

The Mac version cannot be stopped manually and the window cannot pop up when the icon is clicked

### How to Reproduce

The Mac version cannot be stopped manually and the window cannot pop up when the icon is clicked

### Expected Behavior

log out manually

### Operating system(s) on local side and remote side

MacOS Ventura1 3.2.1

### RustDesk Version(s) on local side and remote side

1.20

### Screenshots

![21cb902176bdcb152f6c46599d0f08aa](https://user-images.githubusercontent.com/46797568/219823607-6fa91b27-83ef-4b1a-a9c9-e216ce559f5c.png)

Updates can only be manually forced to delete.

![fd5f77cfb447917eae1c27246378fe6a](https://user-images.githubusercontent.com/46797568/219823744-afda694c-4b97-4454-b265-6aab69257443.png)

**Comment by rustdesk** [comment] 2023-02-18 01:40
title?

**Comment by wakewon** [comment] 2023-02-18 08:34
It seems that `com.carriez.RustDesk_service.plist` always keeps rustdesk running at the background, making it cannot be replaced or restarted. Manually unload this daemon can solve this issue.

Also, rustdesk v1.2.0 cannot be granted with screen recording permission even the option in system preferences is enabled. The above problem also prevent restdesk to be restarted again.

**Comment by working-name** [comment] 2023-02-19 03:14
Confirmed, this has been an issue ever since I started working with rustdesk. It has to do with the launchctl daemon config. I manually removed mine and it stopped giving me that issue, but that was only on a laptop which I use to connect to my stuff, but never need it to run 24/7.

Now that I've updated the app on my big mac it's giving me trouble. I'm assuming a full removal + reinstall might do.

**Comment by rustdesk** [comment] 2023-02-19 03:40
this will be fixed together with #912

**Comment by rustdesk** [comment] 2023-02-19 03:42
we started already, close to favor #912

**Closed** 2023-02-19 03:42 UTC

**Comment by rustdesk** [comment] 2023-02-19 03:43
including pop window
