### ISSUE TITLE
toggle privacy mode failed

### ISSUE THREAD

**Issue by xtyuns** [rustdesk/rustdesk#5714] opened 2023-09-16 18:53 UTC
### Bug Description

A(win11) control B(win11): privacy mode works fine
BUT, B control A: privacy mode works failed

![image](https://github.com/rustdesk/rustdesk/assets/41326335/ef2f1d6f-c8af-42b5-a89c-5a204a58e04a)

### How to Reproduce

Use the toolbar to enable privacy mode after connecting

### Expected Behavior

Switch to privacy mode

### Operating system(s) on local side and remote side

Windows 11 -> Windows 11

### RustDesk Version(s) on local side and remote side

1.2.2 -> 1.2.2

### Screenshots

https://github.com/rustdesk/rustdesk/assets/41326335/5fb7125a-9b58-4329-bdea-03378af92bb9

**Comment by rustdesk** [comment] 2023-09-17 01:07
@fufesou remove this stupid "Failure" meaningless message.

**Comment by rustdesk** [comment] 2023-09-17 01:09
Also check if there are the other similar messages.

**Comment by rustdesk** [comment] 2023-09-18 03:37
Please install the latest nightly build on both side, tell us the new messages.

**Comment by xtyuns** [comment] 2023-09-18 13:53
> Please install the latest nightly build on both side, tell us the new error messages. Thanks!

仍然是上述现象

**Comment by rustdesk** [comment] 2023-09-18 13:58
@fufesou follow up

**Comment by fufesou** [comment] 2023-09-18 14:20
@xtyuns Hi, I've add the missing place to fill the details.

You can also find the error on the controlled side.

https://github.com/rustdesk/rustdesk/blob/master/src/server/connection.rs#L2262

The error log contains "Failed to turn on privacy mode. [THE ERROR MESSAGE]"

The log file is 
```
installed version:  C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log

portable version: %appdata%\RustDesk\log\RustDesk_rCURRENT.log
```

**Comment by xtyuns** [comment] 2023-09-18 14:36
> @xtyuns Hi, I've added the missing place to fill the details in #5737. Please try out tomorrow's nightly build, and let us know. Sorry for the inconvenience.
> 
> You can also find the error on the controlled side.
> 
> https://github.com/rustdesk/rustdesk/blob/master/src/server/connection.rs#L2262
> 
> The error log contains "Failed to turn on privacy mode. [THE ERROR MESSAGE]"
> 
> Please paste here if you find it. The log file is
> 
> ```
> installed version:  C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\log\server\RustDesk_rCURRENT.log
> 
> portable version: %appdata%\RustDesk\log\RustDesk_rCURRENT.log
> ```

```log
[2023-09-18 21:47:28.408991 +08:00] ERROR [src\server\connection.rs:2262] Failed to turn on privacy mode. Failed to get hwnd after started
...
[2023-09-18 21:50:01.680868 +08:00] ERROR [src\server\connection.rs:2262] Failed to turn on privacy mode. No privacy window created
```

**Comment by fufesou** [comment] 2023-09-18 23:53
It seems the privacy window cannot be created.

Can you please try the test app here?
https://github.com/fufesou/RustDeskTempTopMostWindow/releases/tag/v0.1

https://github.com/rustdesk/rustdesk/assets/13586388/97f0dc1b-090f-427c-a2cd-5244cb69a4c0

The whole screen will be covered by a fullscreen window.
After 5 seconds, the window will be destroyed.

```C
		printf("now hide window\n");
		ShowWindow(hwnd, SW_HIDE);
		std::this_thread::sleep_for(std::chrono::milliseconds(1 * 1000));

		printf("now show window\n");
		ShowWindow(hwnd, SW_SHOW);
		std::this_thread::sleep_for(std::chrono::milliseconds(1 * 1000));

		std::this_thread::sleep_for(std::chrono::milliseconds(5 * 1000));
		printf("now destroy window\n");
		PostMessage(hwnd, WM_CLOSE, NULL, NULL);
```

**Comment by xtyuns** [comment] 2023-09-19 02:03
> It seems the privacy window cannot be created.
> 
> Can you please try the test app here? https://github.com/fufesou/RustDeskTempTopMostWindow/releases/tag/v0.1
> 
>  topmostwindow.mp4 
> The whole screen will be covered by a fullscreen window. After 5 seconds, the window will be destroyed.
> 
> ```c
> 		printf("now hide window\n");
> 		ShowWindow(hwnd, SW_HIDE);
> 		std::this_thread::sleep_for(std::chrono::milliseconds(1 * 1000));
> 
> 		printf("now show window\n");
> 		ShowWindow(hwnd, SW_SHOW);
> 		std::this_thread::sleep_for(std::chrono::milliseconds(1 * 1000));
> 
> 		std::this_thread::sleep_for(std::chrono::milliseconds(5 * 1000));
> 		printf("now destroy window\n");
> 		PostMessage(hwnd, WM_CLOSE, NULL, NULL);
> ```

TestApp works fine with UAC authorization on machine A.
But, the privacy mode is still not activated when B controls A.

ps: The first pop-up window may be UAC, I don't remember, because it only exists when running TestApp for the first time, It only popped up on machine A.

**Comment by fufesou** [comment] 2023-09-19 12:01
It's wired that the TestApp.exe and rustdesk do the same things.

1. Start a new process, create a fullscreen privacy window.
2. Wait the window to be ready.

And the process should not request privilege.
I'm not sure if there's some different privilege settings that affect.


Can you please also try the attached TestApp.zip?
Just extract the file to the same directory of rustdesk.
```
installed version: C:\Program Files\RustDesk (if you did not change path)
portable version: %userprofile%\AppData\Local\rustdesk
```

The difference of this build is it start `RuntimeBroker_rustdesk.exe` in the rustdesk directory.

[TestApp.zip](https://github.com/rustdesk/rustdesk/files/12659430/TestApp.zip)

**Comment by xtyuns** [comment] 2023-09-19 14:53
TestApp：Ok
![Snipaste_2023-09-19_22-40-40](https://github.com/rustdesk/rustdesk/assets/41326335/19a1e3ea-a853-4251-a9f0-09428dbd2e7f)

RustDesk privacy mode：Failure
![image](https://github.com/rustdesk/rustdesk/assets/41326335/62d6c71e-34d0-4ca6-8b57-15d7ec8526be)

**Comment by xtyuns** [comment] 2023-09-19 14:57
I installed the nightly released today, and the error message displayed now is: Failed to get hwnd after started

**Comment by xtyuns** [comment] 2023-09-19 15:04
Possibly some useful log messages:
```
[2023-09-19 22:55:30.372678 +08:00] INFO [libs\scrap\src\common\codec.rs:549] cpu num:8, cpu usage:Some(6.8384640723159125), codec thread:4
[2023-09-19 22:55:30.406348 +08:00] INFO [src\server\video_service.rs:549] gdi: false
[2023-09-19 22:55:30.417465 +08:00] INFO [src\server\service.rs:133] Call snapshot of video service
[2023-09-19 22:55:30.567956 +08:00] INFO [src\server\service.rs:133] Call snapshot of clipboard service
[2023-09-19 22:55:33.304158 +08:00] INFO [src\server\connection.rs:2126] Option update: OptionMessage { image_quality: NotSet, lock_after_session_end: NotSet, show_remote_cursor: NotSet, privacy_mode: Yes, block_input: NotSet, custom_image_quality: 0, disable_audio: NotSet, disable_clipboard: NotSet, enable_file_transfer: NotSet, supported_decoding: MessageField(None), custom_fps: 0, disable_keyboard: NotSet, special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[2023-09-19 22:55:33.313170 +08:00] INFO [src\privacy_win_mag.rs:99] turn_on_privacy, dll not found when started, try start
[2023-09-19 22:55:34.302630 +08:00] DEBUG [libs\hbb_common\src\config.rs:475] Configuration path: C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\RustDesk\config\RustDesk_local.toml
[2023-09-19 22:55:35.548263 +08:00] ERROR [src\server\connection.rs:2262] Failed to turn on privacy mode. Failed to get hwnd after started
[2023-09-19 22:55:42.033151 +08:00] DEBUG [src\server\connection.rs:912] error sending request for url (http://SELF_HOST:21114/api/audit/conn): operation timed out

Caused by:
    operation timed out, librustdesk::server::connection:src\server\connection.rs:912:13
[2023-09-19 22:55:42.330915 +08:00] DEBUG [src\server\connection.rs:912] error sending request for url (http://SELF_HOST:21114/api/audit/conn): operation timed out

Caused by:
    operation timed out, librustdesk::server::connection:src\server\connection.rs:912:13
[2023-09-19 22:55:59.421661 +08:00] DEBUG [src\common.rs:250] ClipboardOccupied - "The native clipboard is not accessible due to being held by an other party.", librustdesk::common:src\common.rs:250:17
[2023-09-19 22:55:59.421851 +08:00] DEBUG [src\common.rs:251] clipboard updated on host
[2023-09-19 22:56:33.446319 +08:00] DEBUG [src\common.rs:250] ClipboardOccupied - "The native clipboard is not accessible due to being held by an other party.", librustdesk::common:src\common.rs:250:17
[2023-09-19 22:56:33.446488 +08:00] DEBUG [src\common.rs:251] clipboard updated on host
[2023-09-19 22:56:46.801559 +08:00] DEBUG [src\common.rs:250] ClipboardOccupied - "The native clipboard is not accessible due to being held by an other party.", librustdesk::common:src\common.rs:250:17
[2023-09-19 22:56:46.801795 +08:00] DEBUG [src\common.rs:251] clipboard updated on host
[2023-09-19 22:56:59.451633 +08:00] DEBUG [src\common.rs:250] ClipboardOccupied - "The native clipboard is not accessible due to being held by an other party.", librustdesk::common:src\common.rs:250:17
[2023-09-19 22:56:59.451869 +08:00] DEBUG [src\common.rs:251] clipboard updated on host
[2023-09-19 22:57:29.451880 +08:00] INFO [src\platform\windows.rs:674] Desktop switched
[2023-09-19 22:57:29.472663 +08:00] ERROR [src\server\service.rs:207] Error of mouse_cursor service: 拒绝访问。 (os error 5)
[2023-09-19 22:57:29.490708 +08:00] ERROR [src\server\service.rs:242] Error of video service: Desktop changed
[2023-09-19 22:57:29.535879 +08:00] INFO [src\platform\windows.rs:674] Desktop switched
[2023-09-19 22:57:29.567158 +08:00] DEBUG [src\server\service.rs:239] Enter video service inner loop
[2023-09-19 22:57:29.573525 +08:00] DEBUG [src\server\video_service.rs:389] #displays=1, current=0, origin: (0, 0), width=1920, height=1080, cpus=4/8, name:\\.\DISPLAY1
[2023-09-19 22:57:29.573552 +08:00] DEBUG [src\server\video_service.rs:412] Try create capturer with capturer privacy mode id 0
[2023-09-19 22:57:29.573559 +08:00] DEBUG [src\server\video_service.rs:303] Create capturer dxgi|gdi
[2023-09-19 22:57:29.573564 +08:00] DEBUG [src\server\portable_service.rs:915] Create capturer dxgi|gdi
[2023-09-19 22:57:29.585849 +08:00] INFO [src\server\video_service.rs:493] init quality=Best, abr enabled:true
[2023-09-19 22:57:29.585881 +08:00] INFO [libs\scrap\src\common\codec.rs:111] new encoder:VPX(VpxEncoderConfig { width: 1920, height: 1080, quality: Best, codec: VP9, keyframe_interval: None })
[2023-09-19 22:57:29.585899 +08:00] INFO [libs\scrap\src\common\codec.rs:549] cpu num:8, cpu usage:Some(0.8521576108222836), codec thread:4
[2023-09-19 22:57:29.608783 +08:00] INFO [src\server\video_service.rs:549] gdi: false
[2023-09-19 22:57:30.486262 +08:00] INFO [src\platform\windows.rs:674] Desktop switched
[2023-09-19 22:57:32.079917 +08:00] ERROR [src\server\service.rs:207] Error of mouse_cursor service: 拒绝访问。 (os error 5)
[2023-09-19 22:57:32.119322 +08:00] ERROR [src\server\service.rs:242] Error of video service: Desktop changed
[2023-09-19 22:57:32.152300 +08:00] INFO [src\platform\windows.rs:674] Desktop switched
[2023-09-19 22:57:32.183033 +08:00] DEBUG [src\server\service.rs:239] Enter video service inner loop
[2023-09-19 22:57:32.198720 +08:00] DEBUG [src\server\video_service.rs:389] #displays=1, current=0, origin: (0, 0), width=1920, height=1080, cpus=4/8, name:\\.\DISPLAY1
[2023-09-19 22:57:32.198769 +08:00] DEBUG [src\server\video_service.rs:412] Try create capturer with capturer privacy mode id 0
[2023-09-19 22:57:32.198783 +08:00] DEBUG [src\server\video_service.rs:303] Create capturer dxgi|gdi
[2023-09-19 22:57:32.198796 +08:00] DEBUG [src\server\portable_service.rs:915] Create capturer dxgi|gdi
[2023-09-19 22:57:32.218977 +08:00] INFO [src\server\video_service.rs:493] init quality=Best, abr enabled:true
[2023-09-19 22:57:32.219027 +08:00] INFO [libs\scrap\src\common\codec.rs:111] new encoder:VPX(VpxEncoderConfig { width: 1920, height: 1080, quality: Best, codec: VP9, keyframe_interval: None })
[2023-09-19 22:57:32.219047 +08:00] INFO [libs\scrap\src\common\codec.rs:549] cpu num:8, cpu usage:Some(1.3284013738003284), codec thread:4
[2023-09-19 22:57:32.257758 +08:00] INFO [src\server\video_service.rs:549] gdi: false
[2023-09-19 22:57:32.335066 +08:00] INFO [src\platform\windows.rs:674] Desktop switched
[2023-09-19 22:57:33.088195 +08:00] INFO [src\platform\windows.rs:674] Desktop switched
[2023-09-19 22:58:35.487426 +08:00] INFO [src\server\connection.rs:2126] Option update: OptionMessage { image_quality: NotSet, lock_after_session_end: NotSet, show_remote_cursor: NotSet, privacy_mode: Yes, block_input: NotSet, custom_image_quality: 0, disable_audio: NotSet, disable_clipboard: NotSet, enable_file_transfer: NotSet, supported_decoding: MessageField(None), custom_fps: 0, disable_keyboard: NotSet, special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[2023-09-19 22:58:35.488133 +08:00] ERROR [src\server\connection.rs:2262] Failed to turn on privacy mode. No privacy window created
[2023-09-19 22:58:39.969283 +08:00] INFO [src\server\connection.rs:2126] Option update: OptionMessage { image_quality: NotSet, lock_after_session_end: NotSet, show_remote_cursor: NotSet, privacy_mode: Yes, block_input: NotSet, custom_image_quality: 0, disable_audio: NotSet, disable_clipboard: NotSet, enable_file_transfer: NotSet, supported_decoding: MessageField(None), custom_fps: 0, disable_keyboard: NotSet, special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }
[2023-09-19 22:58:39.969492 +08:00] ERROR [src\server\connection.rs:2262] Failed to turn on privacy mode. No privacy window created

```

**Comment by fufesou** [comment] 2023-09-20 12:14
I have no idea why the privacy window can't be found.
This issue may not be fixed in a short time.

@xtyuns Thanks for all your feedback.

Can you please test again to see if the "RuntimeBroker_rustdesk.exe" exists?
The privay window depends on "RuntimeBroker_rustdesk.exe".

1. "B" -> "A".
2. Turn on privacy mode. Use TaskManager on "A" to see if "RuntimeBroker_rustdesk.exe" exists.

**Comment by xtyuns** [comment] 2023-09-20 13:05
A:
![b155e728ff1766e1a379099d3ea208c8](https://github.com/rustdesk/rustdesk/assets/41326335/c10c4791-4edf-4e5a-b42a-4658ac435940)

But when using B to turn on A privacy mode, it doesn't work as expected.

In turn, RuntimeBroker_rustdesk.exe in B works as expected and the "Runtime Broker" process appears in the task manager

**Comment by fufesou** [comment] 2023-09-20 13:14
So "RuntimeBroker_rustdesk.exe" cannot be started on "A" by rustdesk. And you can run it manually.

Can you please restart the rustdesk service on "A", and test again?
By sign out and sign in or restart the PC, or restart the rustdesk service.

Because "RuntimeBroker_rustdesk.exe" may only be started one time in the lifetime of the rustdesk server process.

The first time when trying to start "RuntimeBroker_rustdesk.exe", you may see the error "Failed to get hwnd after started".
And then the errors are "No privacy window created".

**Comment by xtyuns** [comment] 2023-09-20 13:21
I've tried restarting the service and it still doesn't work.

I just manually double-clicked to start RuntimeBroker_rustdesk.exe, and after I saw it in task manager I tried to turn on privacy mode again, and it still gives me the error.

**Comment by dignow** [comment] 2023-09-20 13:39
Yes. Just double-click "RuntimeBroker_rustdesk.exe" dose not work.

What rustdesk do is 
1. start "RuntimeBroker_rustdesk.exe".
2. inject the "WindowInjection.dll".

rustdesk holds the sub process id of its own subprocess("RuntimeBroker_rustdesk.exe"). Manually run "RuntimeBroker_rustdesk.exe" has no effect.

The attached TestApp in https://github.com/rustdesk/rustdesk/issues/5714#issuecomment-1725371746 does the same thing.
You said it's ok if you try to run TestApp. https://github.com/rustdesk/rustdesk/issues/5714#issuecomment-1725804754

I cannot understand why the "RuntimeBroker_rustdesk.exe" cannot be started by rustdesk.

**Comment by fufesou** [comment] 2023-09-20 13:43
Yes. Just double-click "RuntimeBroker_rustdesk.exe" dose not work.

What rustdesk do is 
1. start "RuntimeBroker_rustdesk.exe".
2. inject the "WindowInjection.dll".

rustdesk holds the sub process id of its own subprocess("RuntimeBroker_rustdesk.exe"). Manually run "RuntimeBroker_rustdesk.exe" has no effect.

The attached TestApp in https://github.com/rustdesk/rustdesk/issues/5714#issuecomment-1725371746 does the same thing.
You said it's ok if you try to run TestApp. https://github.com/rustdesk/rustdesk/issues/5714#issuecomment-1725804754

I cannot understand why the "RuntimeBroker_rustdesk.exe" cannot be started by rustdesk.

**Comment by xtyuns** [comment] 2023-09-20 13:50
https://github.com/fufesou/RustDeskTempTopMostWindow/releases/tag/v0.1
```
now hide window
TURN ON PRIVACY MODE
```

https://github.com/rustdesk/rustdesk/issues/5714#issuecomment-1725371746
```
Failed CreateProcess, 0x2,
```

**Comment by fufesou** [comment] 2023-09-20 13:51
Maybe you download and run the wrong file. Do you run x86 exe on x64 PC?

**Comment by xtyuns** [comment] 2023-09-20 13:56
My computer is x64 and i download installer is:
https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.3-x86_64.exe

**Comment by xtyuns** [comment] 2023-09-20 13:59
@fufesou
https://github.com/rustdesk/rustdesk/issues/5714#issuecomment-1727775605
The first one was successful, the second TestApp failed

**Comment by fufesou** [comment] 2023-09-20 14:11
Is it ok if you run the file in https://github.com/rustdesk/rustdesk/issues/5714#issuecomment-1727775605 on your PC "B" in the directory of rustdesk?

**Comment by xtyuns** [comment] 2023-09-20 14:12
> After puting the attached file in the same directory of rustdesk, you still get the error?
> 
> ```
> Failed CreateProcess, 0x2,
> ```
> 
> Maybe it's the reason.
> 
> But I still cannot understand. Code 0x2 means the file cannot be found. And I also checked the result in rustdesk, it should report "Failed to create privacy window process..." if it failed to create the subprocess.
> 
> ![222](https://user-images.githubusercontent.com/13586388/269310832-1d6e9e9b-4da5-4017-8fe5-f075f3e5065b.png)

sorry, I made a mistake. After puting the attached file in the same directory of rustdesk the second TestApp running successful

**Comment by fufesou** [comment] 2023-09-20 14:21
Thanks.
The reason should be that "RuntimeBroker_rustdesk.exe" is started by rustdesk, but then the child process exits unexpectedly.

Can you please try again without installation? Just to make sure if the process user affects.

Sorry for the inconvenience, but I cannot reproduce it.

**Comment by xtyuns** [comment] 2023-09-20 14:59
@fufesou Privacy mode in Portable works fine

**Comment by fufesou** [comment] 2023-09-20 15:14
😢   The privilege strategy is strange.

**Comment by Creling** [comment] 2023-09-21 06:39
BTW, what about the performance of privacy mode now? Does it brings delays and lag still like the pervious versions?

**Comment by rustdesk** [comment] 2023-09-21 06:45
This one is still laggy. We have another implementation of privacy mode based on virtual display, but not released yet.

**Comment by Creling** [comment] 2023-09-21 06:47
Glad to hear that another implementation is done. Hoping to see it soon.

**Comment by rustdesk** [comment] 2023-10-23 09:14
close this since we are writing new privacy mode implemetation. Current privacy mode has a lot of limit, especially low fps.

**Closed by rustdesk** 2023-10-23 09:14 UTC
Labels: bug

**Comment by geeklihui** [comment] 2024-05-28 06:08
@rustdesk Sorry to bother, I just wonder if any progress about new privacy mode? I got similar error code with this author. 
![image](https://github.com/rustdesk/rustdesk/assets/28993319/dea42246-dd33-4bd9-b7db-b6c0bb90d562)

![image](https://github.com/rustdesk/rustdesk/assets/28993319/b508ba2d-96b8-4619-9228-dfca8ce3a2d5)
