### ISSUE TITLE
Mac client Screen flickering

### ISSUE THREAD

**Issue by k-k-s-s** [rustdesk/rustdesk#6296] opened 2023-11-05 14:21 UTC
### Bug Description

When using mac remote control windows, mac RustDesk1.2.x version will have screen flickering bug. switch back to mac RustDesk1.1.8, the screen flickering bug disappeared, hope to fix the mac RustDesk1.2.x version bug as soon as possible.

### How to Reproduce

use  1.2.x version mac client to control windows. the server is windows itself.

### Expected Behavior

screen flickers.

### Operating system(s) on local side and remote side

osx ---> windows 10

### RustDesk Version(s) on local side and remote side

1.2.3-->1.2.3

### Screenshots

I can't catch the screen flicker bug.

**Comment by k-k-s-s** [comment] 2023-11-05 14:26
I use intel mac.

**Comment by 21pages** [comment] 2023-11-05 14:27
> I can't catch the screen flicker bug.

Could you record a video ?

**Comment by k-k-s-s** [comment] 2023-11-05 16:34
> > I can't catch the screen flicker bug.
> 
> Could you record a video ?


https://github.com/rustdesk/rustdesk/assets/7893382/1fd73eb9-b335-4fbd-a3df-47fba6fc65d2

Okay, here's the recorded video, using a mac to control windows

**Comment by k-k-s-s** [comment] 2023-11-05 16:36
I've tested version 1.2.3, 1.2.4 and they all have this problem, switching back to 1.1.8 is fine, but there is a problem with the playback sound.

**Comment by yeziyezi** [comment] 2023-11-15 02:48
I also use Intel Mac to control Windows, there are the same problem.
The version is 1.2.3.

**Comment by intoku** [comment] 2023-11-28 20:24
This is also happening to me, and is quite annoying. Using 1.2.3 on Mac. 
I have noticed is that the flickering was less when i fully lowered the resolution on the remote computer like 1024x768.

**Comment by halfkai** [comment] 2023-12-28 03:07
Had the same issue when remote connecting from Mac to Win11, but when connecting from another Win10 to Win11, no flickering issue.

**Comment by zhaoxuan** [comment] 2023-12-29 03:13
I have the same problem in my Intel mac.
The mac version is 14.2.1.

**Comment by fuhuo** [comment] 2024-01-21 08:59
the same problem.
rustdesk version: 1.2.3、1.2.4
intel mac version 10.15.3
remote: win11

**Comment by hadim** [comment] 2024-01-30 16:48
I have the same issue with a MacBook Pro M3 and Sonoma 14.3.

**Comment by PJaros** [comment] 2024-02-08 08:35
I had the issue with Linux (Ubuntu 18.04) 1.2.3 -> Mac (I don't know the spec) 1.2.3

Most interesting only the primary monitor (Laptop LCD) flickered. The secondary screen didn't.

**Comment by 9840380** [comment] 2024-02-23 21:56
same
Monterey 12.7.1 Macbook pro 2015 15
RustDesktop 1.2.3 (39)

**Comment by poffio** [comment] 2024-03-17 15:23
Hi, I have the same issue.
MacBook Pro Intel 13-inch 2020
OS Sonoma 14.2.1
RustDesktop 1.2.3 (39)

Thank you !

**Comment by cwhypt** [comment] 2024-04-05 00:54
I was able to reproduce the issue on my Macbook Pro 13-inch 2020, OS 14.2.1. Using the 1.2.3 version with flutter from Macbook to Windows server shows the screen flickering, while installing the 1.1.8 version fixes the problem as previously mentioned in the thread. 

I tried compling macbook locally, with the Sciter GUI it was fine, while trying the flutter GUI the problem occurs. Below is the console log (with some personal identifier deleted). I'm new to rust and flutter so I'm still learning, would appreciate any suggestions/feedbacks on further debugging the issue:

```
[2024-04-05T00:41:06Z INFO  librustdesk::core_main] main start args:[]
[2024-04-05T00:41:06Z INFO  librustdesk::server] server not started (will try to start): Connection refused (os error 61)
[2024-04-05T00:41:06Z INFO  librustdesk::common] Testing nat ...
[2024-04-05T00:41:06Z INFO  librustdesk::rendezvous_mediator] start rendezvous mediator of 
[2024-04-05T00:41:06Z INFO  librustdesk::ipc] Started ipc server at path: /tmp/RustDesk/ipc
[2024-04-05T00:41:06Z INFO  librustdesk::common] Tested nat type: ASYMMETRIC in 76.881192ms
2024-04-04 17:41:06.190 RustDesk[] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
[2024-04-05T00:41:06Z INFO  librustdesk::server] #1 try: failed to connect to ipc_service
[2024-04-05T00:41:07Z INFO  librustdesk::server] #2 try: failed to connect to ipc_service
flutter: launch args: []
flutter: initializing FFI main
flutter: _appType:main,info1-id:
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler native_ui native_ui
flutter: pullAb, force: ForcePullAb.listAndCurrent, quiet: false
[2024-04-05T00:41:07Z INFO  librustdesk::server] #3 try: failed to connect to ipc_service
[2024-04-05T00:41:07Z WARN  librustdesk::server] skipped config sync
Syncing files to device macOS...                                   193ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

A Dart VM Service on macOS is available at: http://127.0.0.1:50209/
flutter: registerEventHandler callback_query_onlines recent peer
flutter: registerEventHandler load_recent_peers recent peer
The Flutter DevTools debugger and profiler on macOS is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:50209/
flutter: pullAb, force: ForcePullAb.listAndCurrent, quiet: false
flutter: restore lpos: 800.0/601.0, offset:662.0/304.0
flutter: Bring window 'null' on top
flutter: handled by uni links: true
flutter: [MultiWindowHandler] active window changed: {0}
flutter: Saving frame: null: 800.0/601.0, offset:599.0/299.0, isMaximized:false, isFullscreen:false
embedder.cc (2525): 'FlutterPlatformMessageCreateResponseHandle' returned 'kInvalidArguments'. Engine handle was invalid.
2024-04-04 17:41:28.829 RustDesk Failed to create a FlutterPlatformMessageResponseHandle (2)
embedder.cc (2525): 'FlutterPlatformMessageCreateResponseHandle' returned 'kInvalidArguments'. Engine handle was invalid.
2024-04-04 17:41:28.829 RustDesk Failed to create a FlutterPlatformMessageResponseHandle (2)
flutter: [MultiWindowHandler] active window changed: {0, 1}
embedder.cc (2525): 'FlutterPlatformMessageCreateResponseHandle' returned 'kInvalidArguments'. Engine handle was invalid.
2024-04-04 17:41:28.898 RustDesk Failed to create a FlutterPlatformMessageResponseHandle (2)
flutter: launch args: [multi_window, 1, {"type":1,"id":"","password":"","forceRelay":false,"isSharedPassword":false}]
flutter: initializing FFI remote
flutter: _appType:remote,info1-id:
flutter: _globalFFI init
flutter: _globalFFI init end
flutter: registerEventHandler theme theme
flutter: registerEventHandler language language
flutter: registerEventHandler native_ui native_ui
2024-04-04 17:41:29.591 RustDesk[] IOHIDCheckAccess = 0, kIOHIDAccessTypeGranted = 0
flutter: CustomTouchGestureRecognizer init
flutter: [Main] call get_window_info with args  from window 1
flutter: onFocusChange(window active:true) true
flutter: restore lpos: 1300.0/740.0, offset:164.0/128.0
flutter: create pixelbuffer texture: peerId: 496683771 display:0, textureId:105553129405504
flutter: isMaximized false
flutter: restore lpos: 1300.0/740.0, offset:134.0/98.0
flutter: onFocusChange(window active:true) false
flutter: onFocusChange(window active:true) true
flutter: onFocusChange(window active:true) false
flutter: [Main] call get_window_info with args  from window 1
flutter: CustomTouchGestureRecognizer init
flutter: onFocusChange(window active:true) true
flutter: onFocusChange(window active:true) false
flutter: EventToUI_Rgba display:0
flutter: setTextureType: display:0, isGpuTexture:false
flutter: Saving frame: 1: 1300.0/740.0, offset:134.0/98.0, isMaximized:false, isFullscreen:false
flutter: CustomTouchGestureRecognizer init
flutter: [Main] call get_window_info with args  from window 1
flutter: CustomTouchGestureRecognizer init
flutter: onFocusChange(window active:true) true
flutter: [Remote Page] call get_remote_list with args null from window 1
flutter: onFocusChange(window active:true) false
flutter: Saving frame: 1: 1300.0/740.0, offset:500.0/96.0, isMaximized:false, isFullscreen:false
flutter: [Remote Page] call get_remote_list with args null from window 1
flutter: onFocusChange(window active:true) true
flutter: Register custom cursor with key 496683771_65539_320000000_320000000 (0.0,0.0)
flutter: Register custom cursor with key 496683771_61343461_320000000_320000000 (15.0,15.0)
flutter: Saving frame: 1: 1300.0/740.0, offset:564.0/50.0, isMaximized:false, isFullscreen:false
flutter: [Remote Page] call get_remote_list with args null from window 1
flutter: Register custom cursor with key 496683771_65555_320000000_320000000 (4.0,11.0)
flutter: onPointDownImage PointerDeviceKind.mouse
flutter: addAllowedPointer
flutter: start oneFingerPan
flutter: ScaleGestureRecognizer onEnd
flutter: TwoFingerState.pan onEnd
flutter: Register custom cursor with key 496683771_1552287783_320000000_320000000 (9.0,9.0)
flutter: Register custom cursor with key 496683771_65553_320000000_320000000 (11.0,4.0)
flutter: onPointDownImage PointerDeviceKind.mouse
flutter: addAllowedPointer
flutter: start oneFingerPan
flutter: ScaleGestureRecognizer onEnd
flutter: TwoFingerState.pan onEnd
flutter: REMOTE PAGE dispose session 
flutter: deleting cursor with key 496683771_65539_320000000_320000000
flutter: deleting cursor with key 496683771_61343461_320000000_320000000
flutter: deleting cursor with key 496683771_65555_320000000_320000000
flutter: deleting cursor with key 496683771_1552287783_320000000_320000000
flutter: deleting cursor with key 496683771_65553_320000000_320000000
flutter: model closed
flutter: [Main] call hide with args {id: 1} from window 1
flutter: [MultiWindowHandler] active window changed: {0}
flutter: destroy pixelbuffer texture: peerId:  display:0, textureId:105553129405504
Application finished.
```

**Comment by dennisproppe** [comment] 2024-04-30 12:34
Dear RustDesk-Team, I am also running into this issue.

MacBook Pro Intel 13-inch 2020
OS Sonoma 14.4.1
RustDesktop 1.2.3 (39)

Unfortunately, the flickering appears very frequently (approx. every 3-5 seconds), so it is very cumbersome to use - Can I do anything to help here? I see the bug is marked as unreproducible, which for me it isn't. Or is there a duplicate somewhere that is being worked on?

Thanks a lot in advance!

**Comment by rustdesk** [comment] 2024-04-30 12:42
How about nightly? https://github.com/rustdesk/rustdesk/releases/tag/nightly

**Comment by dennisproppe** [comment] 2024-04-30 12:47
@rustdesk : Thanks for the blazingly fast answers. I tried it with the nightly DMG for Intel ([rustdesk-1.2.4-x86_64.dmg](https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64.dmg), the issue remains the same (Connected to Windows 11 machine).

Thanks a lot, Dennis

**Comment by rustdesk** [comment] 2024-04-30 13:08
We will build a version for you test, wait one moment.

**Comment by 21pages** [comment] 2024-04-30 13:16
@dennisproppe Could you try https://github.com/21pages/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64-x86_64-no-texture-render.dmg?

**Comment by dennisproppe** [comment] 2024-04-30 13:41
Hi, thanks for the version - Unfortunately it crashes on startup, it seems as if there is flutter problem:

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/FlutterMacOS.framework/Versions/A/FlutterMacOS
Referenced from: <8E853059-DF60-3EE4-B425-61238A5E42B8> /Applications/RustDesk.app/Contents/MacOS/RustDesk
Reason: tried: '/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Applications/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (code signature in <4C4C44DF-5555-3144-A12B-6A006FC7413F> '/Applications/RustDesk.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/Applications/RustDesk.app/Contents/MacOS/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS' (no such file), '/Applications/Xcode_15.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/FlutterMacOS.framework/Versio
(terminated at launch; ignore backtrace)

**Comment by hadim** [comment] 2024-04-30 15:17
I don't think it's intel related since I see the same problem with M3.

**Comment by rustdesk** [comment] 2024-04-30 15:56
Please try out this new build, https://github.com/rustdesk/rustdesk/releases/download/nightly/rustdesk-1.2.4-x86_64.dmg
Also can test it on M3

**Comment by cwhypt** [comment] 2024-04-30 18:13
Hi, on my Macbook Pro 13-inch 2020, OS 14.2.1 the flickering issue seems to have disappeared. Thanks for fixing it! More datapoints may be helpful to confirm it.

**Comment by hadim** [comment] 2024-04-30 20:14
I don't see the glitch as well anymore on my side.

**Comment by rustdesk** [comment] 2024-05-03 08:17
Close as fixed in nightly build.

**Closed by rustdesk** 2024-05-03 08:17 UTC
Labels: bug, unreproducible
